import type {Metadata} from "next";
import Link from "next/link";
import {AlertTriangle,CheckCircle2,ClipboardCheck,ExternalLink,FileText,GraduationCap,HeartHandshake,MailCheck,Scale,ShieldCheck,Users} from "lucide-react";
import {createAdminClient} from "@/lib/supabase/admin";
import {signHowardPetition,submitHowardCase} from "./actions";

export const metadata:Metadata={title:"Howard Help Desk | Esther Funds Foundation",description:"Consent-based enrollment rescue, reinstatement advocacy, verified resources, and collective action for affected Howard University students."};

type Query={case?:string;code?:string;error?:string;petition?:string;petitionError?:string};
const issueOptions=["Admission rescinded","Classes removed","Housing at risk","Unexpected balance change","Pending federal or institutional aid","Pending external scholarship","Pending waiver or discount","Payment plan problem","Other"];
const statusOptions=["Admission canceled","Unregistered or inactive","Courses dropped or withdrawn","Housing canceled or at risk","Still enrolled but at immediate risk","Unsure"];

export default async function HowardHelp({searchParams}:{searchParams:Promise<Query>}){
  const query=await searchParams;let signatures=0;let verifiedCases=0;
  try{const admin=createAdminClient();const [petition,cases]=await Promise.all([admin.from("howard_petition_signatures").select("id",{count:"exact",head:true}).not("verified_at","is",null),admin.from("howard_help_cases").select("id",{count:"exact",head:true}).not("verified_at","is",null)]);signatures=petition.count??0;verifiedCases=cases.count??0;}catch{}
  return <main className="howard-help-page">
    <section className="howard-hero"><div className="shell howard-hero-grid"><div><Link className="back-link" href="/resources">← Student Help Center</Link><div className="eyebrow">Howard University Student Rescue</div><h1>Reinstate every <span>affected student.</span></h1><p>EFF is organizing verified cases, sending consent-based reinstatement requests, and building a documented collective record. Your future should not disappear because aid, scholarships, waivers, discounts, or account corrections were still being processed.</p><div className="hero-actions"><a className="button light" href="#case-intake">Open a case</a><a className="button lavender" href="#petition">Sign the petition</a></div></div><aside className="howard-hero-card"><HeartHandshake/><strong>Our requested outcome is complete reinstatement.</strong><p>Howard University controls enrollment decisions. EFF will advocate for restoration of admission, classes, housing, and pending aid while each account is reviewed.</p><small>No application fee. No promise we cannot control. No sensitive documents by ordinary email.</small></aside></div></section>
    <section className="howard-status"><div className="shell"><div><strong>{verifiedCases}</strong><span>verified student case{verifiedCases===1?"":"s"}</span></div><div><strong>{signatures}</strong><span>verified petition signature{signatures===1?"":"s"}</span></div><p>Counts update after email verification. They are not estimates of all affected students.</p></div></section>
    <section className="section white"><div className="shell"><div className="section-head"><div><div className="eyebrow">What the Help Desk does</div><h2>One case. One record. One clear demand.</h2></div><p>Students should not have to repeat the same story to disconnected offices. EFF creates a documented advocacy trail while keeping the student copied on every request.</p></div><div className="howard-process">
      <article><MailCheck/><span>01</span><h3>Verify</h3><p>Submit only essential facts, consent to advocacy, and verify your email within 24 hours.</p></article>
      <article><FileText/><span>02</span><h3>Advocate</h3><p>EFF automatically sends one individualized request for complete reinstatement to Howard and copies you.</p></article>
      <article><ClipboardCheck/><span>03</span><h3>Track</h3><p>EFF assigns a case number and maintains the documented status, deadline, and response.</p></article>
      <article><Users/><span>04</span><h3>Escalate together</h3><p>Anonymous patterns support a consolidated request for a uniform reinstatement process.</p></article>
    </div></div></section>
    <section className="section howard-action-center"><div className="shell"><div className="section-head"><div><div className="eyebrow">Do these steps now</div><h2>Protect your place while EFF advocates.</h2></div><p>These links go to official Howard University pages. Save screenshots and confirmation numbers, but do not send private records to EFF by ordinary email.</p></div><div className="howard-action-grid">
      <a href="https://bisonhub.howard.edu/bisonhub-information-students" target="_blank" rel="noreferrer"><strong>Check BisonHub</strong><span>Review holds, tasks, aid status, enrollment, and the exact balance shown today.</span><ExternalLink/></a>
      <a href="https://financialservices.howard.edu/contact" target="_blank" rel="noreferrer"><strong>Join Student Financial Services</strong><span>Use Howard’s live chat, virtual queue, appointment, and account-support routes.</span><ExternalLink/></a>
      <a href="https://howard.edu/registrar/registration" target="_blank" rel="noreferrer"><strong>Registration and holds</strong><span>Review Howard’s registration guidance and contact the appropriate academic advisor.</span><ExternalLink/></a>
      <a href="https://studentaffairs.howard.edu/services/office-student-advocacy-and-support" target="_blank" rel="noreferrer"><strong>Howard student advocacy</strong><span>Request Howard’s case-management support for urgent or extenuating circumstances.</span><ExternalLink/></a>
      <a href="https://studentaffairs.howard.edu/about/departments/office-residence-life-university-housing" target="_blank" rel="noreferrer"><strong>Protect housing</strong><span>Contact Residence Life immediately if a room assignment is canceled or at risk.</span><ExternalLink/></a>
      <a href="https://howard.edu/registrar/FERPA" target="_blank" rel="noreferrer"><strong>Manage FERPA permission</strong><span>Howard may require third-party permission in BisonHub before discussing protected records with an advocate.</span><ExternalLink/></a>
    </div><div className="howard-evidence-note"><ClipboardCheck/><div><strong>Build a clean evidence packet for your own records.</strong><p>Save dated PDFs or redacted screenshots of your balance history, aid status, scholarship or waiver confirmation, payment-plan status, cancellation notice, class schedule, housing assignment, and every case number. Share records only through a secure method Howard or EFF specifically provides.</p></div></div></div></section>
    <section className="section howard-demand"><div className="shell"><div className="eyebrow">EFF’s requested relief</div><h2>What we are asking Howard to do</h2><div className="howard-demand-grid">
      <div><CheckCircle2/><strong>Immediately reinstate affected Fall 2026 students pending individual review.</strong></div>
      <div><CheckCircle2/><strong>Restore original course schedules and housing, or preserve equivalent placements.</strong></div>
      <div><CheckCircle2/><strong>Protect accepted and pending aid, scholarships, waivers, and discounts.</strong></div>
      <div><CheckCircle2/><strong>Reconcile every balance and explain every charge, credit, reversal, and deadline in writing.</strong></div>
      <div><CheckCircle2/><strong>Provide one case liaison and a transparent, uniform reinstatement process.</strong></div>
      <div><CheckCircle2/><strong>Pause reassignment of seats, classes, and housing while cases are reviewed.</strong></div>
    </div></div></section>
    <section className="section white" id="case-intake"><div className="shell howard-form-layout"><div><div className="eyebrow">Howard Help Desk intake</div><h2>Request EFF advocacy</h2><p className="lead">This form is for an affected student. Parents and supporters may help gather facts, but the student must enter their own email, give consent, and verify the request.</p>
      <div className="privacy-banner"><ShieldCheck/><div><strong>Do not upload or type sensitive records.</strong><span>No Social Security numbers, passwords, verification codes, tax returns, FAFSA summaries, bank details, loan documents, medical records, or unredacted student IDs.</span></div></div>
      {query.case==="pending"&&<div className="notice"><MailCheck/>Case {query.code&&<strong>{query.code}</strong>} was saved. Check your email and verify within 24 hours before EFF contacts Howard.</div>}
      {query.case==="verified"&&<div className="notice success-text"><CheckCircle2/>Your case {query.code&&<strong>{query.code}</strong>} is verified, and the EFF reinstatement request was sent to Howard with you copied.</div>}
      {query.error&&<div className="notice error-text"><AlertTriangle/>{query.error}{query.code&&<> Case: <strong>{query.code}</strong></>}</div>}
    </div><form action={submitHowardCase} className="application-form howard-case-form">
      <label className="howard-honeypot" aria-hidden="true">Company website<input name="companyWebsite" tabIndex={-1} autoComplete="off"/></label>
      <div className="form-grid"><label>Student’s full name<input name="studentName" required maxLength={120}/></label><label>Preferred name <span className="optional">optional</span><input name="preferredName" maxLength={80}/></label><label>Student’s email<input type="email" name="email" required maxLength={180}/></label><label>Phone <span className="optional">optional</span><input type="tel" name="phone" maxLength={40}/></label><label>Student type<select name="studentType" required defaultValue=""><option value="" disabled>Select one</option>{["Incoming first-year","Incoming transfer","Continuing undergraduate","Graduate or professional student","Other"].map(item=><option key={item}>{item}</option>)}</select></label><label>Current status<select name="enrollmentStatus" required defaultValue=""><option value="" disabled>Select one</option>{statusOptions.map(item=><option key={item}>{item}</option>)}</select></label><label className="full-field">Main problem<select name="issueType" required defaultValue=""><option value="" disabled>Select one</option>{issueOptions.map(item=><option key={item}>{item}</option>)}</select></label><label>Balance previously shown <span className="optional">optional</span><input name="balanceBefore" inputMode="decimal" placeholder="0.00"/></label><label>Balance currently shown <span className="optional">optional</span><input name="balanceNow" inputMode="decimal" placeholder="1571.00"/></label><label className="full-field">Deadline Howard communicated <span className="optional">optional</span><input name="schoolDeadline" maxLength={120} placeholder="Include the date and what happens at the deadline"/></label></div>
      <label>Pending aid, scholarship, waiver, discount, or payment-plan information<textarea name="aidSummary" required minLength={30} maxLength={1800} placeholder="Name the type and its current status. Do not include account or document numbers."/></label>
      <label>Factual timeline<textarea name="timeline" required minLength={80} maxLength={4000} placeholder="List dates, what the portal showed, notices received, and what changed. Do not include private identifiers."/></label>
      <label>Steps already taken<textarea name="stepsTaken" required minLength={30} maxLength={2500} placeholder="List offices contacted, forms submitted, dates, and any case numbers without including passwords or private account information."/></label>
      <div className="howard-consents"><label className="check"><input type="checkbox" name="authorizeEffContact" required/><span>I authorize Esther Funds Foundation to send these facts and a request for complete reinstatement to Howard University, copying me and EFF.</span></label><label className="check"><input type="checkbox" name="anonymousAdvocacyConsent"/><span>EFF may include my situation without my name, email, phone, student ID, or documents in consolidated advocacy and public impact totals.</span></label><label className="check"><input type="checkbox" name="privacyConsent" required/><span>I understand this is educational advocacy, not legal representation, and Howard may require its own FERPA or identity-verification process.</span></label><label className="check"><input type="checkbox" name="accuracyCertified" required/><span>I certify that the information is accurate and belongs to me.</span></label></div>
      <button className="button" type="submit">Save case and email verification</button>
    </form></div></section>
    <section className="section howard-petition-section" id="petition"><div className="shell howard-petition-grid"><div><div className="eyebrow">Official EFF petition</div><h2>Stand for complete reinstatement.</h2><div className="petition-paper"><GraduationCap/><p>We respectfully call upon Howard University to immediately reinstate affected Fall 2026 students; restore or preserve their admission, classes, housing, and financial aid; complete individualized account reconciliations; honor documented pending scholarships, loans, waivers, discounts, and payment arrangements; and publish one transparent process with a meaningful opportunity for review before student spaces are reassigned.</p><p>Students who acted in good faith to secure aid and complete enrollment steps deserve a fair, timely, written review. Their education should not end while administrative and financial records remain unresolved.</p><strong>Every Future Fulfilled means helping students finish what they started.</strong></div></div><div>
      {query.petition==="pending"&&<div className="notice"><MailCheck/>Check your email to verify your signature within 24 hours.</div>}
      {query.petition==="verified"&&<div className="notice success-text"><CheckCircle2/>Your petition signature is verified. Thank you for standing with students.</div>}
      {query.petitionError&&<div className="notice error-text"><AlertTriangle/>{query.petitionError}</div>}
      <form action={signHowardPetition} className="petition-form"><label className="howard-honeypot" aria-hidden="true">Organization website<input name="organizationWebsite" tabIndex={-1} autoComplete="off"/></label><label>Full name<input name="fullName" required maxLength={120}/></label><label>Email<input name="email" type="email" required maxLength={180}/><small>Your email is used for verification and is not displayed publicly.</small></label><label>Your connection<select name="affiliation" required defaultValue=""><option value="" disabled>Select one</option>{["Affected Howard student","Howard student","Parent or family member","Howard alum","Educator or advocate","Community supporter"].map(item=><option key={item}>{item}</option>)}</select></label><label>City and state <span className="optional">optional</span><input name="cityState" maxLength={120}/></label><label className="check"><input type="checkbox" name="displayAnonymously"/><span>Display my support anonymously in any future public signature list.</span></label><label className="check"><input type="checkbox" name="petitionConsent" required/><span>I support the petition statement and consent to email verification.</span></label><button className="button" type="submit">Sign and verify</button></form>
    </div></div></section>
    <section className="section white"><div className="shell howard-safety"><Scale/><div><div className="eyebrow">Important boundary</div><h2>EFF advocates; Howard decides enrollment.</h2><p>EFF cannot directly change a Howard record, guarantee reinstatement, decide eligibility, or provide legal representation through this Help Desk. EFF can organize evidence, send the student’s authorized request, document patterns, maintain follow-up, and escalate responsibly.</p></div><a className="button outline" href="mailto:nationals@estherfundsinc.org?subject=Howard%20Help%20Desk">Contact EFF</a></div></section>
  </main>;
}
