import type {Metadata} from "next";
import Link from "next/link";
import {AlertTriangle,BookOpen,CheckCircle2,ClipboardCheck,ExternalLink,FileCheck2,HeartHandshake,Landmark,MailCheck,MapPinned,Search,ShieldCheck,Users} from "lucide-react";
import {createAdminClient} from "@/lib/supabase/admin";
import {submitStudentHelpCase} from "./actions";
import {StudentHelpSubmitButton} from "./submit-button";

export const metadata:Metadata={title:"National Student Help Desk | Esther Funds Foundation",description:"Open a private case, find the right college office, prepare documents, receive follow-ups, and request limited student essentials support."};
type Query={case?:string;code?:string;error?:string};
const states=["AL","AK","AZ","AR","CA","CO","CT","DE","DC","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"];
const issues=["Financial aid or FAFSA","Past-due balance or registration hold","Admissions or enrollment","Housing or food insecurity","Academic records or transfer","Disability or accessibility support","International or veteran services","Technology access","Discrimination, safety, or student rights","Other"];
const documents=["School notice or email","Current bill or balance screenshot","Financial-aid offer","FAFSA Submission Summary","Scholarship or waiver notice","Class schedule","Housing notice","Prior office case numbers","Appeal or special-circumstance form","Other supporting record"];
const routes=[
  ["Financial aid, FAFSA, verification","Financial Aid Office","FAFSA Submission Summary, aid offer, verification notice, change-in-income evidence"],
  ["Balance, payment, refund, hold","Bursar or Student Accounts","Itemized bill, payment receipt, scholarship notice, prior case number"],
  ["Classes, registration, transcript","Registrar and academic adviser","Schedule, hold notice, degree audit, written deadline"],
  ["Housing, food, emergency need","Dean of Students or Basic Needs Center","Housing notice, short budget, deadline, emergency-aid form"],
  ["Disability accommodations","Accessibility or Disability Services","Accommodation request and the office’s secure documentation instructions"],
  ["Discrimination, Title IX, safety","Title IX, Equal Opportunity, or Campus Safety","Factual timeline, preserved messages, witnesses, requested safety measure"]
];

export default async function StudentHelp({searchParams}:{searchParams:Promise<Query>}){
  const query=await searchParams;let openCases=0;let queuePosition:number|null=null;let essentialsOpen=0;
  try{
    const admin=createAdminClient();const openStatuses=["new","reviewing","waiting_on_student","referred_to_school","follow_up_due"];
    const [{count},{count:essentials}]=await Promise.all([
      admin.from("student_help_cases").select("id",{count:"exact",head:true}).in("status",openStatuses),
      admin.from("student_help_cases").select("id",{count:"exact",head:true}).in("status",openStatuses).eq("essentials_requested",true)
    ]);openCases=count??0;essentialsOpen=essentials??0;
    if(query.code){
      const {data:current}=await admin.from("student_help_cases").select("created_at,status,verified_at").eq("case_code",query.code.toUpperCase()).maybeSingle();
      if(current?.verified_at&&openStatuses.includes(current.status)){
        const {count:ahead}=await admin.from("student_help_cases").select("id",{count:"exact",head:true}).in("status",openStatuses).lte("created_at",current.created_at);
        queuePosition=ahead??null;
      }
    }
  }catch{}
  return <main className="howard-help-page">
    <section className="howard-hero"><div className="shell howard-hero-grid"><div><Link className="back-link" href="/resources">← Student Help Center</Link><div className="eyebrow">For students at every U.S. college</div><h1>One case.<br/><span>A clearer next step.</span></h1><p>Find the right school office, organize the documents you already have, receive accountable follow-up, and ask EFF for help when a college process threatens your education.</p><div className="hero-actions"><a className="button light" href="#open-case">Open a private case</a><a className="button lavender" href="#office-map">Find the right office</a></div></div><aside className="howard-hero-card"><HeartHandshake/><strong>HBCU, PWI, community college, or university.</strong><p>EFF serves students enrolled at U.S. colleges without requiring their institution to participate.</p><small>Free to open a case. Schools control their own decisions. Financial assistance is limited and never guaranteed.</small></aside></div></section>
    <section className="howard-status"><div className="shell"><div><strong>{openCases}</strong><span>verified open case{openCases===1?"":"s"}</span></div><div><strong>{essentialsOpen}</strong><span>essentials request{essentialsOpen===1?"":"s"} in review</span></div><p>{queuePosition?<><b>Case {query.code}</b> is currently <b>#{queuePosition}</b> in the open-case line.</>:"Enter through your case link to see your private place in line."}</p></div></section>
    <section className="section white"><div className="shell"><div className="section-head"><div><div className="eyebrow">National service model</div><h2>Support built around the problem—not the campus label.</h2></div><p>EFF uses official federal and institutional sources, records when a resource was checked, and routes students by issue. HBCU status is recognized, but it does not determine whether a student can receive help.</p></div><div className="howard-process">
      <article><MailCheck/><span>01</span><h3>Open and verify</h3><p>Receive an EFF case number and verify your email before review begins.</p></article>
      <article><Search/><span>02</span><h3>Route correctly</h3><p>Identify the office that owns the decision and the best official contact path.</p></article>
      <article><FileCheck2/><span>03</span><h3>Prepare documents</h3><p>Build a redacted checklist; secure records are requested only when truly needed.</p></article>
      <article><ClipboardCheck/><span>04</span><h3>Follow through</h3><p>Receive follow-up emails, preserve case numbers, and track the next promised date.</p></article>
    </div></div></section>
    <section className="section howard-action-center" id="office-map"><div className="shell"><div className="eyebrow">College department map</div><h2>Start with the office that owns the next decision.</h2><div className="table-wrap"><table><thead><tr><th>If the issue involves</th><th>Start here</th><th>Prepare</th></tr></thead><tbody>{routes.map(route=><tr key={route[0]}><td><strong>{route[0]}</strong></td><td>{route[1]}</td><td>{route[2]}</td></tr>)}</tbody></table></div><div className="resource-actions"><a className="button outline" href="https://nces.ed.gov/collegenavigator/" target="_blank" rel="noreferrer"><Landmark/> Find any U.S. college <ExternalLink size={15}/></a><a className="button outline" href="https://studentaid.gov/help-center/contact" target="_blank" rel="noreferrer"><BookOpen/> Federal Student Aid help <ExternalLink size={15}/></a><a className="button outline" href="https://www.211.org/" target="_blank" rel="noreferrer"><MapPinned/> Local food and housing help <ExternalLink size={15}/></a></div></div></section>
    <section className="section howard-demand"><div className="shell"><div className="eyebrow">Fall/Spring Student Essentials Fund</div><h2>Up to $100 for groceries or school supplies.</h2><div className="howard-demand-grid"><div><CheckCircle2/><strong>Open to students at U.S. colleges, including HBCUs and PWIs.</strong></div><div><CheckCircle2/><strong>Select Fall or Spring and request no more than $100.</strong></div><div><CheckCircle2/><strong>EFF reviews enrollment, need, available funding, and duplicate requests.</strong></div><div><CheckCircle2/><strong>EFF chooses and confirms the payment method after approval.</strong></div></div><p>Submitting a request does not guarantee approval or payment. Never place bank-account or card information in this form.</p></div></section>
    <section className="section white" id="open-case"><div className="shell howard-form-layout"><div><div className="eyebrow">National Help Desk intake</div><h2>Tell us what is blocking your education.</h2><p className="lead">Your case number stays with your request. EFF will email you after verification and at meaningful follow-up points.</p>
      <div className="privacy-banner"><ShieldCheck/><div><strong>List documents; do not upload secrets here.</strong><span>Never enter Social Security numbers, passwords, tax data, bank details, medical records, or unredacted student IDs. EFF will provide a secure process if a record is needed.</span></div></div>
      {query.case==="pending"&&<div className="notice"><MailCheck/>Case {query.code&&<strong>{query.code}</strong>} was saved. Verify your email within 24 hours to enter the live line.</div>}
      {query.case==="verified"&&<div className="notice success-text"><CheckCircle2/>Case {query.code&&<strong>{query.code}</strong>} is verified and in line. Your current position is {queuePosition?<strong>#{queuePosition}</strong>:"being calculated"}.</div>}
      {query.error&&<div className="notice error-text"><AlertTriangle/>{query.error}{query.code&&<> Case: <strong>{query.code}</strong></>}</div>}
    </div><form action={submitStudentHelpCase} className="application-form howard-case-form">
      <label className="howard-honeypot" aria-hidden="true">Company website<input name="companyWebsite" tabIndex={-1} autoComplete="off"/></label>
      <div className="form-grid"><label>Full name<input name="studentName" required maxLength={120}/></label><label>Preferred name <span className="optional">optional</span><input name="preferredName" maxLength={80}/></label><label>Email<input type="email" name="email" required/></label><label>Phone <span className="optional">optional</span><input type="tel" name="phone"/></label><label className="full-field">College or university<input name="schoolName" required placeholder="Type the school’s full name"/></label><label>School state<select name="schoolState" required defaultValue=""><option value="" disabled>Select</option>{states.map(s=><option key={s}>{s}</option>)}</select></label><label>Institution type<select name="schoolType" required defaultValue="Unsure"><option>HBCU</option><option>PWI or other institution</option><option>Unsure</option></select></label><label>Student level<select name="studentLevel" required defaultValue=""><option value="" disabled>Select</option>{["Incoming student","Undergraduate","Graduate or professional","Community college or certificate","Other"].map(x=><option key={x}>{x}</option>)}</select></label><label>Urgency<select name="urgency" required defaultValue=""><option value="" disabled>Select</option>{["Immediate — within 72 hours","This week","Within 30 days","No fixed deadline"].map(x=><option key={x}>{x}</option>)}</select></label><label className="full-field">Main issue<select name="issueType" required defaultValue=""><option value="" disabled>Select</option>{issues.map(x=><option key={x}>{x}</option>)}</select></label><label>School deadline <span className="optional">optional</span><input type="date" name="schoolDeadline"/></label><label>Amount at risk <span className="optional">optional</span><input name="amountAtRisk" inputMode="decimal" placeholder="0.00"/></label><label className="full-field">Office already contacted <span className="optional">optional</span><input name="departmentSought" placeholder="Financial Aid, Registrar, Dean of Students…"/></label></div>
      <label>What happened and what outcome do you need?<textarea name="situationSummary" required minLength={80} maxLength={4000}/></label><label>Steps already taken<textarea name="stepsTaken" required minLength={20} maxLength={2500}/></label>
      <fieldset><legend>Documents you already have</legend><div className="howard-consents">{documents.map(x=><label className="check" key={x}><input type="checkbox" name="documentsAvailable" value={x}/><span>{x}</span></label>)}</div></fieldset>
      <fieldset className="card"><legend><strong>Optional Fall/Spring Student Essentials request</strong></legend><label className="check"><input type="checkbox" name="essentialsRequested"/><span>I want EFF to review a groceries or school-supplies request.</span></label><div className="form-grid"><label>Term<select name="essentialsTerm" defaultValue=""><option value="">Select if requesting</option><option>Fall</option><option>Spring</option></select></label><label>Need<select name="essentialsCategory" defaultValue=""><option value="">Select if requesting</option><option>Groceries</option><option>School supplies</option><option>Groceries and school supplies</option></select></label><label>Amount requested<input name="essentialsAmount" inputMode="decimal" placeholder="Maximum 100.00"/></label><label>Preferred payment method <span className="optional">no account numbers</span><input name="preferredPaymentMethod" placeholder="Digital payment, store e-gift card, check…"/></label></div><label>Explain the immediate need<textarea name="essentialsExplanation" maxLength={1800} placeholder="Required only when requesting essentials. Explain how this will help you remain enrolled."/></label></fieldset>
      <div className="howard-consents"><label className="check"><input type="checkbox" name="authorizeEffContact" required/><span>I authorize EFF to contact me and, when appropriate, contact my school using the facts I provided.</span></label><label className="check"><input type="checkbox" name="privacyConsent" required/><span>I understand EFF provides educational support and advocacy, not legal representation, and my school controls its decisions.</span></label><label className="check"><input type="checkbox" name="accuracyCertified" required/><span>I certify that this information is accurate and belongs to me.</span></label></div><StudentHelpSubmitButton/>
    </form></div></section>
    <section className="section white"><div className="shell howard-safety"><Users/><div><div className="eyebrow">Service promise</div><h2>A line you can see. Follow-up you can track.</h2><p>Counts include verified, unresolved cases—not unverified forms or resolved students. Queue position is a transparency indicator; urgent safety and deadline-sensitive cases may be triaged ahead after review.</p></div></div></section>
  </main>;
}
