export const ALL_ANSWER_FIELDS = [
  "residency_status",
  "fafsa_completed",
  "unmet_need_verified",
  "undergraduate_no_bachelors",
  "accredited_us_institution",
  "legal_name",
  "preferred_name",
  "date_of_birth",
  "gender",
  "race_ethnicity",
  "marital_status",
  "personal_email",
  "school_email",
  "phone",
  "address",
  "institution",
  "student_id",
  "class_standing",
  "major",
  "expected_graduation",
  "enrollment_status",
  "gpa",
  "emergency_contact_name",
  "emergency_contact_relationship",
  "emergency_contact_phone",
  "emergency_contact_email",
  "amount_requested",
  "need_category",
  "other_need",
  "financial_need_description",
  "story",
  "faith_reflection",
  "full_time_student",
  "active_eff_member",
  "good_standing",
  "board_role",
  "chapter_name",
  "service_start_date",
  "meeting_attendance",
  "task_completion",
  "service_hours_total",
  "recommender_name",
  "recommender_role",
  "recommender_email",
  "leadership_essay",
  "ambassador_service_start_date",
  "ambassador_work_summary",
  "ambassador_essay",
  "certification",
  "signature",
] as const;

export const ALL_UPLOAD_KINDS = [
  "headshot",
  "enrollment_proof",
  "financial_need_proof",
  "supporting_document",
  "fafsa_summary",
  "service_hours_proof",
  "recommendation_letter",
  "ambassador_work_proof",
] as const;

export const AMBASSADOR_REQUIRED_ANSWERS = [
  "full_time_student",
  "active_eff_member",
  "good_standing",
  "fafsa_completed",
  "legal_name",
  "personal_email",
  "phone",
  "institution",
  "student_id",
  "expected_graduation",
  "ambassador_service_start_date",
  "ambassador_work_summary",
  "service_hours_total",
  "ambassador_essay",
  "certification",
  "signature",
] as const;

export const AMBASSADOR_REQUIRED_UPLOADS = [
  "enrollment_proof",
  "fafsa_summary",
  "service_hours_proof",
  "ambassador_work_proof",
] as const;

export const EXECUTIVE_BOARD_REQUIRED_ANSWERS = [
  "full_time_student",
  "active_eff_member",
  "good_standing",
  "fafsa_completed",
  "legal_name",
  "personal_email",
  "phone",
  "institution",
  "student_id",
  "expected_graduation",
  "board_role",
  "chapter_name",
  "service_start_date",
  "meeting_attendance",
  "task_completion",
  "service_hours_total",
  "recommender_name",
  "recommender_role",
  "recommender_email",
  "leadership_essay",
  "certification",
  "signature",
] as const;

export const EXECUTIVE_BOARD_REQUIRED_UPLOADS = [
  "enrollment_proof",
  "fafsa_summary",
  "service_hours_proof",
  "recommendation_letter",
] as const;
