import {z} from "zod";
export const studentSupportStatuses=["draft","pending","changes_requested","approved","declined","paused","withdrawn"] as const;
export type StudentSupportStatus=typeof studentSupportStatuses[number];
export const statusLabels:Record<StudentSupportStatus,string>={draft:"Draft",pending:"Awaiting EFF review",changes_requested:"Changes requested",approved:"Published",declined:"Not published",paused:"Paused",withdrawn:"Withdrawn"};
const blockedHosts=new Set(["localhost","127.0.0.1","0.0.0.0","::1"]);
export function normalizeSupportUrl(value:string):{url:string;platform:string}|null{const input=value.trim();if(!input||input.length>1000)return null;try{const url=new URL(input);const host=url.hostname.toLowerCase().replace(/^www\./,"");if(url.protocol!=="https:"||url.username||url.password||blockedHosts.has(host)||host.endsWith(".local"))return null;if(!host.includes(".")||/^(10|127)\./.test(host)||/^192\.168\./.test(host)||/^172\.(1[6-9]|2\d|3[01])\./.test(host))return null;url.hash="";const platform=host==="gofund.me"||host.endsWith("gofundme.com")?"GoFundMe":host.endsWith("givebutter.com")?"Givebutter":host.endsWith("spotfund.com")?"Spotfund":host.endsWith("fundly.com")?"Fundly":"Verified external support page";return{url:url.toString(),platform};}catch{return null;}}
export function studentProfileSlug(displayName:string,id:string){const name=displayName.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,48)||"student";return`${name}-${id.replaceAll("-","").slice(0,8)}`;}
export function studentInitials(name:string){return name.trim().split(/\s+/).slice(0,2).map(part=>part[0]?.toUpperCase()??"").join("")||"ST";}
export function formatSupportAmount(value:number|string|null|undefined){const amount=Number(value??0);return Number.isFinite(amount)&&amount>0?amount.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}):"Amount verified privately";}
export const submittedStudentSupportSchema=z.object({displayName:z.string().trim().min(2).max(80),headline:z.string().trim().min(10).max(140),institution:z.string().trim().min(2).max(160),locationText:z.string().trim().max(100),major:z.string().trim().max(120),classYear:z.string().trim().max(50),story:z.string().trim().min(150).max(2500),needSummary:z.string().trim().min(40).max(500),amountNeeded:z.coerce.number().positive().max(100000),fundraiserUrl:z.string().trim().min(1).max(1000),consentConfirmed:z.literal(true),accuracyConfirmed:z.literal(true),ageConfirmed:z.literal(true),safetyConfirmed:z.literal(true)});
