import type {Metadata} from "next";
import Link from "next/link";
import {signIn} from "@/app/auth/actions";

export const metadata: Metadata = {title: "Sign In to the EFF Scholarship Portal"};

export default async function SignIn({searchParams}:{searchParams:Promise<{error?:string;message?:string;next?:string}>}) {
  const p=await searchParams;
  return <main className="section"><div className="shell" style={{maxWidth:560}}><div className="card"><div className="eyebrow">Scholarship applicant access</div><h1>Sign In to the EFF Scholarship Portal</h1><p className="muted">Apply for or track an EFF scholarship or support application.</p><div className="notice"><strong>Need help with a college barrier, EFF resource, or support request?</strong><br/><Link className="card-link" href="/help-desk">Open the National Student Help Desk</Link></div><div className="notice"><strong>Not sure whether to sign in, create an account, or claim an old scholarship application?</strong><br/><Link className="card-link" href="/account-help">Use Scholarship Portal account help</Link></div>{p.error&&<p className="notice" role="alert">{p.error}</p>}{p.message&&<p className="notice" role="status">{p.message}</p>}<form action={signIn} style={{display:"grid",gap:16,marginTop:24}}><input type="hidden" name="next" value={p.next??"/dashboard"}/><label>Email address<input name="email" type="email" autoComplete="email" required style={{display:"block",width:"100%",padding:12,marginTop:6}}/></label><label>Password<input name="password" type="password" autoComplete="current-password" required style={{display:"block",width:"100%",padding:12,marginTop:6}}/></label><button className="button">Sign In to Scholarship Portal</button></form><p><Link className="card-link" href="/forgot-password">Forgot your Scholarship Portal password?</Link></p><p className="muted">New scholarship applicant? <Link className="card-link" href="/sign-up">Create a Scholarship Portal account</Link></p></div></div></main>;
}