import Link from "next/link";
import {Clock3, Download, Headphones, ShieldCheck} from "lucide-react";
import {requireHelpDeskVolunteer} from "@/lib/help-desk/auth";
import {HelpDeskChatPanel} from "../../chat-panel";
import {claimHelpDeskConversation, closeHelpDeskConversation, endHelpDeskShift, releaseHelpDeskConversation, startHelpDeskShift} from "../actions";
import {escalateHelpDeskConversation} from "../escalation-actions";

export const dynamic = "force-dynamic";

export default async function VolunteerDesk({searchParams}:{searchParams:Promise<{welcome?:string}>}) {
  const query = await searchParams;
  const {user,profile,admin} = await requireHelpDeskVolunteer();
  const now = new Date().toISOString();
  const [{data:shift},{data:assigned},{data:queue},{data:logs}] = await Promise.all([
    admin.from("help_desk_shifts").select("*").eq("volunteer_id",user.id).eq("status","active").gt("ends_at",now).order("started_at",{ascending:false}).limit(1).maybeSingle(),
    admin.from("help_desk_conversations").select("id,status,risk_level,created_at,last_message_at,student_help_cases(case_code,preferred_name,student_name,school_name,issue_type,urgency,school_deadline,situation_summary,steps_taken)").eq("assigned_volunteer_id",user.id).in("status",["assigned","active","waiting_student","escalated"]).order("updated_at",{ascending:false}).limit(1).maybeSingle(),
    admin.from("help_desk_conversations").select("id,status,risk_level,created_at,last_message_at,student_help_cases(case_code,school_name,issue_type,urgency,school_deadline)").eq("status","unassigned").is("assigned_volunteer_id",null).order("risk_level",{ascending:false}).order("created_at",{ascending:true}).limit(25),
    admin.from("help_desk_service_logs").select("minutes_credited").eq("volunteer_id",user.id).not("ended_at","is",null),
  ]);
  const totalMinutes=(logs??[]).reduce((sum,row)=>sum+(row.minutes_credited??0),0);
  const assignedCase = Array.isArray(assigned?.student_help_cases)?assigned.student_help_cases[0]:assigned?.student_help_cases;
  return <main className="section help-desk-desk-page"><div className="shell">
    <div className="help-desk-desk-header"><div><div className="eyebrow">EFF National Help Desk volunteer console</div><h1>Welcome, {profile.display_name}.</h1><p>Read the whole case, respond as a human, and escalate what belongs with leadership.</p></div><div className="hero-actions"><a className="button outline" href="/help-desk/volunteer/certificate"><Download size={17}/> Certificate</a><Link className="button outline" href="/help-desk/volunteer/training">Review training</Link></div></div>
    {query.welcome&&<div className="notice success-text"><ShieldCheck/>Training complete. Your secure console is unlocked.</div>}
    <div className="stats admin-stats"><div className="stat"><strong>{Math.floor(totalMinutes/60)}h {totalMinutes%60}m</strong><span>recorded service</span></div><div className="stat"><strong>{queue?.length??0}</strong><span>waiting cases</span></div><div className="stat"><strong>{shift?Math.max(0,Math.ceil((new Date(shift.ends_at).getTime()-Date.now())/60_000)):0}</strong><span>minutes available</span></div></div>
    <section className="card help-desk-shift-card"><Clock3/><div><h2>Your availability</h2><p>Choose a short period only when you can actively reply. Ending a shift does not erase a claimed case; release it with a handoff if you must leave.</p></div>{shift?<form action={endHelpDeskShift}><button className="button outline">End availability</button></form>:<div className="help-desk-shift-buttons">{[10,15,30,60].map(minutes=><form action={startHelpDeskShift} key={minutes}><input type="hidden" name="minutes" value={minutes}/><button className="button outline">{minutes} minutes</button></form>)}</div>}</section>
    {assigned&&assignedCase?<section className="help-desk-assigned"><div className="section-head"><div><div className="eyebrow">Your active case</div><h2>{assignedCase.preferred_name||assignedCase.student_name} Â· {assignedCase.school_name}</h2><p>{assignedCase.case_code} Â· {assignedCase.issue_type} Â· {assignedCase.urgency}</p></div><Headphones/></div>
      <div className="notice"><strong>Read before replying.</strong><br/>{assignedCase.situation_summary}<br/><br/><strong>Steps already taken:</strong><br/>{assignedCase.steps_taken}</div>
      <HelpDeskChatPanel endpoint={`/api/help-desk/volunteer/conversations/${assigned.id}/messages`} role="volunteer" initialStatus={assigned.status}/>
      <form action={escalateHelpDeskConversation} className="card stack help-desk-escalation-form"><h3>Escalate to the EFF National Office</h3><p className="muted">Use for safety, conduct, privacy, legal or policy questions, funding decisions, media, or help you are not authorized to provide.</p><input type="hidden" name="conversationId" value={assigned.id}/><label>Escalation type<select name="escalationType" required defaultValue=""><option value="" disabled>Select</option><option value="safety">Immediate safety or self-harm</option><option value="conduct">Threatening or inappropriate conduct</option><option value="privacy">Sensitive information exposed</option><option value="legal_or_policy">Legal or policy decision</option><option value="funding_decision">Funding or exception decision</option><option value="media">Media or public statement</option><option value="volunteer_support">Volunteer needs supervisor help</option><option value="other">Other leadership review</option></select></label><label>Factual summary<textarea name="summary" required minLength={10} maxLength={1500}/></label><button className="button danger-button">Lock or escalate and alert leadership</button></form>
      <div className="help-desk-closeout-grid"><form action={releaseHelpDeskConversation} className="card stack"><h3>Hand off to another volunteer</h3><input type="hidden" name="conversationId" value={assigned.id}/><label>Factual handoff summary<textarea name="summary" required minLength={10} maxLength={1000}/></label><button className="button outline">Record service and release</button></form><form action={closeHelpDeskConversation} className="card stack"><h3>Close resolved conversation</h3><input type="hidden" name="conversationId" value={assigned.id}/><label>Resolution and next-step summary<textarea name="summary" required minLength={10} maxLength={1000}/></label><button className="button">Record service and close</button></form></div>
    </section>:<section className="help-desk-queue"><div className="section-head"><div><div className="eyebrow">Waiting queue</div><h2>Claim one case you can actively serve.</h2></div></div>{!shift&&<div className="notice">Start an availability period before claiming a case.</div>}<div className="cards">{(queue??[]).map(item=>{const c=Array.isArray(item.student_help_cases)?item.student_help_cases[0]:item.student_help_cases;return <article className="card" key={item.id}><span className={`status ${item.risk_level}`}>{item.risk_level}</span><h3>{c?.issue_type}</h3><p>{c?.school_name}</p><small>{c?.urgency} Â· Deadline {c?.school_deadline||"not provided"}</small><form action={claimHelpDeskConversation}><input type="hidden" name="conversationId" value={item.id}/><button className="button" disabled={!shift}>Claim secure case</button></form></article>})}{!queue?.length&&<div className="card"><h3>No student is waiting right now.</h3><p className="muted">Thank you for being available. You may end your shift or check again soon.</p></div>}</div></section>}
  </div></main>;
}
