"use server";

import {createHash,randomUUID} from "node:crypto";
import {headers} from "next/headers";
import {redirect} from "next/navigation";
import {z} from "zod";
import {careerRoleMap,volunteerRoleSlugs} from "@/lib/careers";
import {createAdminClient} from "@/lib/supabase/admin";
import {createClient} from "@/lib/supabase/server";
import {emailFrom,getResend} from "@/lib/email";

const baseSchema=z.object({
  roleSlug:z.string().min(1),fullName:z.string().trim().min(2).max(120),preferredName:z.string().trim().max(80).optional(),email:z.string().trim().email().max(180),phone:z.string().trim().min(7).max(40),location:z.string().trim().min(2).max(160),applicantType:z.string().trim().min(2).max(80),institution:z.string().trim().min(2).max(180),degree:z.string().trim().min(2).max(180),graduationYear:z.string().trim().regex(/^$|^\d{4}$/),linkedinUrl:z.string().trim().url().max(500).or(z.literal("")),whyEff:z.string().trim().min(100).max(3000),relevantExperience:z.string().trim().min(150).max(5000),teamCulture:z.string().trim().min(100).max(3000),weeklyAvailability:z.string().trim().min(2).max(80),startDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),workUrl:z.string().trim().url().max(500).or(z.literal("")),signature:z.string().trim().min(2).max(120),truthful:z.literal("on"),privacyConsent:z.literal("on"),writtenTerms:z.literal("on")
});

const text=(form:FormData,key:string)=>String(form.get(key)??"").trim();
const safeName=(name:string)=>name.replace(/[^a-zA-Z0-9._-]/g,"-").replace(/-+/g,"-").slice(-120)||"resume";
const publicPortalUrl="https://portal.estherfundsfoundation.org";

export async function submitCareerApplication(formData:FormData){
  const slug=text(formData,"roleSlug");const role=careerRoleMap.get(slug);if(!role)redirect("/careers?error=Role+not+found");const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user?.email)redirect(`/sign-in?next=/careers/apply/${encodeURIComponent(slug)}`);
  if(text(formData,"companyWebsite"))redirect(`/careers/apply/success?role=${encodeURIComponent(slug)}`);
  const raw={roleSlug:slug,fullName:text(formData,"fullName"),preferredName:text(formData,"preferredName"),email:user.email.toLowerCase(),phone:text(formData,"phone"),location:text(formData,"location"),applicantType:text(formData,"applicantType"),institution:text(formData,"institution"),degree:text(formData,"degree"),graduationYear:text(formData,"graduationYear"),linkedinUrl:text(formData,"linkedinUrl"),whyEff:text(formData,"whyEff"),relevantExperience:text(formData,"relevantExperience"),teamCulture:text(formData,"teamCulture"),weeklyAvailability:text(formData,"weeklyAvailability"),startDate:text(formData,"startDate"),workUrl:text(formData,"workUrl"),signature:text(formData,"signature"),truthful:text(formData,"truthful"),privacyConsent:text(formData,"privacyConsent"),writtenTerms:text(formData,"writtenTerms")};
  const parsed=baseSchema.safeParse(raw);if(!parsed.success)redirect(`/careers/apply/${slug}?error=${encodeURIComponent("Please review every required field and try again.")}`);
  if(volunteerRoleSlugs.has(slug)&&text(formData,"volunteerAcknowledgment")!=="on")redirect(`/careers/apply/${slug}?error=${encodeURIComponent("Please confirm the volunteer terms before submitting.")}`);
  const answers:Record<string,string>={};for(const question of role.questions){const value=text(formData,question.name);if(question.required&&!value)redirect(`/careers/apply/${slug}?error=${encodeURIComponent("Please answer every required role-specific question.")}`);answers[question.name]=value;}
  const requestHeaders=await headers();const ip=requestHeaders.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";const ipHash=createHash("sha256").update(`${process.env.CRON_SECRET||"eff-careers"}:${ip}`).digest("hex");
  const admin=createAdminClient();const postingTerm=role.postingTerm??"Open opportunity";const {data:active}=await admin.from("career_applications").select("id").eq("applicant_id",user.id).eq("role_slug",slug).eq("posting_term",postingTerm).in("status",["submitted","in_review","interview","selected"]).limit(1).maybeSingle();if(active)redirect(`/careers/applications/${active.id}`);
  const id=randomUUID();let resumePath:string|null=null;let resumeFilename:string|null=null;const resume=formData.get("resume");
  if(resume instanceof File&&resume.size>0){const allowed=new Set(["application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document"]);if(!allowed.has(resume.type)||resume.size>8*1024*1024)redirect(`/careers/apply/${slug}?error=${encodeURIComponent("Your résumé must be a PDF or DOCX file no larger than 8 MB.")}`);resumeFilename=resume.name;resumePath=`${user.id}/${id}/${safeName(resume.name)}`;const uploaded=await admin.storage.from("career-materials").upload(resumePath,resume,{contentType:resume.type,upsert:false});if(uploaded.error)redirect(`/careers/apply/${slug}?error=${encodeURIComponent("Your résumé could not be uploaded. Please try again.")}`);}else if(role.resumeRequired)redirect(`/careers/apply/${slug}?error=${encodeURIComponent("Please attach your résumé before submitting.")}`);
  const graduationYear=parsed.data.graduationYear?Number(parsed.data.graduationYear):null;const now=new Date().toISOString();const baseUpdate=await supabase.from("profiles").update({legal_name:parsed.data.fullName,preferred_name:parsed.data.preferredName||null,phone:parsed.data.phone,updated_at:now}).eq("id",user.id);const careerUpdate=await supabase.from("career_profiles").upsert({user_id:user.id,location:parsed.data.location,applicant_type:parsed.data.applicantType,institution_or_employer:parsed.data.institution,degree_or_field:parsed.data.degree,graduation_year:graduationYear,linkedin_url:parsed.data.linkedinUrl||null,work_url:parsed.data.workUrl||null,updated_at:now},{onConflict:"user_id"});if(baseUpdate.error||careerUpdate.error){if(resumePath)await admin.storage.from("career-materials").remove([resumePath]);redirect(`/careers/apply/${slug}?error=${encodeURIComponent("Your reusable profile could not be saved. Nothing was submitted; please try again.")}`);}
  const payload={id,applicant_id:user.id,posting_term:postingTerm,role_slug:slug,role_title:role.title,category:role.category,full_name:parsed.data.fullName,preferred_name:parsed.data.preferredName||null,email:parsed.data.email,phone:parsed.data.phone,location:parsed.data.location,applicant_type:parsed.data.applicantType,institution:parsed.data.institution,degree:parsed.data.degree,graduation_year:graduationYear,linkedin_url:parsed.data.linkedinUrl||null,work_url:parsed.data.workUrl||null,resume_path:resumePath,resume_filename:resumeFilename,weekly_availability:parsed.data.weeklyAvailability,available_start_date:parsed.data.startDate,why_eff:parsed.data.whyEff,relevant_experience:parsed.data.relevantExperience,team_culture:parsed.data.teamCulture,role_answers:answers,is_volunteer:volunteerRoleSlugs.has(slug),applicant_signature:parsed.data.signature,ip_hash:ipHash,status:"submitted"};
  const inserted=await admin.from("career_applications").insert(payload);if(inserted.error){if(resumePath)await admin.storage.from("career-materials").remove([resumePath]);redirect(`/careers/apply/${slug}?error=${encodeURIComponent("We could not save your application. Nothing was submitted; please try again.")}`);}
  try{const resend=getResend();await Promise.all([resend.emails.send({from:emailFrom,to:parsed.data.email,subject:`We received your EFF application: ${role.title}`,text:`Hi ${parsed.data.preferredName||parsed.data.fullName},\n\nThank you for applying for ${role.title} with Esther Funds Foundation. We received your ${postingTerm} application. The posting lists ${role.compensation}. Submission does not create an employment, contractor, volunteer, or attorney-client relationship. If EFF would like to continue, the National Office will contact you from an official estherfundsinc.org address.\n\nTrack your application securely at ${publicPortalUrl}/careers/dashboard. Never email Social Security numbers, passwords, verification codes, tax returns, or banking details.\n\nEsther Funds Foundation National Office\nEvery Future Fulfilled`}),resend.emails.send({from:emailFrom,to:"nationals@estherfundsinc.org",subject:`New careers application: ${role.title}`,text:`A new ${postingTerm} careers application was received.\n\nApplicant: ${parsed.data.fullName}\nRole: ${role.title}\nEmail: ${parsed.data.email}\n\nReview securely in the staff careers workspace: ${publicPortalUrl}/admin/careers/${id}`})]);}catch(error){console.error("Career application notifications could not be sent",error);}
  redirect(`/careers/apply/success?role=${encodeURIComponent(slug)}&id=${encodeURIComponent(id)}`);
}
