"use server";
import {randomUUID} from "node:crypto";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {normalizeSupportUrl,studentProfileSlug,submittedStudentSupportSchema} from "@/lib/student-support";
import {queueStudentSupportEmail} from "@/lib/student-support-email";
const text=(form:FormData,key:string,max:number)=>String(form.get(key)??"").trim().slice(0,max);
const images=new Set(["image/jpeg","image/png","image/webp"]);const verificationTypes=new Set([...images,"application/pdf"]);
const extension=(file:File)=>file.type==="application/pdf"?"pdf":file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";
const fail=(message:string)=>redirect(`/meet-a-student/apply?error=${encodeURIComponent(message)}`);
export async function saveStudentSupportProfile(formData:FormData){
 const client=await createClient();const{data:{user}}=await client.auth.getUser();if(!user)redirect("/sign-in?next=/meet-a-student/apply");
 const admin=createAdminClient();const{data:profile}=await admin.from("profiles").select("id,primary_email,legal_name,preferred_name").eq("id",user.id).maybeSingle();if(!profile)throw new Error("Complete your EFF portal account before creating a profile.");
 const{data:current}=await admin.from("student_support_profiles").select("*").eq("student_id",user.id).maybeSingle();const intent=text(formData,"intent",20)==="submit"?"submit":"draft";
 const raw={displayName:text(formData,"displayName",80),headline:text(formData,"headline",140),institution:text(formData,"institution",160),locationText:text(formData,"locationText",100),major:text(formData,"major",120),classYear:text(formData,"classYear",50),story:text(formData,"story",2500),needSummary:text(formData,"needSummary",500),amountNeeded:text(formData,"amountNeeded",20).replace(/[$,\s]/g,""),fundraiserUrl:text(formData,"fundraiserUrl",1000),consentConfirmed:formData.get("consentConfirmed")==="on",accuracyConfirmed:formData.get("accuracyConfirmed")==="on",ageConfirmed:formData.get("ageConfirmed")==="on",safetyConfirmed:formData.get("safetyConfirmed")==="on"};
 const parsed=intent==="submit"?submittedStudentSupportSchema.safeParse(raw):null;if(intent==="submit"&&!parsed?.success)fail("Complete every required field and confirmation before submitting for review.");
 const normalized=raw.fundraiserUrl?normalizeSupportUrl(raw.fundraiserUrl):null;if(raw.fundraiserUrl&&!normalized)fail("Enter a safe public HTTPS fundraising or payment-page link.");
 const photo=formData.get("photo"),verification=formData.get("verificationDocument");if(photo instanceof File&&photo.size>0&&(!images.has(photo.type)||photo.size>6*1024*1024))fail("Your optional photo must be JPG, PNG, or WEBP and no larger than 6 MB.");if(verification instanceof File&&verification.size>0&&(!verificationTypes.has(verification.type)||verification.size>8*1024*1024))fail("Verification must be PDF, JPG, PNG, or WEBP and no larger than 8 MB.");if(intent==="submit"&&!(verification instanceof File&&verification.size>0)&&!current?.verification_document_path)fail("Upload redacted school, enrollment, or balance documentation before submitting.");
 const id=current?.id??randomUUID();let privatePhotoPath=current?.private_photo_path??null,verificationPath=current?.verification_document_path??null,verificationName=current?.verification_document_name??null,verificationType=current?.verification_document_type??null;const newPaths:string[]=[];let replacedPhoto=false,replacedVerification=false;
 if(photo instanceof File&&photo.size>0){privatePhotoPath=`${user.id}/${id}/photo-${Date.now()}.${extension(photo)}`;const uploaded=await admin.storage.from("student-support-private").upload(privatePhotoPath,photo,{contentType:photo.type,upsert:false});if(uploaded.error)fail("Your photo could not be uploaded. Please try again.");newPaths.push(privatePhotoPath);replacedPhoto=true;}
 if(verification instanceof File&&verification.size>0){verificationPath=`${user.id}/${id}/verification-${Date.now()}.${extension(verification)}`;const uploaded=await admin.storage.from("student-support-private").upload(verificationPath,verification,{contentType:verification.type,upsert:false});if(uploaded.error){if(newPaths.length)await admin.storage.from("student-support-private").remove(newPaths);fail("Your verification document could not be uploaded. Please try again.");}newPaths.push(verificationPath);verificationName=verification.name.slice(0,180);verificationType=verification.type;replacedVerification=true;}
 const now=new Date().toISOString(),amount=raw.amountNeeded&&Number.isFinite(Number(raw.amountNeeded))?Number(raw.amountNeeded):null;const payload={id,student_id:user.id,slug:current?.slug??studentProfileSlug(raw.displayName||profile.preferred_name||profile.legal_name||"student",id),display_name:raw.displayName,headline:raw.headline||null,institution:raw.institution||null,location_text:raw.locationText||null,major:raw.major||null,class_year:raw.classYear||null,story:raw.story||null,need_summary:raw.needSummary||null,amount_needed:amount,fundraiser_url:normalized?.url??null,fundraiser_platform:normalized?.platform??null,private_photo_path:privatePhotoPath,public_photo_path:null,verification_document_path:verificationPath,verification_document_name:verificationName,verification_document_type:verificationType,status:intent==="submit"?"pending":"draft",consent_confirmed:raw.consentConfirmed,accuracy_confirmed:raw.accuracyConfirmed,age_or_guardian_confirmed:raw.ageConfirmed,sensitive_information_warning_confirmed:raw.safetyConfirmed,review_note:intent==="submit"?null:current?.review_note??null,verification_checklist:{},submitted_at:intent==="submit"?now:current?.submitted_at??null,reviewed_at:null,reviewed_by:null,link_verified_at:null,published_at:null,updated_at:now};
 const{error}=await admin.from("student_support_profiles").upsert(payload,{onConflict:"student_id"});if(error){if(newPaths.length)await admin.storage.from("student-support-private").remove(newPaths);console.error("Meet a Student save failed",error);fail("Your profile could not be saved. Please try again.");}
 const oldToRemove:string[]=[];if(replacedPhoto&&current?.private_photo_path)oldToRemove.push(current.private_photo_path);if(replacedVerification&&current?.verification_document_path)oldToRemove.push(current.verification_document_path);if(oldToRemove.length)await admin.storage.from("student-support-private").remove(oldToRemove);if(current?.public_photo_path)await admin.storage.from("student-support-public").remove([current.public_photo_path]);
 await admin.from("audit_events").insert({actor_id:user.id,action:intent==="submit"?"student_support_profile_submitted":"student_support_profile_saved",target_type:"student_support_profile",target_id:id,metadata_safe:{status:payload.status,has_photo:Boolean(privatePhotoPath),has_verification:Boolean(verificationPath),platform:normalized?.platform??null}});
 if(intent==="submit"){const name=profile.preferred_name||profile.legal_name||raw.displayName||"Student",email=String(profile.primary_email??user.email??"");await queueStudentSupportEmail({recipient:email,templateKey:"student_support_received",idempotencyKey:`student-support-received:${id}:${now}`,name,message:"We received your Meet a Student profile. It is now in the protected national-office review line.",path:"/meet-a-student/apply"});await queueStudentSupportEmail({recipient:"nationals@estherfundsinc.org",templateKey:"student_support_admin_alert",idempotencyKey:`student-support-admin-alert:${id}:${now}`,name:"National Office",message:`${raw.displayName} submitted a profile for ${raw.institution}. Review the story, redacted documentation, consent, photo, and external support link before publishing.`,path:`/admin/student-support/${id}`});await admin.from("notifications").insert({user_id:user.id,title:"Meet a Student profile received",body:"Your profile is private while the EFF national team reviews it.",href:"/meet-a-student/apply"});}
 revalidatePath("/meet-a-student");revalidatePath("/meet-a-student/apply");revalidatePath("/admin/student-support");redirect(`/meet-a-student/apply?${intent==="submit"?"submitted=1":"saved=1"}`);
}
export async function withdrawStudentSupportProfile(){const client=await createClient();const{data:{user}}=await client.auth.getUser();if(!user)redirect("/sign-in?next=/meet-a-student/apply");const admin=createAdminClient();const{data:item}=await admin.from("student_support_profiles").select("id,slug,public_photo_path").eq("student_id",user.id).maybeSingle();if(!item)redirect("/meet-a-student/apply");if(item.public_photo_path)await admin.storage.from("student-support-public").remove([item.public_photo_path]);await admin.from("student_support_profiles").update({status:"withdrawn",public_photo_path:null,published_at:null,updated_at:new Date().toISOString()}).eq("id",item.id);await admin.from("audit_events").insert({actor_id:user.id,action:"student_support_profile_withdrawn",target_type:"student_support_profile",target_id:item.id,metadata_safe:{}});revalidatePath("/meet-a-student");revalidatePath(`/meet-a-student/${item.slug}`);revalidatePath("/meet-a-student/apply");redirect("/meet-a-student/apply?withdrawn=1");}
