import type {Metadata} from "next";
import Link from "next/link";
import {CheckCircle2,Eye,FileCheck2,LockKeyhole,ShieldAlert} from "lucide-react";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {statusLabels,type StudentSupportStatus} from "@/lib/student-support";
import {saveStudentSupportProfile,withdrawStudentSupportProfile} from "./actions";
export const metadata:Metadata={title:"Create a Meet a Student profile",description:"Create a verified student support profile for the EFF Meet a Student directory."};
export default async function StudentSupportApplication({searchParams}:{searchParams:Promise<{error?:string;saved?:string;submitted?:string;withdrawn?:string}>}){
 const query=await searchParams,client=await createClient();const{data:{user}}=await client.auth.getUser();
 if(!user)return <main className="section support-apply"><div className="shell support-narrow"><div className="card support-signin"><LockKeyhole/><div><div className="eyebrow">Student account required</div><h2>Sign in before creating your profile.</h2><p>Your draft, private documents, and review status stay connected to your secure EFF account.</p><Link className="button" href="/sign-in?next=/meet-a-student/apply">Sign in or create an account</Link></div></div></div></main>;
 const admin=createAdminClient();const[{data:item},{data:portalProfile}]=await Promise.all([admin.from("student_support_profiles").select("*").eq("student_id",user.id).maybeSingle(),admin.from("profiles").select("legal_name,preferred_name,institution,major").eq("id",user.id).maybeSingle()]);
 const status=(item?.status??"draft") as StudentSupportStatus,canEdit=!item||["draft","changes_requested","approved","declined","paused","withdrawn"].includes(status);
 return <main className="section support-apply"><div className="shell support-form-shell"><div className="support-page-heading"><div><div className="eyebrow">Meet a Student</div><h1>Create your support profile</h1><p>Tell your story once. EFF reviews your redacted documentation and external support link before anything becomes public.</p></div><Link className="button outline" href="/meet-a-student">View public directory</Link></div>
 {query.error&&<div className="notice support-error" role="alert"><ShieldAlert/>{query.error}</div>}{query.saved&&<div className="notice"><CheckCircle2/>Your private draft was saved.</div>}{query.submitted&&<div className="notice"><CheckCircle2/>Submitted. Check your inbox and spam folder for the receipt. Nothing is public until EFF approves it.</div>}{query.withdrawn&&<div className="notice">Your profile has been removed from the directory.</div>}
 {item&&<section className="support-status-card"><div><span className={`support-status status-${status}`}>{statusLabels[status]}</span><h2>{item.display_name||"Your profile"}</h2><p>{status==="pending"?"The national team is reviewing your story, consent, documents, and external link.":status==="approved"?"Your approved profile is visible in the public directory.":"You can update the details below."}</p>{item.review_note&&<div className="support-review-note"><strong>Message from EFF</strong><p>{item.review_note}</p></div>}</div>{status==="approved"&&<Link className="button" href={`/meet-a-student/${item.slug}`}>View live profile</Link>}</section>}
 <div className="support-steps"><div><Eye/><strong>1. You write</strong><span>Share only what the public should see.</span></div><div><FileCheck2/><strong>2. EFF verifies</strong><span>Private documents stay protected.</span></div><div><CheckCircle2/><strong>3. EFF publishes</strong><span>Your page links to your approved external fundraiser.</span></div></div>
 {canEdit?<form action={saveStudentSupportProfile} className="support-profile-form">{status==="approved"&&<div className="notice support-full">Editing a live profile temporarily removes it until EFF reviews the new version.</div>}
  <section className="card support-form-section"><div className="eyebrow">Public identity</div><h2>How should donors meet you?</h2><div className="support-field-grid"><label>Public display name <b>required</b><input name="displayName" defaultValue={item?.display_name??portalProfile?.preferred_name??portalProfile?.legal_name??""} maxLength={80} required placeholder="Taylor M."/><small>Use a first name and last initial if preferred.</small></label><label>School or college <b>required</b><input name="institution" defaultValue={item?.institution??portalProfile?.institution??""} maxLength={160} required/></label><label className="support-wide">Profile headline <b>required</b><input name="headline" defaultValue={item?.headline??""} minLength={10} maxLength={140} required placeholder="Help me stay enrolled and finish my nursing degree"/></label><label>City and state<input name="locationText" defaultValue={item?.location_text??""} maxLength={100} placeholder="Atlanta, GA"/></label><label>Major or program<input name="major" defaultValue={item?.major??portalProfile?.major??""} maxLength={120}/></label><label>Class year<input name="classYear" defaultValue={item?.class_year??""} maxLength={50} placeholder="Junior or Class of 2027"/></label><label>Optional public photo<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"/><small>{item?.private_photo_path?"A private photo is on file. Uploading a new one replaces it.":"JPG, PNG, or WEBP; maximum 6 MB."}</small></label></div></section>
  <section className="card support-form-section"><div className="eyebrow">Your story</div><h2>Help people understand the barrier.</h2><label>Public story <b>required</b><textarea name="story" defaultValue={item?.story??""} minLength={150} maxLength={2500} required rows={10} placeholder="Explain what you study, what happened, what you already tried, and what staying enrolled means for your future."/><small>150–2,500 characters. Do not include account numbers, student IDs, medical records, or private contact information.</small></label><label>Short need summary <b>required</b><textarea name="needSummary" defaultValue={item?.need_summary??""} minLength={40} maxLength={500} required rows={4} placeholder="I am seeking help with a verified balance that could interrupt my enrollment."/></label></section>
  <section className="card support-form-section"><div className="eyebrow">Support destination</div><h2>Where should donors continue?</h2><div className="support-field-grid"><label>Amount you are seeking <b>required</b><input name="amountNeeded" type="number" min="1" max="100000" step="0.01" defaultValue={item?.amount_needed??""} required/></label><label className="support-wide">Public fundraising or payment page <b>required</b><input name="fundraiserUrl" type="url" defaultValue={item?.fundraiser_url??""} required placeholder="https://www.gofundme.com/f/your-campaign"/><small>EFF verifies this link. Donors complete support there; EFF does not receive or control that transaction.</small></label></div></section>
  <section className="card support-form-section"><div className="eyebrow">Private verification</div><h2>Give EFF enough to review the public claim.</h2><div className="privacy-banner"><ShieldAlert/><div><strong>Redact sensitive information first.</strong><span>Never upload Social Security numbers, passwords, verification codes, tax returns, full bank details, full student IDs, or unnecessary medical information.</span></div></div><label>Redacted school, enrollment, or balance document <b>required to submit</b><input name="verificationDocument" type="file" accept="application/pdf,image/jpeg,image/png,image/webp"/><small>{item?.verification_document_path?`A private document is on file${item.verification_document_name?`: ${item.verification_document_name}`:""}. Uploading a new one replaces it.`:"PDF, JPG, PNG, or WEBP; maximum 8 MB. Never shown publicly."}</small></label></section>
  <section className="card support-form-section support-confirmations"><div className="eyebrow">Before you submit</div><h2>Consent and safety</h2><label><input name="consentConfirmed" type="checkbox" defaultChecked={item?.consent_confirmed}/> EFF may review and publish the public profile fields if approved.</label><label><input name="accuracyConfirmed" type="checkbox" defaultChecked={item?.accuracy_confirmed}/> My story, amount, and external link are accurate.</label><label><input name="ageConfirmed" type="checkbox" defaultChecked={item?.age_or_guardian_confirmed}/> I am 18+, or my parent/legal guardian approved this submission.</label><label><input name="safetyConfirmed" type="checkbox" defaultChecked={item?.sensitive_information_warning_confirmed}/> I removed sensitive information EFF told me not to share.</label><p className="muted">Submission does not guarantee publication, donations, an EFF award, or any outcome.</p></section>
  <div className="support-form-actions"><button className="button outline" name="intent" value="draft" formNoValidate>Save private draft</button><button className="button" name="intent" value="submit">Submit for EFF review</button></div>
 </form>:<div className="card"><h2>Your profile is in review.</h2><p>Nothing is public yet. You may withdraw now or contact the national office if something must change.</p></div>}
 {item&&status!=="withdrawn"&&<form action={withdrawStudentSupportProfile} className="support-withdraw"><button className="text-button">Withdraw and remove my profile</button></form>}
 </div></main>;
}
