import Link from "next/link";
import {requireStaff} from "@/lib/auth/staff";
import {bulkTransitionApplications} from "./actions";
import {BulkSelectionControls} from "./bulk-selection-controls";

type Params={q?:string;status?:string;need?:string;min_amount?:string;max_amount?:string;urgent?:string;page?:string;per_page?:string;bulk_updated?:string;bulk_failed?:string;bulk_error?:string};
type Answer={question_key:string;value:unknown};

const money=(value:unknown)=>{const parsed=Number(String(value??"").replace(/[^0-9.]/g,""));return Number.isFinite(parsed)?parsed:0};
const answer=(answers:Answer[],key:string)=>answers.find(item=>item.question_key===key)?.value;
const excerpt=(value:string,max=180)=>value.length>max?`${value.slice(0,max).trim()}…`:value;

export default async function ApplicationsAdmin({searchParams}:{searchParams:Promise<Params>}){
  const params=await searchParams;const {supabase,roles}=await requireStaff();
  const canBulk=roles.some(item=>["program_admin","super_admin"].includes(item.role));
  const allowedPageSizes=[50,100,250];const requestedPageSize=Number(params.per_page)||100;const pageSize=allowedPageSizes.includes(requestedPageSize)?requestedPageSize:100;const page=Math.max(1,Number(params.page)||1);const from=(page-1)*pageSize;
  const queueStatuses=["applied","review_by_admin","additional_information_needed","draft"] as const;
  const queueResults=await Promise.all(queueStatuses.map(status=>supabase.from("applications").select("id",{count:"exact",head:true}).eq("status",status)));
  let query=supabase.from("applications").select("id,status,submitted_at,updated_at,profiles!applications_applicant_id_fkey(legal_name,primary_email,institution),program_cycles(name,programs(name)),application_answers(question_key,value)",{count:"exact"}).order("updated_at",{ascending:false}).range(from,from+pageSize-1);
  if(params.status)query=query.eq("status",params.status);
  const {data,error,count}=await query;
  if(error)return <main className="section white"><div className="shell"><Link href="/admin" className="card-link">← Command center</Link><div className="notice error-text" style={{marginTop:24}}><strong>The application workspace could not load.</strong><p>Please try again. Your application records were not changed.</p><Link className="button outline" href="/admin/applications">Retry workspace</Link></div></div></main>;
  const min=params.min_amount?Number(params.min_amount):null;const max=params.max_amount?Number(params.max_amount):null;
  const urgentWords=/urgent|emergency|eviction|past due|shut.?off|disconnect|deadline|food|housing|homeless|crisis|tuition balance/i;
  const filtered=(data??[]).filter(item=>{
    const answers=(item.application_answers as unknown as Answer[])??[];const amount=money(answer(answers,"amount_requested"));
    const need=String(answer(answers,"need_category")??"");const narrative=String(answer(answers,"financial_need_description")??"");
    if(params.q&&!JSON.stringify(item).toLowerCase().includes(params.q.toLowerCase()))return false;
    if(params.need&&need!==params.need)return false;if(min!==null&&amount<min)return false;if(max!==null&&amount>max)return false;
    if(params.urgent==="yes"&&!urgentWords.test(`${need} ${narrative}`))return false;return true;
  });
  const statuses=["applied","review_by_admin","additional_information_needed","approved","denied","withdrawn","archived"];
  const needs=["Tuition or fees","Housing or utilities","Food","Transportation","Books or supplies","Technology","Childcare","Health or wellness","Other"];
  return <main className="section white"><div className="shell"><Link href="/admin" className="card-link">← Command center</Link>
    <div className="section-head"><div><div className="eyebrow">Solo Review Mode</div><h2>Review applications in manageable batches</h2><p className="muted">Open a focused queue, show up to 250 applications, select the displayed batch, and apply one audited status update.</p></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{filtered[0]&&<Link className="button" href={`/admin/applications/${filtered[0].id}`}>Review next application</Link>}<Link className="button outline" href="/admin/applicant-pool">View full applicant pool</Link></div></div>
    <div className="stats admin-stats" style={{marginBottom:24}}>{queueStatuses.map((status,index)=><Link className="stat" href={{pathname:"/admin/applications",query:{status,per_page:String(pageSize)}}} key={status}><strong>{queueResults[index].count??0}</strong><span>{status==="applied"?"New submissions":status==="review_by_admin"?"In review":status==="additional_information_needed"?"Waiting on students":"Drafts"}</span></Link>)}</div>
    {params.bulk_updated&&<div className="notice"><strong>{params.bulk_updated} application(s) updated.</strong> Status emails were queued automatically.{Number(params.bulk_failed)>0?` ${params.bulk_failed} could not be changed because the transition was not allowed.`:""}</div>}
    {params.bulk_error&&<div className="notice error-text"><strong>Bulk update not completed:</strong> {params.bulk_error}</div>}
    <form className="admin-filter" style={{marginBottom:24}}><input name="q" defaultValue={params.q} placeholder="Name, email, school, ID, or answer"/><select name="status" defaultValue={params.status??""}><option value="">All statuses</option>{statuses.map(status=><option value={status} key={status}>{status.replaceAll("_"," ")}</option>)}</select><select name="need" defaultValue={params.need??""}><option value="">All need types</option>{needs.map(need=><option key={need}>{need}</option>)}</select><input name="min_amount" type="number" min="0" defaultValue={params.min_amount} placeholder="Minimum $"/><input name="max_amount" type="number" min="0" defaultValue={params.max_amount} placeholder="Maximum $"/><label className="check"><input name="urgent" type="checkbox" value="yes" defaultChecked={params.urgent==="yes"}/><span>Urgency signals</span></label><select name="per_page" defaultValue={String(pageSize)} aria-label="Applications per page">{allowedPageSizes.map(size=><option key={size} value={size}>{size} per page</option>)}</select><button className="button">Apply filters</button><Link className="button outline" href="/admin/applications">Clear</Link></form>
    <form action={bulkTransitionApplications}>{canBulk&&<section className="card" style={{marginBottom:20}}><h3>Bulk status update</h3><p className="muted">Select up to 250 displayed applications. Every successful change is audited and queues an individualized status email.</p><BulkSelectionControls count={filtered.length}/><div className="admin-filter"><select name="new_status" required defaultValue=""><option value="" disabled>New status</option>{statuses.slice(1).map(status=><option key={status} value={status}>{status.replaceAll("_"," ")}</option>)}</select><input name="reason" required placeholder="Internal reason for this batch"/><input name="applicant_note" placeholder="Optional message shown in the portal"/><button className="button">Update selected</button></div></section>}
      <div className="table-wrap"><table><thead><tr>{canBulk&&<th>Select</th>}<th>Applicant</th><th>Quick summary</th><th>Need</th><th>Requested</th><th>Status</th><th>Submitted</th><th></th></tr></thead><tbody>{filtered.map(item=>{const profile=item.profiles as unknown as {legal_name:string|null;primary_email:string|null;institution:string|null};const answers=(item.application_answers as unknown as Answer[])??[];const need=String(answer(answers,"need_category")??"Not provided");const amount=money(answer(answers,"amount_requested"));const narrative=String(answer(answers,"financial_need_description")??"").trim();const cycle=item.program_cycles as unknown as {name:string;programs:{name:string}}|null;const urgent=urgentWords.test(`${need} ${narrative}`);return <tr key={item.id}>{canBulk&&<td><input aria-label={`Select ${profile?.legal_name??"application"}`} type="checkbox" name="application_ids" value={item.id}/></td>}<td><strong>{profile?.legal_name??"Applicant"}</strong><br/><small>{profile?.primary_email}<br/>{profile?.institution}<br/>{item.id}</small></td><td><strong>{cycle?.programs?.name??"Program not listed"}</strong><br/><small>{cycle?.name}<br/>{narrative?excerpt(narrative):"No financial-need summary provided."}</small></td><td>{need}{urgent&&<><br/><span className="status status-additional_information_needed">Urgency signal</span></>}</td><td>{amount?`$${amount.toLocaleString()}`:"—"}</td><td><span className={`status status-${item.status}`}>{item.status.replaceAll("_"," ")}</span></td><td>{item.submitted_at?new Date(item.submitted_at).toLocaleDateString():"—"}</td><td><Link className="button outline" href={`/admin/applications/${item.id}`}>Review</Link></td></tr>})}</tbody></table></div>
    </form><p className="muted">Showing {filtered.length} on page {page} of {Math.max(1,Math.ceil((count??0)/pageSize))} · {count??0} application(s) in this status. “Urgency signal” is a review aid based on the applicant’s own words; it is not an eligibility or award decision.</p>
    <div style={{display:"flex",gap:12,marginTop:16}}>{page>1&&<Link className="button outline" href={{pathname:"/admin/applications",query:{...params,page:String(page-1)}}}>← Previous</Link>}{from+pageSize<(count??0)&&<Link className="button outline" href={{pathname:"/admin/applications",query:{...params,page:String(page+1)}}}>Next →</Link>}</div></div></main>;
}
