import { notFound } from "next/navigation";
import { CalendarDays, CheckCircle2, HeartHandshake, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { startApplication } from "./actions";

const eligibility = ["U.S. citizen, U.S. national, or permanent resident", "Completed the FAFSA", "Demonstrated unmet financial need verified by your college or university", "Undergraduate student who has not earned a bachelor’s degree", "Enrolled at an accredited U.S. college or university", "No minimum GPA; open to students in every field"];

export default async function ProgramDetail({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params;
  const supabase=await createClient();
  const {data:program}=await supabase.from("programs").select("id,slug,name,description,program_cycles(id,name,opens_at,closes_at,status,award_config,form_versions(id,version,published_at))").eq("slug",slug).single();
  if(!program) notFound();
  const cycles=program.program_cycles as unknown as Array<{id:string;name:string;closes_at:string|null;status:string;award_config:Record<string,string>;form_versions:Array<{id:string;version:number;published_at:string|null}>}>;
  const cycle=cycles.find(item=>item.status==="open");
  const form=cycle?.form_versions.find(item=>item.published_at);
  const rolling=slug==="for-such-a-time-as-this";
  if(!rolling&&slug!=="name-your-need") return <main className="section"><div className="shell" style={{maxWidth:850}}><div className="eyebrow">EFF-administered program</div><h2>{program.name}</h2><p className="muted">{program.description}</p><div className="notice"><strong>Applications are not currently open.</strong><br/>Program details will be published after EFF approves the cycle’s eligibility, award terms, and deadline.</div></div></main>;
  const title=rolling?"For Such a Time as This Scholarship":"The “Name Your Need” Scholarship";
  return <main><section className="program-hero"><div className="shell"><div className="eyebrow">Official EFF application</div><h1>{title}</h1><p className="scripture">“For such a time as this.” — Esther 4:14</p><p>{rolling?"Support for students facing a defining season when timely financial help can protect their path to graduation.":"You tell us, in your own words, what you need most to stay enrolled—and our team steps in to help."}</p>{cycle&&form?<form action={startApplication}><input type="hidden" name="cycle_id" value={cycle.id}/><input type="hidden" name="form_version_id" value={form.id}/><input type="hidden" name="program_slug" value={slug}/><button className="button tan" type="submit"><HeartHandshake size={19}/> Start or continue application</button></form>:<div className="notice">Applications are currently closed.</div>}</div></section><section className="section white"><div className="shell split" style={{alignItems:"start"}}><div><div className="eyebrow">About this scholarship</div><h2>{rolling?"Help for the season you’re in":"Name what you need"}</h2><p>This need-based award helps undergraduate students address verified unmet financial needs that could interrupt enrollment.</p>{rolling?<><div className="deadline-card"><CalendarDays/><div><strong>Rolling application period</strong><br/>There is no fixed deadline. Applications are reviewed as funding and capacity allow.</div></div><div className="deadline-card"><Users/><div><strong>Multiple recipients</strong><br/>EFF expects to select multiple qualified recipients. Award amounts may vary based on verified need and available funds.</div></div></>:<div className="deadline-card"><CalendarDays/><div><strong>Application deadline</strong><br/>July 31, 2026 at 11:59 p.m. Eastern</div></div>}<p className="muted"><strong>Early application is strongly encouraged.</strong> Awards are not guaranteed and are determined by EFF after review and verification.</p></div><div className="card"><h3>Eligibility — you must meet all</h3><ul className="check-list">{eligibility.map(item=><li key={item}><CheckCircle2 size={19}/><span>{item}</span></li>)}</ul><p><strong>If you do not meet every requirement, please do not apply.</strong></p></div></div></section></main>;
}
