"use server";
import {redirect} from "next/navigation";
import {revalidatePath} from "next/cache";
import {createClient} from "@/lib/supabase/server";

async function authenticated(){const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/sign-in?next=%2Fapply-everywhere%2Fstart");return {db,user};}
export async function activateApplyAll(){const {db,user}=await authenticated();const {error}=await db.from("applyall_profiles").upsert({user_id:user.id},{onConflict:"user_id"});if(error)redirect(`/apply-everywhere/start?error=${encodeURIComponent("Apply Everywhere is not available yet. Please return after launch setup is complete.")}`);redirect("/apply-everywhere/dashboard");}
export async function saveSchool(formData:FormData){const {db,user}=await authenticated();const institutionId=String(formData.get("institutionId")??"");const {data:profile,error:profileError}=await db.from("applyall_profiles").upsert({user_id:user.id},{onConflict:"user_id"}).select("id").single();if(profileError||!profile)redirect("/apply-everywhere/start?error=We+could+not+activate+your+Apply+Everywhere+profile.");const {error}=await db.from("applyall_school_selections").upsert({profile_id:profile.id,institution_id:institutionId,applicant_type:"FIRST_YEAR",admission_term:"Fall 2027"},{onConflict:"profile_id,institution_id,applicant_type,admission_term"});if(error)redirect(`/apply-everywhere/schools?error=${encodeURIComponent("We could not save that school. Please try again.")}`);revalidatePath("/apply-everywhere/dashboard");redirect("/apply-everywhere/dashboard?message=School+saved+to+your+Apply+Everywhere+list.");}
export async function removeSchool(formData:FormData){const {db,user}=await authenticated();const selectionId=String(formData.get("selectionId")??"");const {data:profile}=await db.from("applyall_profiles").select("id").eq("user_id",user.id).single();if(profile)await db.from("applyall_school_selections").delete().eq("id",selectionId).eq("profile_id",profile.id);revalidatePath("/apply-everywhere/dashboard");}
