import type { ParsedScholarship,SourceAdapter } from "./types";
const entities:Record<string,string>={amp:"&",quot:'"',apos:"'",nbsp:" ",ndash:"–",mdash:"—",ldquo:'“',rdquo:'”',rsquo:"’"};
export const cleanText=(value:string)=>value.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]*>/g," ").replace(/&(#x?[0-9a-f]+|[a-z]+);/gi,(_,entity:string)=>{if(entity[0]==="#"){const hex=entity[1]?.toLowerCase()==="x";return String.fromCodePoint(parseInt(entity.slice(hex?2:1),hex?16:10));}return entities[entity.toLowerCase()]??`&${entity};`;}).replace(/\s+/g," ").trim();
const links=(html:string)=>[...html.matchAll(/<a\s[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].map(m=>({url:m[1],label:cleanText(m[2]),index:m.index??0,end:(m.index??0)+m[0].length}));
const absolute=(url:string,base:string)=>{try{return new URL(url,base).toString();}catch{return "";}};
const amountFrom=(title:string,body="")=>cleanText(`${title} ${body}`).match(/\$[\d,]+(?:\.\d{2})?(?:\s*(?:–|-|to)\s*\$?[\d,]+(?:\.\d{2})?)?/i)?.[0]??null;
export const scholarshipCollectiveAdapter:SourceAdapter={key:"scholarship_collective",parse(html,sourceUrl){const found:ParsedScholarship[]=[];let level="all";const markers=[...html.matchAll(/<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/gi)].map(m=>({at:m.index??0,label:cleanText(m[1])}));for(const link of links(html)){for(const marker of markers){if(marker.at>link.index)break;if(/high school|undergraduate|graduate/i.test(marker.label))level=marker.label.toLowerCase();}const nearby=cleanText(html.slice(link.end,link.end+260));const due=nearby.match(/(?:deadline\s*:|\bdue\s+)([^|•]{2,45}?)(?=\s{2,}|apply|learn|$)/i)?.[1]?.replace(/[().]/g," ").trim()??"varies";const url=absolute(link.url,sourceUrl);if(!url||link.label.length<4||(!/scholarship|award|grant|fellowship/i.test(link.label)&&due==="varies")||/apply now|learn more|money list/i.test(link.label))continue;found.push({title:link.label,sponsor:null,amountText:amountFrom(link.label),deadlineText:due,originalUrl:url,sourceUrl,academicLevels:[level]});}return found;}};
function parseJlvBlocks(html:string,sourceUrl:string){const results:ParsedScholarship[]=[];for(const paragraph of html.match(/<p\b[^>]*>[\s\S]*?<\/p>/gi)??[]){const lead=paragraph.match(/<strong[^>]*>\s*<a\s[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>\s*<\/strong>/i);if(!lead)continue;const title=cleanText(lead[2]);const deadline=cleanText(paragraph.match(/<strong[^>]*>\s*(?:Deadline|Closing Date)\s*<\/strong>\s*:\s*([\s\S]*?)(?:<br|<\/p>)/i)?.[1]??"varies");const sponsor=cleanText(paragraph.match(/<strong[^>]*>\s*Sponsor\s*<\/strong>\s*:\s*([\s\S]*?)(?:<br|<\/p>)/i)?.[1]??"")||null;results.push({title,sponsor,amountText:amountFrom("",paragraph.match(/<strong[^>]*>\s*(?:Amount|Award)\s*<\/strong>\s*:\s*([\s\S]*?)(?:<br|<\/p>)/i)?.[1]??""),deadlineText:deadline,originalUrl:absolute(lead[1],sourceUrl),sourceUrl});}if(results.length)return results;for(const block of html.split(/<h[234][^>]*>/i).slice(1)){const heading=block.match(/^([\s\S]*?)<\/h[234]>/i);if(!heading)continue;const title=cleanText(heading[1]);if(!/scholarship|award|grant|fellowship/i.test(title))continue;const body=block.slice(heading[0].length,heading[0].length+1800);const link=links(body).find(item=>!/facebook|twitter|pinterest|subscribe/i.test(item.label));if(!link)continue;const deadline=(cleanText(body).match(/(?:Deadline|Closing Date)\s*:?\s*([^|•]{3,50}?)(?=\s{2,}|Amount|Award|Eligibility|Apply|$)/i)?.[1]??"varies").trim();results.push({title,sponsor:null,amountText:amountFrom(title,body),deadlineText:deadline,originalUrl:absolute(link.url,sourceUrl),sourceUrl});}return results;}
export const jlvAdapter:SourceAdapter={key:"jlv_college_counseling",parse(html,sourceUrl){const direct=parseJlvBlocks(html,sourceUrl);if(direct.length)return direct;const decoded=html.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&amp;/g,"&");return parseJlvBlocks(decoded,sourceUrl);}};
export function adapterFor(key:string){if(key===scholarshipCollectiveAdapter.key)return scholarshipCollectiveAdapter;if(key===jlvAdapter.key)return jlvAdapter;throw new Error(`Unknown source adapter: ${key}`)}
