export type ResourceSource={key:string;name:string;url:string;tags:string[];levels:string[]};
export const RESOURCE_SOURCES:ResourceSource[]=[
{key:"fastweb",name:"Fastweb Scholarship Search",url:"https://www.fastweb.com/",tags:["general-search"],levels:["high school","undergraduate","graduate"]},
{key:"scholarships_com",name:"Scholarships.com",url:"https://www.scholarships.com/",tags:["general-search"],levels:["high school","undergraduate","graduate"]},
{key:"bigfuture",name:"College Board BigFuture Scholarship Search",url:"https://bigfuture.collegeboard.org/scholarship-search",tags:["general-search"],levels:["high school","undergraduate"]},
{key:"scholarships360",name:"Scholarships360",url:"https://scholarships360.org/",tags:["general-search"],levels:["high school","undergraduate","graduate"]},
{key:"bold",name:"Bold.org Scholarships",url:"https://bold.org/",tags:["general-search","quick-apply"],levels:["high school","undergraduate","graduate"]},
{key:"going_merry",name:"Going Merry",url:"https://www.goingmerry.com/",tags:["general-search"],levels:["high school","undergraduate","graduate"]},
{key:"niche",name:"Niche Scholarships",url:"https://www.niche.com/colleges/scholarships/",tags:["general-search"],levels:["high school","undergraduate"]},
{key:"unigo",name:"Unigo Scholarships",url:"https://www.unigo.com/scholarships",tags:["general-search"],levels:["high school","undergraduate","graduate"]},
{key:"petersons",name:"Peterson's Scholarship Search",url:"https://www.petersons.com/scholarship-search.aspx",tags:["general-search"],levels:["high school","undergraduate","graduate"]},
{key:"sallie_mae",name:"Sallie Mae Scholarship Search",url:"https://www.salliemae.com/college-planning/tools/scholarship-search/",tags:["general-search"],levels:["high school","undergraduate","graduate"]},
{key:"careeronestop",name:"CareerOneStop Scholarship Finder",url:"https://www.careeronestop.org/Toolkit/Training/find-scholarships.aspx",tags:["general-search","government"],levels:["high school","undergraduate","graduate"]},
{key:"chegg",name:"Chegg Scholarships",url:"https://www.chegg.com/scholarships",tags:["general-search"],levels:["high school","undergraduate","graduate"]},
{key:"appily",name:"Appily Scholarships",url:"https://www.appily.com/scholarships",tags:["general-search"],levels:["high school","undergraduate"]},
{key:"scholarshipowl",name:"ScholarshipOwl",url:"https://scholarshipowl.com/",tags:["general-search","quick-apply"],levels:["high school","undergraduate","graduate"]},
{key:"scholarship_america",name:"Scholarship America",url:"https://scholarshipamerica.org/",tags:["general-search"],levels:["high school","undergraduate","graduate"]},
{key:"ron_brown",name:"Ron Brown Scholar Program",url:"https://ronbrown.org/ron-brown-scholarship/",tags:["black-hbcu","high-achieving"],levels:["high school"]},
{key:"jackie_robinson",name:"Jackie Robinson Foundation Scholarship",url:"https://www.jackierobinson.org/",tags:["black-hbcu"],levels:["high school"]},
{key:"naacp",name:"NAACP Scholarships",url:"https://naacp.org/",tags:["black-hbcu"],levels:["high school","undergraduate","graduate"]},
{key:"tom_joyner",name:"Tom Joyner Foundation",url:"https://tomjoynerfoundation.org/",tags:["black-hbcu"],levels:["high school","undergraduate"]},
{key:"aauw",name:"AAUW Fellowships and Grants",url:"https://www.aauw.org/",tags:["women"],levels:["undergraduate","graduate"]},
{key:"peo",name:"P.E.O. International Educational Assistance",url:"https://www.peointernational.org/",tags:["women"],levels:["undergraduate","graduate"]},
{key:"rankin",name:"Jeannette Rankin Foundation",url:"https://rankinfoundation.org/",tags:["women"],levels:["undergraduate"]},
{key:"patsy_mink",name:"Patsy Takemoto Mink Education Support Awards",url:"https://www.patsyminkfoundation.org/",tags:["women","parents"],levels:["undergraduate","graduate"]},
{key:"gates",name:"The Gates Scholarship",url:"https://www.thegatesscholarship.org/",tags:["first-gen","high-achieving"],levels:["high school"]},
{key:"questbridge",name:"QuestBridge",url:"https://www.questbridge.org/",tags:["first-gen","high-achieving"],levels:["high school"]},
{key:"coca_cola",name:"Coca-Cola Scholars Foundation",url:"https://www.coca-colascholarsfoundation.org/",tags:["high-achieving"],levels:["high school"]},
{key:"dell_scholars",name:"Dell Scholars",url:"https://www.dellscholars.org/",tags:["first-gen"],levels:["high school"]},
{key:"horatio_alger",name:"Horatio Alger Scholarships",url:"https://scholars.horatioalger.org/",tags:["first-gen"],levels:["high school","undergraduate"]},
{key:"shpe",name:"SHPE Scholarships",url:"https://shpe.org/",tags:["heritage-immigrant","stem-health-trades"],levels:["high school","undergraduate","graduate"]},
{key:"nsbe",name:"NSBE Scholarships",url:"https://nsbe.org/",tags:["black-hbcu","stem-health-trades"],levels:["high school","undergraduate","graduate"]},
{key:"nsna",name:"NSNA Nursing Scholarships",url:"https://www.nsna.org/",tags:["stem-health-trades"],levels:["undergraduate","graduate"]},
{key:"smart_dod",name:"SMART Scholarship-for-Service Program",url:"https://www.smartscholarship.org/",tags:["stem-health-trades","military-veteran"],levels:["undergraduate","graduate"]},
{key:"mike_rowe",name:"mikeroweWORKS Work Ethic Scholarship",url:"https://www.mikeroweworks.org/scholarship/",tags:["stem-health-trades"],levels:["trade school"]},
{key:"teach_grant",name:"Federal TEACH Grant",url:"https://studentaid.gov/understand-aid/types/grants/teach",tags:["stem-health-trades","government"],levels:["undergraduate","graduate"]},
{key:"apia",name:"APIA Scholars",url:"https://apiascholars.org/scholarships/",tags:["heritage-immigrant"],levels:["high school","undergraduate"]},
{key:"college_fund",name:"American Indian College Fund",url:"https://collegefund.org/students/scholarships/",tags:["heritage-immigrant"],levels:["high school","undergraduate","graduate"]},
{key:"aises",name:"AISES Scholarships",url:"https://www.aises.org/students/scholarships",tags:["heritage-immigrant","stem-health-trades"],levels:["high school","undergraduate","graduate"]},
{key:"thedream_us",name:"TheDream.US Scholarships",url:"https://www.thedream.us/",tags:["heritage-immigrant","first-gen"],levels:["high school","undergraduate"]},
{key:"golden_door",name:"Golden Door Scholars",url:"https://www.goldendoorscholars.org/",tags:["heritage-immigrant","first-gen"],levels:["high school","undergraduate"]},
{key:"pat_tillman",name:"Pat Tillman Foundation Scholarship",url:"https://pattillmanfoundation.org/",tags:["military-veteran"],levels:["undergraduate","graduate"]},
{key:"amvets",name:"AMVETS Scholarships",url:"https://amvets.org/scholarships/",tags:["military-veteran"],levels:["high school","undergraduate","graduate"]},
{key:"student_veterans",name:"Student Veterans of America",url:"https://studentveterans.org/",tags:["military-veteran"],levels:["undergraduate","graduate"]},
{key:"generation_hope",name:"Generation Hope Scholar Program",url:"https://www.generationhope.org/",tags:["parents","first-gen"],levels:["undergraduate"]},
{key:"niche_no_essay",name:"Niche No-Essay Scholarship",url:"https://www.niche.com/colleges/scholarship/no-essay-scholarship/",tags:["quick-apply"],levels:["high school","undergraduate"]},
{key:"bold_no_essay",name:"Bold.org No-Essay Scholarships",url:"https://bold.org/scholarships/no-essay/",tags:["quick-apply"],levels:["high school","undergraduate","graduate"]}
];
