import "server-only";
import { createHash } from "node:crypto";
import { adapterFor } from "./adapters";
import type { ParsedScholarship } from "./types";
import { createAdminClient } from "../supabase/admin";

const VERSION="2.0.0";
const SOURCES:Record<string,string>={scholarship_collective:"https://www.thescholarshipcollective.com/scholarships",jlv_college_counseling:"https://jlvcollegecounseling.com/feed/"};
const normalize=(value:string)=>value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g," ").trim();
const makeSlug=(value:string)=>`${normalize(value).replace(/\s+/g,"-").slice(0,70)}-${createHash("sha1").update(value).digest("hex").slice(0,8)}`;
const canonical=(raw:string)=>{const url=new URL(raw);url.hash="";for(const key of [...url.searchParams.keys()])if(/^utm_|^(ref|source|affiliate|aff)$/i.test(key))url.searchParams.delete(key);return url.toString().replace(/\/$/,"");};
const amountNumber=(value:string|null)=>value?Number(value.match(/[\d,]+(?:\.\d{2})?/)?.[0].replace(/,/g,"")??0)||null:null;
function parseDeadline(value:string){const clean=value.replace(/\b(?:due|deadline)\b\s*:?/i,"").trim();if(/rolling|ongoing|monthly|every month/i.test(clean))return {kind:"rolling",date:null};if(/varies|various|see (?:site|website)/i.test(clean))return {kind:"varies",date:null};const parsed=new Date(clean);return Number.isNaN(parsed.valueOf())?null:{kind:"fixed",date:parsed.toISOString().slice(0,10)};}
function validate(item:ParsedScholarship){if(item.title.length<4||item.title.length>240)throw new Error("Invalid title");const url=new URL(item.originalUrl);if(!/^https?:$/.test(url.protocol))throw new Error("Unsafe provider URL");if(/application fee|processing fee|pay to apply/i.test(item.title))throw new Error("Possible fee-based listing");const parsed=parseDeadline(item.deadlineText);if(!parsed)throw new Error("Unrecognized deadline");return {url:canonical(item.originalUrl),deadline:parsed};}
async function fetchSource(url:string){const contact=process.env.IMPORTER_CONTACT_EMAIL??"notifications@estherfundsinc.org";const response=await fetch(url,{headers:{"User-Agent":`EFFScholarshipDirectory/1.0 (+mailto:${contact})`,Accept:"text/html,application/rss+xml;q=0.9"},signal:AbortSignal.timeout(20000),cache:"no-store"});if(!response.ok)throw new Error(`Source returned HTTP ${response.status}`);return response.text();}

export async function runSource(key:string){const db=createAdminClient();const sourceResult=await db.from("external_sources").select("*").eq("key",key).single();const source=sourceResult.data;if(sourceResult.error||!source)throw new Error(`Unknown source: ${key}`);if(!source.active||source.health==="paused")return {source:key,status:"paused"};const lock=await db.from("importer_runs").insert({source_id:source.id,status:"running",parser_version:VERSION}).select("id").single();if(lock.error){if(lock.error.code==="23505")return {source:key,status:"already_running"};throw lock.error;}const run=lock.data;const counts={seen:0,published:0,updated:0,rejected:0};try{const html=await fetchSource(SOURCES[key]??source.directory_url);const parsed=adapterFor(key).parse(html,source.directory_url);if(!parsed.length)throw new Error("No scholarship records found; source structure may have changed");const merged=new Map<string,ParsedScholarship>();for(const item of parsed){const id=canonical(item.originalUrl);const old=merged.get(id);merged.set(id,old?{...old,academicLevels:[...new Set([...(old.academicLevels??[]),...(item.academicLevels??[])])]}:item);}counts.seen=merged.size;
for(const item of merged.values()){try{const checked=validate(item);const normalized=normalize(item.title);const record={slug:makeSlug(`${normalized}|${checked.url}`),title:item.title,normalized_title:normalized,sponsor:item.sponsor,amount_text:item.amountText,amount_numeric:amountNumber(item.amountText),deadline_kind:checked.deadline.kind,deadline:checked.deadline.date,original_url:item.originalUrl,canonical_url:checked.url,eligibility:{academic_levels:item.academicLevels??[]},published_at:new Date().toISOString(),archived_at:null,updated_at:new Date().toISOString()};let lookup=await db.from("external_scholarships").select("id").eq("canonical_url",checked.url).maybeSingle();if(!lookup.data)lookup=await db.from("external_scholarships").select("id").eq("normalized_title",normalized).eq("deadline_kind",checked.deadline.kind).maybeSingle();let scholarshipId:string;if(lookup.data){const changed=await db.from("external_scholarships").update(record).eq("id",lookup.data.id);if(changed.error)throw changed.error;scholarshipId=lookup.data.id;counts.updated++;}else{const inserted=await db.from("external_scholarships").insert(record).select("id").single();if(inserted.error)throw inserted.error;scholarshipId=inserted.data.id;counts.published++;}const observation=await db.from("source_observations").upsert({source_id:source.id,scholarship_id:scholarshipId,source_record_key:createHash("sha256").update(checked.url).digest("hex"),source_page_url:item.sourceUrl,observed_data:item,last_seen_at:new Date().toISOString()},{onConflict:"source_id,source_record_key"});if(observation.error)throw observation.error;}catch(error){counts.rejected++;await db.from("scholarship_exceptions").insert({run_id:run.id,kind:"validation",detail_safe:error instanceof Error?error.message:"Record rejected",priority:1});}}
await db.from("external_scholarships").update({archived_at:new Date().toISOString()}).lt("deadline",new Date(Date.now()-30*86400000).toISOString().slice(0,10)).is("archived_at",null);await db.from("importer_runs").update({status:"succeeded",counts,completed_at:new Date().toISOString()}).eq("id",run.id);await db.from("external_sources").update({parser_version:VERSION,health:"healthy",failure_count:0,last_error:null,last_success_at:new Date().toISOString()}).eq("id",source.id);return {source:key,status:"succeeded",counts};}catch(error){const message=error instanceof Error?error.message:"Importer failed";const failures=source.failure_count+1;await db.from("importer_runs").update({status:"failed",counts,error_safe:message,completed_at:new Date().toISOString()}).eq("id",run.id);await db.from("external_sources").update({failure_count:failures,last_error:message,health:failures>=3?"paused":"degraded",active:failures>=3?false:source.active}).eq("id",source.id);return {source:key,status:"failed",error:message};}}
export async function runAllSources(){const results=[];for(const key of Object.keys(SOURCES))results.push(await runSource(key));return results;}
