import "server-only";
import { createHash } from "node:crypto";
import { adapterFor } from "./adapters";
import type { ParsedScholarship } from "./types";
import { createAdminClient } from "../supabase/admin";
import { RESOURCE_SOURCES } from "./catalog";
import { verifyLiveScholarshipLinks } from "./link-health";

const VERSION="2.1.0";
const SOURCES:Record<string,string>={scholarship_collective:"https://www.thescholarshipcollective.com/scholarships",jlv_college_counseling:"https://jlvcollegecounseling.com/category/scholarships/",uncf:"https://uncf.org/the-latest/scholarships-for-july-at-uncf",tmcf:"https://tmcf.org/scholarships/",swe:"https://swe.org/scholarships/",jack_kent_cooke:"https://www.jkcf.org/our-scholarships/",hsf:"https://www.hsf.net/"};
for(const source of RESOURCE_SOURCES)SOURCES[source.key]=source.url;
const EMPTY_IS_HEALTHY=new Set(["swe"]);
const normalize=(value:string)=>value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g," ").trim();
const makeSlug=(value:string)=>`${normalize(value).replace(/\s+/g,"-").slice(0,70)}-${createHash("sha1").update(value).digest("hex").slice(0,8)}`;
const canonical=(raw:string)=>{const url=new URL(raw);url.hash="";for(const key of [...url.searchParams.keys()])if(/^utm_|^(ref|source|affiliate|aff)$/i.test(key))url.searchParams.delete(key);return url.toString().replace(/\/$/,"");};
const amountNumber=(value:string|null)=>value?Number(value.match(/[\d,]+(?:\.\d{2})?/)?.[0].replace(/,/g,"")??0)||null:null;
function parseDeadline(value:string){
  const clean=value.replace(/\b(?:due|deadline|closing date|closes)\b\s*:?/i,"").replace(/[().]/g," ").trim();
  if(/rolling|ongoing|monthly|every month/i.test(clean))return {kind:"rolling",date:null};
  if(/varies|various|see (?:site|website)/i.test(clean))return {kind:"varies",date:null};
  const now=new Date();
  const hasYear=/\b(?:19|20)\d{2}\b/.test(clean);
  let parsed=new Date(hasYear?clean:`${clean}, ${now.getUTCFullYear()}`);
  if(!hasYear&&!Number.isNaN(parsed.valueOf())&&parsed.valueOf()<now.valueOf()-45*86400000)parsed=new Date(`${clean}, ${now.getUTCFullYear()+1}`);
  return Number.isNaN(parsed.valueOf())?null:{kind:"fixed",date:parsed.toISOString().slice(0,10)};
}
function validate(item:ParsedScholarship){if(item.title.length<4||item.title.length>240)throw new Error("Invalid title");const url=new URL(item.originalUrl);if(!/^https?:$/.test(url.protocol))throw new Error("Unsafe provider URL");if(/application fee|processing fee|pay to apply/i.test(item.title))throw new Error("Possible fee-based listing");const parsed=parseDeadline(item.deadlineText);if(!parsed)throw new Error("Unrecognized deadline");return {url:canonical(item.originalUrl),deadline:parsed};}
async function fetchText(url:string){const contact=process.env.IMPORTER_CONTACT_EMAIL??"notifications@estherfundsinc.org";const response=await fetch(url,{headers:{"User-Agent":`EFFScholarshipDirectory/1.0 (+mailto:${contact})`,Accept:"text/html,application/rss+xml;q=0.9"},signal:AbortSignal.timeout(20000),cache:"no-store"});if(!response.ok)throw new Error(`Source returned HTTP ${response.status}`);return response.text();}
const escapeAttribute=(value:string)=>value.replaceAll("&","&amp;").replaceAll('"',"&quot;");
async function fetchSource(key:string,url:string){
  if(key!=="jlv_college_counseling")return fetchText(url);
  const index=await fetchText(url);
  const postUrls=[...index.matchAll(/href=["'](https?:\/\/jlvcollegecounseling\.com\/\d{4}\/\d{2}\/\d{2}\/scholarship-saturday-[^"'?#]+\/?)["']/gi)].map(match=>match[1]);
  const recent=[...new Set(postUrls)].slice(0,6);
  if(!recent.length)throw new Error("No current Scholarship Saturday posts found");
  const pages=(await Promise.all(recent.flatMap(postUrl=>[postUrl,`${postUrl.replace(/\/?$/,"/")}2/`]).map(async pageUrl=>{try{return {pageUrl,html:await fetchText(pageUrl)};}catch{return null;}}))).filter((item):item is {pageUrl:string;html:string}=>Boolean(item));
  if(!pages.length)throw new Error("Current Scholarship Saturday posts could not be loaded");
  return pages.map(item=>`<section data-eff-source-url="${escapeAttribute(item.pageUrl)}">${item.html}</section>`).join("\n");
}

export async function runSource(key:string){const db=createAdminClient();const sourceResult=await db.from("external_sources").select("*").eq("key",key).single();const source=sourceResult.data;if(sourceResult.error||!source)throw new Error(`Unknown source: ${key}`);if(!source.active||source.health==="paused")return {source:key,status:"paused"};const lock=await db.from("importer_runs").insert({source_id:source.id,status:"running",parser_version:VERSION}).select("id").single();if(lock.error){if(lock.error.code==="23505")return {source:key,status:"already_running"};throw lock.error;}const run=lock.data;const counts={seen:0,published:0,updated:0,rejected:0};try{const sourceUrl=SOURCES[key]??source.directory_url;const html=await fetchSource(key,sourceUrl);const parsed=adapterFor(key).parse(html,sourceUrl);if(!parsed.length&&!EMPTY_IS_HEALTHY.has(key))throw new Error("No scholarship records found; source structure may have changed");const merged=new Map<string,ParsedScholarship>();for(const item of parsed){const id=canonical(item.originalUrl);const old=merged.get(id);merged.set(id,old?{...old,academicLevels:[...new Set([...(old.academicLevels??[]),...(item.academicLevels??[])])]}:item);}counts.seen=merged.size;
for(const item of merged.values()){try{const checked=validate(item);const normalized=normalize(item.title);const record={slug:makeSlug(`${normalized}|${checked.url}`),title:item.title,normalized_title:normalized,sponsor:item.sponsor,amount_text:item.amountText,amount_numeric:amountNumber(item.amountText),deadline_kind:checked.deadline.kind,deadline:checked.deadline.date,original_url:item.originalUrl,canonical_url:checked.url,eligibility:{academic_levels:item.academicLevels??[],categories:item.categoryTags??[]},published_at:new Date().toISOString(),archived_at:null,updated_at:new Date().toISOString()};let lookup=await db.from("external_scholarships").select("id").eq("canonical_url",checked.url).limit(1).maybeSingle();if(!lookup.data)lookup=await db.from("external_scholarships").select("id").eq("normalized_title",normalized).eq("deadline_kind",checked.deadline.kind).limit(1).maybeSingle();let scholarshipId:string;if(lookup.data){const changed=await db.from("external_scholarships").update(record).eq("id",lookup.data.id);if(changed.error)throw changed.error;scholarshipId=lookup.data.id;counts.updated++;}else{const inserted=await db.from("external_scholarships").insert(record).select("id").single();if(inserted.error)throw inserted.error;scholarshipId=inserted.data.id;counts.published++;}const observation=await db.from("source_observations").upsert({source_id:source.id,scholarship_id:scholarshipId,source_record_key:createHash("sha256").update(checked.url).digest("hex"),source_page_url:item.sourceUrl,observed_data:item,last_seen_at:new Date().toISOString()},{onConflict:"source_id,source_record_key"});if(observation.error)throw observation.error;}catch(error){counts.rejected++;await db.from("scholarship_exceptions").insert({run_id:run.id,kind:"validation",detail_safe:error instanceof Error?error.message:"Record rejected",priority:1});}}
await db.from("external_scholarships").update({archived_at:new Date().toISOString()}).lt("deadline",new Date(Date.now()-30*86400000).toISOString().slice(0,10)).is("archived_at",null);await db.from("importer_runs").update({status:"succeeded",counts,completed_at:new Date().toISOString()}).eq("id",run.id);await db.from("external_sources").update({directory_url:sourceUrl,parser_version:VERSION,health:"healthy",failure_count:0,last_error:null,last_success_at:new Date().toISOString()}).eq("id",source.id);return {source:key,status:"succeeded",counts};}catch(error){const message=error instanceof Error?error.message:"Importer failed";const failures=source.failure_count+1;await db.from("importer_runs").update({status:"failed",counts,error_safe:message,completed_at:new Date().toISOString()}).eq("id",run.id);await db.from("external_sources").update({failure_count:failures,last_error:message,health:failures>=3?"paused":"degraded",active:failures>=3?false:source.active}).eq("id",source.id);return {source:key,status:"failed",error:message};}}
export async function runAllSources(){const db=createAdminClient();const registered=await db.from("external_sources").upsert(RESOURCE_SOURCES.map(source=>({key:source.key,name:source.name,directory_url:source.url,permission_status:"written_permission",permission_notes:"Written permission represented by EFF; catalog resource is monitored and links to the provider's current public experience.",parser_version:VERSION,active:true})),{onConflict:"key"});if(registered.error)throw registered.error;const keys=Object.keys(SOURCES),results:Awaited<ReturnType<typeof runSource>>[]=[];for(let index=0;index<keys.length;index+=8)results.push(...await Promise.all(keys.slice(index,index+8).map(runSource)));const linkAudit=await verifyLiveScholarshipLinks();return {sources:results,linkAudit};}
