"use server";
import {revalidatePath} from "next/cache";
import {requireAdmin} from "@/lib/auth/staff";

export async function transitionApplication(formData: FormData) {const {supabase}=await requireAdmin();const id=String(formData.get("application_id"));const result=await supabase.rpc("staff_transition_application",{p_application_id:id,p_new_status:String(formData.get("new_status")),p_reason:String(formData.get("reason")??""),p_applicant_note:String(formData.get("applicant_note")??"")});if(result.error)throw new Error(result.error.message);revalidatePath(`/admin/applications/${id}`)}
export async function addInternalNote(formData: FormData) {const {supabase,user}=await requireAdmin();const id=String(formData.get("application_id"));const body=String(formData.get("body")??"").trim();if(body)await supabase.from("internal_notes").insert({application_id:id,author_id:user.id,body});revalidatePath(`/admin/applications/${id}`)}
export async function requestInformation(formData: FormData) {const {supabase,user}=await requireAdmin();const id=String(formData.get("application_id"));const item=String(formData.get("item")??"").trim();const due=String(formData.get("due_at")??"")||null;if(item){await supabase.from("information_requests").insert({application_id:id,requested_by:user.id,item,due_at:due});await supabase.rpc("staff_transition_application",{p_application_id:id,p_new_status:"additional_information_needed",p_reason:"Additional information requested",p_applicant_note:item})}revalidatePath(`/admin/applications/${id}`)}
export async function recordAward(formData: FormData) {const {supabase,user}=await requireAdmin();const id=String(formData.get("application_id"));const amount=Number(formData.get("amount"));if(!Number.isFinite(amount)||amount<=0)throw new Error("Enter a valid award amount.");const {data:application}=await supabase.from("applications").select("status").eq("id",id).single();if(application?.status!=="approved")throw new Error("Approve the application before issuing an award.");const award={application_id:id,amount,conditions:String(formData.get("conditions")??"").trim()||null,acceptance_deadline:String(formData.get("acceptance_deadline")??"")||null,disbursement_status:"pending_acceptance",scheduled_date:String(formData.get("scheduled_date")??"")||null};const {error}=await supabase.from("awards").upsert(award,{onConflict:"application_id"});if(error)throw new Error("The award could not be saved.");await supabase.from("audit_events").insert({actor_id:user.id,action:"award_recorded",target_type:"application",target_id:id,metadata_safe:{amount,acceptance_deadline:award.acceptance_deadline}});revalidatePath(`/admin/applications/${id}`);revalidatePath(`/applications/${id}`)}
export async function assignReviewer(formData: FormData) {const {supabase}=await requireAdmin();const id=String(formData.get("application_id"));const reviewerId=String(formData.get("reviewer_id"));const {error}=await supabase.rpc("assign_application_reviewer",{p_application_id:id,p_reviewer_id:reviewerId});if(error)throw new Error(error.message);revalidatePath(`/admin/applications/${id}`);revalidatePath("/admin/reviews")}
export async function correctStatus(formData:FormData){const {supabase}=await requireAdmin();const id=String(formData.get("application_id"));const {error}=await supabase.rpc("correct_application_status",{p_application_id:id,p_new_status:String(formData.get("new_status")),p_reason:String(formData.get("reason")??""),p_applicant_note:String(formData.get("applicant_note")??"")});if(error)throw new Error(error.message);revalidatePath(`/admin/applications/${id}`);revalidatePath(`/applications/${id}`)}
