import Link from "next/link";
import {notFound} from "next/navigation";
import {requireStaff} from "@/lib/auth/staff";
import {addInternalNote,assignReviewer,correctStatus,recordAward,requestInformation,sendApplicationEmail,transitionApplication} from "./actions";

type Profile={legal_name:string|null;primary_email:string|null;institution:string|null};
type Answer={question_key:string;value:unknown};
type Doc={id:string;kind:string;filename:string;storage_path:string};
type History={previous_status:string|null;new_status:string;reason:string|null;applicant_note:string|null;created_at:string};
type Note={id:string;body:string;created_at:string;profiles:{legal_name:string|null}};
type Request={id:string;item:string;due_at:string|null;response:string|null;resolved_at:string|null;created_at:string};
type Decision={decision:string;internal_reason:string;applicant_explanation:string|null;confirmed_at:string};
type Award={amount:number;conditions:string|null;acceptance_deadline:string|null;accepted_at:string|null;disbursement_status:string|null;scheduled_date:string|null};
type Message={id:string;template_key:string|null;status:string;created_at:string;sent_at:string|null;last_error_safe:string|null};
type Search={action_error?:string;action_done?:string};
const answerValue=(answers:Answer[],key:string)=>answers.find(item=>item.question_key===key)?.value;
const label=(value:string)=>value.replaceAll("_"," ");

export default async function AdminApplication({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Search>}) {
  const {id}=await params;
  const feedback=await searchParams;
  const {supabase,roles}=await requireStaff();
  const [{data:a},{data:messageRows}]=await Promise.all([supabase.from("applications").select("id,status,submitted_at,profiles!applications_applicant_id_fkey(*),application_answers(question_key,value),documents(id,kind,filename,storage_path),status_history(previous_status,new_status,reason,applicant_note,created_at),internal_notes(id,body,created_at,profiles!internal_notes_author_id_fkey(legal_name)),information_requests(id,item,due_at,response,resolved_at,created_at),decisions(decision,internal_reason,applicant_explanation,confirmed_at),awards(id,amount,conditions,acceptance_deadline,accepted_at,disbursement_status,scheduled_date,actual_date),program_cycles(name,programs(name))").eq("id",id).single(),supabase.from("messages").select("id,template_key,status,created_at,sent_at,last_error_safe").eq("application_id",id).order("created_at",{ascending:false}).limit(12)]);
  if(!a)notFound();

  const canManage=roles.some(item=>["program_admin","super_admin"].includes(item.role));
  const [{data:reviewerRoles},{data:assignments}]=canManage?await Promise.all([
    supabase.from("user_roles").select("user_id,role,active,profiles!user_roles_user_id_fkey(legal_name,primary_email)").eq("active",true).in("role",["reviewer","program_admin","super_admin"]),
    supabase.from("review_assignments").select("id,reviewer_id,conflict_disclosed,has_conflict,assigned_at,reviews(scores,notes,locked_at)").eq("application_id",id),
  ]):[{data:[]},{data:[]}];

  const profile=a.profiles as unknown as Profile;
  const answers=(a.application_answers as unknown as Answer[])??[];
  const rawDocs=(a.documents as unknown as Doc[])??[];
  const history=((a.status_history as unknown as History[])??[]).sort((x,y)=>y.created_at.localeCompare(x.created_at));
  const notes=((a.internal_notes as unknown as Note[])??[]).sort((x,y)=>y.created_at.localeCompare(x.created_at));
  const requests=((a.information_requests as unknown as Request[])??[]).sort((x,y)=>y.created_at.localeCompare(x.created_at));
  const decision=(a.decisions as unknown as Decision[])?.[0];
  const award=(a.awards as unknown as Award[])?.[0];
  const messages=(messageRows??[]) as Message[];
  const cycle=a.program_cycles as unknown as {name:string;programs:{name:string}}|null;
  const need=String(answerValue(answers,"need_category")??"Not provided");
  const amount=Number(String(answerValue(answers,"amount_requested")??"").replace(/[^0-9.]/g,""))||0;
  const needStatement=String(answerValue(answers,"financial_need_description")??"No financial-need statement was provided.");
  const docs=await Promise.all(rawDocs.map(async doc=>{const {data}=await supabase.storage.from("application-documents").createSignedUrl(doc.storage_path,300);return {...doc,url:data?.signedUrl??null}}));

  return <main className="section white"><div className="shell admin-detail">
    <div className="application-detail-nav"><Link href="/admin/applications" className="card-link">← Application workspace</Link><Link href="/admin/communications" className="card-link">Email delivery →</Link></div>
    {feedback.action_error&&<div className="notice error-text"><strong>Action not completed:</strong> {feedback.action_error}</div>}
    {feedback.action_done&&<div className="notice success-text"><strong>{feedback.action_done==="email_queued"?"Email queued.":feedback.action_done==="email_already_queued"?"Duplicate email prevented.":"Saved."}</strong> {feedback.action_done==="email_queued"?"It will be sent through the protected delivery system and tracked below.":feedback.action_done==="email_already_queued"?"That message was already queued within the last ten minutes.":<>The action was audited{["approved","denied","review_by_admin","correction"].includes(feedback.action_done)?" and the appropriate student notice was queued":""}.</>}</div>}
    <div className="section-head application-heading"><div><div className="eyebrow">{label(a.status)}</div><h2>{profile.legal_name??"Applicant"}</h2><p className="muted">{profile.primary_email} · {profile.institution} · Application {a.id}</p></div>{a.submitted_at&&<strong>Submitted {new Date(a.submitted_at).toLocaleString()}</strong>}</div>

    <section className="card application-summary-card"><div className="eyebrow">Application summary</div><h3>{cycle?.programs?.name??"Program not listed"} · {cycle?.name??"Cycle not listed"}</h3><div className="stats"><div className="stat"><strong>{need}</strong><span>Need category</span></div><div className="stat"><strong>{amount?`$${amount.toLocaleString()}`:"—"}</strong><span>Requested</span></div><div className="stat"><strong>{rawDocs.length}</strong><span>Documents</span></div><div className="stat"><strong>{label(a.status)}</strong><span>Current stage</span></div></div><p><strong>Student’s need statement:</strong> {needStatement}</p></section>

    <div className="admin-columns application-review-layout"><div>
      <section className="card"><div className="section-head"><div><div className="eyebrow">Student submission</div><h3>Application answers</h3></div><span className="status">{answers.length} answers</span></div><dl className="answer-list">{answers.sort((x,y)=>x.question_key.localeCompare(y.question_key)).map(item=><div key={item.question_key}><dt>{label(item.question_key)}</dt><dd>{String(item.value??"—")}</dd></div>)}</dl></section>
      <section className="card"><div className="section-head"><div><div className="eyebrow">Supporting files</div><h3>Documents and uploads</h3></div><span className="status">{docs.length} files</span></div>{docs.length?docs.map(doc=><div className="document-row" key={doc.id}><span><strong>{label(doc.kind)}</strong><br/><small>{doc.filename}</small></span>{doc.url?<a className="button outline" href={doc.url} target="_blank" rel="noreferrer">Open file</a>:<strong>Unavailable</strong>}</div>):<p className="muted">No documents are attached. If a file is required, use “Request a correction or upload” so the student receives a replyable portal task.</p>}</section>
      {decision&&<section className="card"><div className="section-head"><div><div className="eyebrow">Audited decision</div><h3>{label(decision.decision)}</h3></div>{decision.decision==="approved"&&<Link className="button outline" href={`/applications/${id}/acceptance-letter`}>View acceptance letter</Link>}</div><p><strong>Recorded:</strong> {new Date(decision.confirmed_at).toLocaleString()}</p><p><strong>Private basis:</strong> {decision.internal_reason}</p><div className="notice"><strong>Student message</strong><p>{decision.applicant_explanation||"No applicant-facing explanation was recorded."}</p></div></section>}
      <section className="card"><div className="eyebrow">Student communications</div><h3>Email delivery</h3>{messages.length?messages.map(message=><article className="communication-record" key={message.id}><div><strong>{label(message.template_key??"application email")}</strong><span className={`status status-${message.status}`}>{label(message.status)}</span></div><small>{new Date(message.created_at).toLocaleString()}{message.sent_at?` · Sent ${new Date(message.sent_at).toLocaleString()}`:""}</small>{message.last_error_safe&&<p className="error-text">{message.last_error_safe}</p>}</article>):<p className="muted">No tracked emails are connected to this application yet.</p>}<hr/><h3>Correction requests</h3>{requests.length?requests.map(request=><article className="communication-record" key={request.id}><div><strong>{request.resolved_at?"Student responded":"Waiting on student"}</strong><span>{new Date(request.created_at).toLocaleString()}</span></div><p>{request.item}</p>{request.due_at&&<small>Requested by {new Date(request.due_at).toLocaleString()}</small>}{request.response&&<div className="notice"><strong>Student response</strong><p>{request.response}</p></div>}</article>):<p className="muted">No correction requests have been sent.</p>}</section>
      <section className="card"><div className="eyebrow">Audit trail</div><h3>Status and activity</h3>{history.length?<ol className="timeline">{history.map((item,index)=><li key={`${item.created_at}-${index}`}><strong>{label(item.new_status)}</strong><span>{new Date(item.created_at).toLocaleString()}</span>{item.reason&&<p>{item.reason}</p>}{item.applicant_note&&<div className="notice">Student message: {item.applicant_note}</div>}</li>)}</ol>:<p className="muted">No status changes have been recorded.</p>}</section>
    </div>

    <aside>{canManage&&<>
      <section className="card" id="email-student"><div className="eyebrow">Email this student</div><h3>Send an update now</h3><p className="muted">Choose a prepared message or write your own. Sending an email does not change the application status or decision.</p><div className="application-email-presets">{[{key:"received",label:"Confirm receipt"},{key:"reviewing",label:"Still under review"},{key:"more_time",label:"Review needs more time"},{key:"portal",label:"Check the portal"}].map(item=><form action={sendApplicationEmail} key={item.key}><input type="hidden" name="application_id" value={id}/><input type="hidden" name="preset" value={item.key}/><button className="button outline">{item.label}</button></form>)}</div><details><summary>Write a custom email</summary><form action={sendApplicationEmail} className="stack"><input type="hidden" name="application_id" value={id}/><label>Subject<input name="subject" maxLength={160} required placeholder="Application update from Esther Funds Foundation"/></label><label>Message<textarea name="message" maxLength={4000} rows={7} required placeholder="Write the message the student should receive..."/></label><button className="button">Queue custom email</button></form></details><p className="muted"><small>The applicant receives a secure portal button and can reply to nationals@estherfundsinc.org. Delivery appears in the Email delivery section.</small></p></section>
      <section className="card workflow-card"><div className="eyebrow">Next action</div><h3>Application workflow</h3>
        {a.status==="applied"&&<><p>Open this submission for formal review. The student receives one “under review” update.</p><form action={transitionApplication} className="stack"><input type="hidden" name="application_id" value={id}/><input type="hidden" name="new_status" value="review_by_admin"/><input type="hidden" name="reason" value="Application opened for administrative review"/><button className="button">Start review</button></form></>}
        {a.status==="review_by_admin"&&<div className="decision-actions">
          <details open><summary>Request a correction or upload</summary><p className="muted">Creates a visible task in the student portal, reopens editing/uploads, and sends one email.</p><form action={requestInformation} className="stack"><input type="hidden" name="application_id" value={id}/><textarea name="item" required placeholder="Exactly what needs to be corrected or uploaded"/><label>Reply deadline (optional)<input name="due_at" type="datetime-local"/></label><button className="button outline">Send correction request</button></form></details>
          <details><summary>Approve application</summary><p className="muted">Records an audited approval and automatically sends a secure acceptance letter. Award amount and payment remain separate.</p><form action={transitionApplication} className="stack"><input type="hidden" name="application_id" value={id}/><input type="hidden" name="new_status" value="approved"/><textarea name="reason" required placeholder="Private approval basis"/><textarea name="applicant_note" placeholder="Optional personalized acceptance message"/><label>Type APPROVE to confirm<input name="confirmation" required autoComplete="off"/></label><button className="button">Approve and send letter</button></form></details>
          <details className="danger-action"><summary>Deny application</summary><p className="muted">The private reason stays internal. The student receives the compassionate explanation below.</p><form action={transitionApplication} className="stack"><input type="hidden" name="application_id" value={id}/><input type="hidden" name="new_status" value="denied"/><textarea name="reason" required placeholder="Private decision basis"/><textarea name="applicant_note" required placeholder="Clear, compassionate explanation for the student"/><label>Type DENY to confirm<input name="confirmation" required autoComplete="off"/></label><button className="button danger">Deny and send decision</button></form></details>
        </div>}
        {a.status==="additional_information_needed"&&<><div className="notice"><strong>Waiting on the student.</strong><p>The student can edit answers, upload files, and respond securely. A submitted response automatically returns the application to review.</p></div><details><summary>Return to review manually</summary><form action={transitionApplication} className="stack"><input type="hidden" name="application_id" value={id}/><input type="hidden" name="new_status" value="review_by_admin"/><textarea name="reason" required placeholder="Why review can resume"/><textarea name="applicant_note" placeholder="Optional note for the student"/><button className="button outline">Return to review</button></form></details></>}
        {a.status==="approved"&&<><div className="notice success-text"><strong>Application approved.</strong><p>The secure acceptance letter is available now. Issue award details separately only after the amount and conditions are verified.</p></div><Link className="button" href={`/applications/${id}/acceptance-letter`}>Open acceptance letter</Link></>}
        {a.status==="denied"&&<div className="notice"><strong>Decision recorded.</strong><p>The student’s decision notice was queued and the private basis remains in the audit record.</p></div>}
        {["approved","denied","withdrawn"].includes(a.status)&&<details><summary>Archive completed record</summary><form action={transitionApplication} className="stack"><input type="hidden" name="application_id" value={id}/><input type="hidden" name="new_status" value="archived"/><textarea name="reason" required placeholder="Private archive reason"/><button className="button outline">Archive</button></form></details>}
      </section>

      <section className="card"><h3>Reviewer assignment</h3><form action={assignReviewer} className="stack"><input type="hidden" name="application_id" value={id}/><select name="reviewer_id" required defaultValue=""><option value="" disabled>Select reviewer</option>{reviewerRoles?.map(item=>{const p=item.profiles as unknown as Profile;return <option value={item.user_id} key={`${item.user_id}-${item.role}`}>{p?.legal_name??p?.primary_email??"Staff member"} · {label(item.role)}</option>})}</select><button className="button outline">Assign reviewer</button></form>{assignments?.map(item=>{const review=(item.reviews as unknown as Array<{locked_at:string|null}>)?.[0];return <p key={item.id}><strong>Assigned</strong> · {item.conflict_disclosed?(item.has_conflict?"Conflict disclosed":"Conflict cleared"):"Awaiting disclosure"} · {review?.locked_at?"Review submitted":"Review pending"}</p>})}</section>

      {a.status==="approved"&&<section className="card"><div className="eyebrow">Separate financial step</div><h3>Issue award details</h3><form action={recordAward} className="stack"><input type="hidden" name="application_id" value={id}/><label>Amount<input name="amount" type="number" min="1" step="0.01" required defaultValue={award?.amount}/></label><label>Acceptance deadline<input name="acceptance_deadline" type="date" required defaultValue={award?.acceptance_deadline??""}/></label><label>Planned payment date<input name="scheduled_date" type="date" defaultValue={award?.scheduled_date??""}/></label><textarea name="conditions" placeholder="Award conditions or instructions" defaultValue={award?.conditions??""}/><button className="button">Save and notify student</button></form>{award&&<p className="muted">{award.accepted_at?`Accepted ${new Date(award.accepted_at).toLocaleString()}`:`Status: ${award.disbursement_status??"pending"}`}</p>}</section>}

      <section className="card"><h3>Private notes</h3><form action={addInternalNote} className="stack"><input type="hidden" name="application_id" value={id}/><textarea name="body" required placeholder="Never visible to the applicant"/><button className="button outline">Add private note</button></form>{notes.map(note=><blockquote key={note.id}>{note.body}<footer>— {note.profiles?.legal_name??"EFF staff"}, {new Date(note.created_at).toLocaleDateString()}</footer></blockquote>)}</section>

      <details className="card"><summary>Correct an accidental status</summary><p className="muted">This is only for correcting staff error. It preserves the previous decision, actor, reason, and timestamp.</p><form action={correctStatus} className="stack"><input type="hidden" name="application_id" value={id}/><select name="new_status" required defaultValue=""><option value="" disabled>Correct status to…</option>{["applied","review_by_admin","additional_information_needed","approved","denied","withdrawn"].map(status=><option key={status} value={status}>{label(status)}</option>)}</select><textarea name="reason" required placeholder="Why this correction is necessary"/><textarea name="applicant_note" placeholder="Message visible to applicant"/><button className="button outline">Record correction</button></form></details>
    </>}</aside>
    </div>
  </div></main>;
}
