import Link from "next/link";
import {notFound} from "next/navigation";
import {requireStaff} from "@/lib/auth/staff";
import {addInternalNote,assignReviewer,recordAward,requestInformation,transitionApplication} from "./actions";

type Profile={legal_name:string|null;primary_email:string|null;institution:string|null};
type Answer={question_key:string;value:unknown};
type Doc={id:string;kind:string;filename:string;storage_path:string};
type History={new_status:string;reason:string|null;applicant_note:string|null;created_at:string};
type Note={id:string;body:string;created_at:string;profiles:{legal_name:string|null}};
type Request={id:string;item:string;response:string|null;resolved_at:string|null};
type Decision={decision:string;internal_reason:string;applicant_explanation:string|null;confirmed_at:string};
type Award={amount:number;conditions:string|null;acceptance_deadline:string|null;accepted_at:string|null;disbursement_status:string|null;scheduled_date:string|null};

export default async function AdminApplication({params}:{params:Promise<{id:string}>}) {
  const {id}=await params;const {supabase,roles}=await requireStaff();
  const {data:a}=await supabase.from("applications").select("id,status,submitted_at,profiles!applications_applicant_id_fkey(*),application_answers(question_key,value),documents(id,kind,filename,storage_path),status_history(previous_status,new_status,reason,applicant_note,created_at),internal_notes(id,body,created_at,profiles!internal_notes_author_id_fkey(legal_name)),information_requests(id,item,due_at,response,resolved_at,created_at),decisions(decision,internal_reason,applicant_explanation,confirmed_at),awards(id,amount,conditions,acceptance_deadline,accepted_at,disbursement_status,scheduled_date,actual_date),program_cycles(name,programs(name))").eq("id",id).single();
  if(!a)notFound();
  const canManage=roles.some(item=>["program_admin","super_admin"].includes(item.role));
  const [{data:reviewerRoles},{data:assignments}]=canManage?await Promise.all([supabase.from("user_roles").select("user_id,role,profiles!user_roles_user_id_fkey(legal_name,primary_email)").in("role",["reviewer","program_admin","super_admin"]),supabase.from("review_assignments").select("id,reviewer_id,conflict_disclosed,has_conflict,assigned_at,reviews(scores,notes,locked_at)").eq("application_id",id)]):[{data:[]},{data:[]}];
  const profile=a.profiles as unknown as Profile;const answers=(a.application_answers as unknown as Answer[])??[];const rawDocs=(a.documents as unknown as Doc[])??[];const history=(a.status_history as unknown as History[])??[];const notes=(a.internal_notes as unknown as Note[])??[];const requests=(a.information_requests as unknown as Request[])??[];const decision=(a.decisions as unknown as Decision[])?.[0];const award=(a.awards as unknown as Award[])?.[0];
  const docs=await Promise.all(rawDocs.map(async doc=>{const {data}=await supabase.storage.from("application-documents").createSignedUrl(doc.storage_path,300);return {...doc,url:data?.signedUrl??null}}));
  return <main className="section white"><div className="shell admin-detail"><Link href="/admin/applications" className="card-link">← Applications</Link><div className="section-head"><div><div className="eyebrow">{a.status.replaceAll("_"," ")}</div><h2>{profile.legal_name??"Applicant"}</h2><p className="muted">{profile.primary_email} · {profile.institution} · Application {a.id}</p></div>{a.submitted_at&&<strong>Submitted {new Date(a.submitted_at).toLocaleString()}</strong>}</div><div className="admin-columns"><div>
    <section className="card"><h3>Application answers</h3><dl className="answer-list">{answers.sort((x,y)=>x.question_key.localeCompare(y.question_key)).map(item=><div key={item.question_key}><dt>{item.question_key.replaceAll("_"," ")}</dt><dd>{String(item.value??"—")}</dd></div>)}</dl></section>
    <section className="card"><h3>Documents</h3>{docs.length?docs.map(doc=><div className="document-row" key={doc.id}><span>{doc.kind.replaceAll("_"," ")}</span>{doc.url?<a className="card-link" href={doc.url} target="_blank" rel="noreferrer">Open {doc.filename}</a>:<strong>{doc.filename}</strong>}</div>):<p className="muted">No documents attached.</p>}</section>
    {decision&&<section className="card"><h3>Recorded decision</h3><p><strong>{decision.decision}</strong> · {new Date(decision.confirmed_at).toLocaleString()}</p><p>Internal basis: {decision.internal_reason}</p><p className="notice">Applicant message: {decision.applicant_explanation||"No message recorded."}</p></section>}
    <section className="card"><h3>Status and activity</h3><ol className="timeline">{history.map((item,index)=><li key={`${item.created_at}-${index}`}><strong>{item.new_status.replaceAll("_"," ")}</strong><span>{new Date(item.created_at).toLocaleString()}</span>{item.reason&&<p>{item.reason}</p>}{item.applicant_note&&<p className="notice">Applicant message: {item.applicant_note}</p>}</li>)}</ol></section>
  </div><aside>{canManage&&<>
    <section className="card"><h3>Assign reviewer</h3><form action={assignReviewer} className="stack"><input type="hidden" name="application_id" value={id}/><select name="reviewer_id" required defaultValue=""><option value="" disabled>Select reviewer</option>{reviewerRoles?.map(item=>{const p=item.profiles as unknown as Profile;return <option value={item.user_id} key={`${item.user_id}-${item.role}`}>{p?.legal_name??p?.primary_email??"Staff member"} · {item.role.replaceAll("_"," ")}</option>})}</select><button className="button outline">Assign reviewer</button></form>{assignments?.map(item=>{const review=(item.reviews as unknown as Array<{locked_at:string|null}>)?.[0];return <p key={item.id}><strong>Assigned</strong> · {item.conflict_disclosed?(item.has_conflict?"Conflict disclosed":"Conflict cleared"):"Awaiting disclosure"} · {review?.locked_at?"Review submitted":"Review pending"}</p>})}</section>
    <section className="card"><h3>Change status</h3><form action={transitionApplication} className="stack"><input type="hidden" name="application_id" value={id}/><select name="new_status" required defaultValue=""><option value="" disabled>Select next status</option>{["review_by_admin","additional_information_needed","approved","denied","withdrawn","archived"].map(status=><option key={status} value={status}>{status.replaceAll("_"," ")}</option>)}</select><textarea name="reason" required placeholder="Private reason and decision basis"/><textarea name="applicant_note" placeholder="Compassionate message visible to applicant"/><button className="button">Confirm status change</button></form></section>
    {a.status==="approved"&&<section className="card"><h3>Issue award</h3><form action={recordAward} className="stack"><input type="hidden" name="application_id" value={id}/><label>Amount<input name="amount" type="number" min="1" step="0.01" required defaultValue={award?.amount}/></label><label>Acceptance deadline<input name="acceptance_deadline" type="date" required defaultValue={award?.acceptance_deadline??""}/></label><label>Planned payment date<input name="scheduled_date" type="date" defaultValue={award?.scheduled_date??""}/></label><textarea name="conditions" placeholder="Award conditions or instructions" defaultValue={award?.conditions??""}/><button className="button">Save award</button></form>{award&&<p className="muted">{award.accepted_at?`Accepted ${new Date(award.accepted_at).toLocaleString()}`:`Status: ${award.disbursement_status??"pending"}`}</p>}</section>}
    <section className="card"><h3>Request information</h3><form action={requestInformation} className="stack"><input type="hidden" name="application_id" value={id}/><textarea name="item" required placeholder="Exactly what is needed"/><label>Response deadline<input name="due_at" type="datetime-local"/></label><button className="button outline">Send request</button></form>{requests.map(request=><p key={request.id}><strong>{request.resolved_at?"Resolved":"Open"}:</strong> {request.item}{request.response&&<><br/><small>Response: {request.response}</small></>}</p>)}</section>
    <section className="card"><h3>Private notes</h3><form action={addInternalNote} className="stack"><input type="hidden" name="application_id" value={id}/><textarea name="body" required placeholder="Never visible to the applicant"/><button className="button outline">Add note</button></form>{notes.map(note=><blockquote key={note.id}>{note.body}<footer>— {note.profiles?.legal_name??"EFF staff"}, {new Date(note.created_at).toLocaleDateString()}</footer></blockquote>)}</section>
  </>}</aside></div></div></main>;
}
