"use server";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import {safeInternalPath} from "@/lib/security";

const safeNext=(value:FormDataEntryValue|null)=>safeInternalPath(value);
export async function signIn(formData:FormData){const supabase=await createClient();const email=String(formData.get("email")??"").trim();const password=String(formData.get("password")??"");const next=safeNext(formData.get("next"));const {error}=await supabase.auth.signInWithPassword({email,password});if(error)redirect(`/sign-in?error=${encodeURIComponent(error.message)}&next=${encodeURIComponent(next)}`);redirect(next);}
export async function signUp(formData:FormData){const supabase=await createClient();const legalName=String(formData.get("legalName")??"").trim();const preferredName=String(formData.get("preferredName")??"").trim();const email=String(formData.get("email")??"").trim();const password=String(formData.get("password")??"");const next=safeNext(formData.get("next"));if(legalName.length<2||password.length<10)redirect(`/sign-up?error=Please+enter+your+legal+name+and+a+password+of+at+least+10+characters.&next=${encodeURIComponent(next)}`);const {error}=await supabase.auth.signUp({email,password,options:{data:{legal_name:legalName,preferred_name:preferredName},emailRedirectTo:`${process.env.NEXT_PUBLIC_APP_URL}/auth/callback?next=${encodeURIComponent(next)}`}});if(error)redirect(`/sign-up?error=${encodeURIComponent(error.message)}&next=${encodeURIComponent(next)}`);redirect(`/sign-in?message=${encodeURIComponent("Check your email to verify your account, then sign in.")}&next=${encodeURIComponent(next)}`);}
export async function requestPasswordReset(formData:FormData){const supabase=await createClient();const email=String(formData.get("email")??"").trim();await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${process.env.NEXT_PUBLIC_APP_URL}/auth/callback?next=/reset-password`});redirect(`/forgot-password?message=${encodeURIComponent("If that email has an account, a secure reset link is on its way.")}`);}
export async function updatePassword(formData:FormData){const supabase=await createClient();const password=String(formData.get("password")??"");if(password.length<10)redirect("/reset-password?error=Password+must+be+at+least+10+characters.");const {error}=await supabase.auth.updateUser({password});if(error)redirect(`/reset-password?error=${encodeURIComponent(error.message)}`);redirect("/dashboard?message=Password+updated.");}
export async function signOut(){const supabase=await createClient();await supabase.auth.signOut();redirect("/");}
