import type {Metadata} from "next";
import Link from "next/link";
import {AlertTriangle,ArrowRight,BookOpenCheck,Bus,FileQuestion,HeartHandshake,Home,Phone,ReceiptText,Utensils} from "lucide-react";

export const metadata:Metadata={title:"Student Help Center",description:"Fast, trusted help for FAFSA problems, school balances, emergency expenses, and basic needs."};
const external=(href:string,label:string)=><a className="resource-link" href={href} target="_blank" rel="noopener noreferrer">{label}<ArrowRight size={16}/></a>;

export default function Resources(){return <main>
  <section className="resource-hero"><div className="shell resource-hero-grid"><div><div className="eyebrow">You do not have to figure this out alone</div><h1>I need help <span>right now.</span></h1><p>Choose what is putting your education at risk. We will show you the fastest trusted next steps, what to ask for, and where Esther Funds Foundation may be able to walk beside you.</p><div className="hero-actions"><a className="button light" href="#choose">Find my next step</a><Link className="button lavender" href="/programs/name-your-need">Name Your Need</Link></div></div><div className="resource-promise"><strong>Start with the need—not the paperwork.</strong><p>No shame. No judgment. Clear steps, official resources, and compassionate support.</p><small>EFF does not guarantee outside aid or emergency funding. We help you identify and pursue legitimate options.</small></div></div></section>
  <section className="section" id="choose"><div className="shell"><div className="section-head"><div><div className="eyebrow">Choose your situation</div><h2>What is happening?</h2></div><p>Pick the closest match. If several apply, start with the issue that could make you lose housing, food, transportation, enrollment, or safety first.</p></div><div className="resource-choice-grid">
    <a className="resource-choice" href="#fafsa"><FileQuestion/><strong>My FAFSA is stuck or confusing</strong><span>Contributor, correction, identity, dependency, missing aid, or changed income</span></a>
    <a className="resource-choice" href="#balance"><ReceiptText/><strong>I owe my school a balance</strong><span>Registration hold, dropped classes, transcript issue, or risk of stopping out</span></a>
    <a className="resource-choice urgent" href="#emergency"><AlertTriangle/><strong>I need emergency money</strong><span>Unexpected expense, medical need, car repair, childcare, technology, or crisis</span></a>
    <a className="resource-choice" href="#basic-needs"><Home/><strong>I need food, housing, or transportation</strong><span>Local help, benefits, campus pantry, shelter, utilities, or a ride</span></a>
    <a className="resource-choice" href="#support"><HeartHandshake/><strong>I am overwhelmed and need a person</strong><span>EFF support, crisis lines, encouragement, and a simple plan for today</span></a>
  </div></div></section>
  <section className="section white" id="fafsa"><div className="shell resource-section"><div><div className="resource-icon"><FileQuestion/></div><div className="eyebrow">FAFSA rescue path</div><h2>When financial aid is stuck</h2><p className="lead">Do not guess or change tax years. Identify the exact status, correct what can be corrected online, and take income changes or unusual circumstances to your school’s financial-aid office.</p></div><div className="resource-steps">
    <div><b>1</b><span><strong>Open your FAFSA Submission Summary.</strong> Check processing status, missing signatures or consent, contributor problems, and next-step messages.</span></div>
    <div><b>2</b><span><strong>Make allowable corrections.</strong> Contact information, typos, schools, signatures, and a contributor’s own section may be corrected online after processing.</span></div>
    <div><b>3</b><span><strong>If income changed, request “professional judgment.”</strong> Finish FAFSA using the required tax year, then ask your school for a special-circumstances aid adjustment.</span></div>
    <div><b>4</b><span><strong>If parent contact is unsafe or impossible, say “unusual circumstances.”</strong> Ask the school about a dependency override and accepted third-party documentation.</span></div>
  </div><div className="resource-actions">{external("https://studentaid.gov/h/apply-for-aid/fafsa","Open the official FAFSA")}{external("https://studentaid.gov/articles/things-after-fafsa/","FAFSA correction guidance")}{external("https://studentaid.gov/articles/financial-aid-not-enough/","When aid is not enough")}<a className="resource-link phone" href="tel:18004333243"><Phone size={16}/>Call Federal Student Aid: 1-800-433-3243</a></div><div className="resource-docs"><strong>Gather before contacting your school:</strong><span>Student ID · FAFSA Submission Summary · aid offer · screenshots/error text · recent pay stubs or termination letter · medical or other supporting bills · a short timeline of what changed</span></div></div></section>
  <section className="section" id="balance"><div className="shell resource-section"><div><div className="resource-icon"><ReceiptText/></div><div className="eyebrow">Stay-enrolled plan</div><h2>When a school balance blocks you</h2><p className="lead">A balance may include an aid delay, verification hold, changed enrollment, housing charge, lost scholarship, or unmet need. Ask the school to identify every line before choosing a solution.</p></div><div className="resource-callout"><strong>Use these exact words:</strong><p>“I am at risk of stopping out because of a balance. Please review my account for pending aid, verification issues, professional judgment, emergency completion grants, institutional grants, payment-plan options, and any hold that can be temporarily lifted while assistance is reviewed.”</p></div><div className="resource-two-col"><div className="card"><h3>Contact in this order</h3><ol><li>Financial-aid office</li><li>Student accounts or bursar</li><li>Dean of students/basic-needs office</li><li>Retention or student-success office</li><li>Your academic adviser</li></ol></div><div className="card"><h3>Ask for these options</h3><ul><li>Emergency or completion grant</li><li>Professional-judgment review</li><li>Short-term institutional loan</li><li>Payment plan or due-date extension</li><li>Late-fee waiver</li><li>Pending-aid or registration-hold review</li></ul></div></div><div className="resource-actions"><Link className="resource-link primary" href="/programs/name-your-need">Apply for EFF Name Your Need<ArrowRight size={16}/></Link>{external("https://www.nassgapsurvey.com/","Find state financial-aid programs")}</div></div></section>
  <section className="section white" id="emergency"><div className="shell resource-section"><div><div className="resource-icon"><AlertTriangle/></div><div className="eyebrow">Fast emergency pathway</div><h2>When one expense could stop everything</h2><p className="lead">Start with the smallest amount and fastest action that keeps you safe and enrolled. Avoid payday loans, title loans, application fees for “grants,” and anyone promising guaranteed government money.</p></div><div className="resource-two-col"><div className="card emergency-card"><h3>Within the next hour</h3><ul><li>Write the exact amount, deadline, and consequence.</li><li>Save the bill, estimate, notice, or screenshot.</li><li>Call your school’s dean of students and ask for emergency aid.</li><li>Dial 211 for verified local help.</li><li>Submit EFF’s Name Your Need application if eligible.</li></ul></div><div className="card"><h3>Common needs to name clearly</h3><div className="need-tags"><span>Past-due balance</span><span>Rent</span><span>Food</span><span>Utilities</span><span>Transportation</span><span>Car repair</span><span>Childcare</span><span>Laptop</span><span>Medical cost</span><span>Books</span></div></div></div><div className="resource-actions"><Link className="resource-link primary" href="/programs/name-your-need">Tell EFF what you need<ArrowRight size={16}/></Link>{external("https://www.211.org/","Find immediate local help through 211")}{external("https://www.usa.gov/benefits","Find government benefits")}</div></div></section>
  <section className="section" id="basic-needs"><div className="shell resource-section"><div><div className="resource-icon"><Home/></div><div className="eyebrow">Basic needs are education needs</div><h2>Food, housing, utilities, health, and transportation</h2><p className="lead">Use both campus and community support. Ask your school whether it has a basic-needs center, food pantry, meal-swipe program, emergency housing, transportation help, childcare support, or benefits navigator.</p></div><div className="resource-choice-grid compact"><div className="resource-mini"><Utensils/><strong>Food</strong><span>Campus pantry, meal swipes, SNAP screening, local food banks</span></div><div className="resource-mini"><Home/><strong>Housing & utilities</strong><span>Emergency shelter, rent assistance, eviction prevention, utility relief</span></div><div className="resource-mini"><Bus/><strong>Transportation</strong><span>Campus passes, local ride help, gas cards, repair assistance</span></div><div className="resource-mini"><BookOpenCheck/><strong>School essentials</strong><span>Books, laptop lending, internet benefits, childcare, work-study</span></div></div><div className="resource-actions">{external("https://www.211.org/","Call or search 211")}{external("https://www.usa.gov/benefits","Explore official benefit programs")}{external("https://swipehunger.org/","Explore campus food support")}</div></div></section>
  <section className="section white" id="support"><div className="shell resource-support"><div><div className="eyebrow">A person, not another portal</div><h2>You deserve support with dignity.</h2><p>Tell the EFF national team what is happening, what deadline you face, and the best safe way to reach you. We can help organize next steps and identify resources, even when EFF cannot directly fund the full need.</p><div className="hero-actions"><a className="button" href="mailto:nationals@estherfundsinc.org?subject=Student%20Help%20Request">Email the EFF national team</a><Link className="button outline" href="/dashboard">Return to my portal</Link></div></div><aside className="crisis-card"><strong>If you may be in immediate danger</strong><p>Call 911. For suicidal thoughts, emotional distress, or a mental-health crisis, call or text 988. For local shelter, food, and essential-needs referrals, dial 211.</p><p><a href="tel:988">Call or text 988</a> · <a href="tel:211">Call 211</a></p></aside></div></section>
</main>}
