export type StateResource={code:string;name:string;aidName:string;aidUrl:string};

export const stateResources:StateResource[]=[
  {code:"AL",name:"Alabama",aidName:"Alabama Commission on Higher Education",aidUrl:"https://www.ache.edu/index.php/student-information/"},
  {code:"AK",name:"Alaska",aidName:"Alaska Commission on Postsecondary Education",aidUrl:"https://acpe.alaska.gov/FINANCIAL-AID"},
  {code:"AZ",name:"Arizona",aidName:"Arizona state financial aid",aidUrl:"https://highered.az.gov/financial-aid"},
  {code:"AR",name:"Arkansas",aidName:"Arkansas Division of Higher Education",aidUrl:"https://sams.adhe.edu/"},
  {code:"CA",name:"California",aidName:"California Student Aid Commission",aidUrl:"https://www.csac.ca.gov/"},
  {code:"CO",name:"Colorado",aidName:"Colorado Department of Higher Education",aidUrl:"https://cdhe.colorado.gov/students/preparing-for-college/financial-aid"},
  {code:"CT",name:"Connecticut",aidName:"Connecticut Office of Higher Education",aidUrl:"https://portal.ct.gov/ohe/knowledge-base/articles/students-family/financial-aid"},
  {code:"DE",name:"Delaware",aidName:"Delaware Higher Education Office",aidUrl:"https://education.delaware.gov/families/college-career-life/college-scholarship-financial-aid/"},
  {code:"FL",name:"Florida",aidName:"Florida Student Scholarship & Grant Programs",aidUrl:"https://www.floridastudentfinancialaidsg.org/"},
  {code:"GA",name:"Georgia",aidName:"GAfutures",aidUrl:"https://www.gafutures.org/"},
  {code:"HI",name:"Hawaii",aidName:"University of Hawaii financial aid",aidUrl:"https://www.hawaii.edu/tuition/financial-aid/"},
  {code:"ID",name:"Idaho",aidName:"Idaho State Board scholarships",aidUrl:"https://boardofed.idaho.gov/scholarships/"},
  {code:"IL",name:"Illinois",aidName:"Illinois Student Assistance Commission",aidUrl:"https://www.isac.org/"},
  {code:"IN",name:"Indiana",aidName:"Indiana ScholarTrack",aidUrl:"https://scholartrack.che.in.gov/"},
  {code:"IA",name:"Iowa",aidName:"Iowa College Aid",aidUrl:"https://iowacollegeaid.gov/"},
  {code:"KS",name:"Kansas",aidName:"Kansas Board of Regents aid",aidUrl:"https://www.kansasregents.org/scholarships_and_grants"},
  {code:"KY",name:"Kentucky",aidName:"Kentucky Higher Education Assistance Authority",aidUrl:"https://www.kheaa.com/"},
  {code:"LA",name:"Louisiana",aidName:"Louisiana Office of Student Financial Assistance",aidUrl:"https://mylosfa.la.gov/"},
  {code:"ME",name:"Maine",aidName:"Finance Authority of Maine",aidUrl:"https://www.famemaine.com/education/"},
  {code:"MD",name:"Maryland",aidName:"Maryland Higher Education Commission",aidUrl:"https://mhec.maryland.gov/preparing/Pages/FinancialAid/index.aspx"},
  {code:"MA",name:"Massachusetts",aidName:"Massachusetts Office of Student Financial Assistance",aidUrl:"https://www.mass.edu/osfa/home/home.asp"},
  {code:"MI",name:"Michigan",aidName:"MI Student Aid",aidUrl:"https://www.michigan.gov/mistudentaid"},
  {code:"MN",name:"Minnesota",aidName:"Minnesota Office of Higher Education",aidUrl:"https://ohe.mn.gov/paying-college"},
  {code:"MS",name:"Mississippi",aidName:"Mississippi Financial Aid",aidUrl:"https://www.msfinancialaid.org/"},
  {code:"MO",name:"Missouri",aidName:"Missouri student financial assistance",aidUrl:"https://dhewd.mo.gov/ppc/grants/"},
  {code:"MT",name:"Montana",aidName:"Montana University System aid",aidUrl:"https://www.mus.edu/Prepare/Pay/index.html"},
  {code:"NE",name:"Nebraska",aidName:"Nebraska Coordinating Commission",aidUrl:"https://ccpe.nebraska.gov/financial-aid"},
  {code:"NV",name:"Nevada",aidName:"Nevada financial aid and scholarships",aidUrl:"https://nvigate.gov/"},
  {code:"NH",name:"New Hampshire",aidName:"NH Higher Education Assistance Foundation",aidUrl:"https://www.nhheaf.org/"},
  {code:"NJ",name:"New Jersey",aidName:"New Jersey Higher Education Student Assistance Authority",aidUrl:"https://www.hesaa.org/"},
  {code:"NM",name:"New Mexico",aidName:"New Mexico Higher Education Department",aidUrl:"https://hed.nm.gov/free-college-for-new-mexico"},
  {code:"NY",name:"New York",aidName:"New York Higher Education Services Corporation",aidUrl:"https://www.hesc.ny.gov/"},
  {code:"NC",name:"North Carolina",aidName:"College Foundation of North Carolina",aidUrl:"https://www.cfnc.org/pay-for-college/"},
  {code:"ND",name:"North Dakota",aidName:"North Dakota University System aid",aidUrl:"https://ndus.edu/paying-for-college/"},
  {code:"OH",name:"Ohio",aidName:"Ohio Department of Higher Education",aidUrl:"https://highered.ohio.gov/students/pay-for-college"},
  {code:"OK",name:"Oklahoma",aidName:"OKcollegestart",aidUrl:"https://www.okcollegestart.org/"},
  {code:"OR",name:"Oregon",aidName:"Oregon Student Aid",aidUrl:"https://oregonstudentaid.gov/"},
  {code:"PA",name:"Pennsylvania",aidName:"Pennsylvania Higher Education Assistance Agency",aidUrl:"https://www.pheaa.org/"},
  {code:"RI",name:"Rhode Island",aidName:"Rhode Island Office of the Postsecondary Commissioner",aidUrl:"https://riopc.edu/page/financial-aid/"},
  {code:"SC",name:"South Carolina",aidName:"South Carolina Commission on Higher Education",aidUrl:"https://che.sc.gov/students-families-and-military/scholarships-and-grants-sc-residents"},
  {code:"SD",name:"South Dakota",aidName:"Our Dakota Dreams",aidUrl:"https://ourdakotadreams.com/paying-for-college/"},
  {code:"TN",name:"Tennessee",aidName:"College for Tennessee",aidUrl:"https://www.collegefortn.org/"},
  {code:"TX",name:"Texas",aidName:"Texas Higher Education Coordinating Board",aidUrl:"https://www.highered.texas.gov/our-work/empowering-our-students/financial-aid/"},
  {code:"UT",name:"Utah",aidName:"Utah System of Higher Education aid",aidUrl:"https://ushe.edu/state-scholarships-aid/"},
  {code:"VT",name:"Vermont",aidName:"Vermont Student Assistance Corporation",aidUrl:"https://www.vsac.org/"},
  {code:"VA",name:"Virginia",aidName:"State Council of Higher Education for Virginia",aidUrl:"https://www.schev.edu/financial-aid"},
  {code:"WA",name:"Washington",aidName:"Washington Student Achievement Council",aidUrl:"https://wsac.wa.gov/sfa-overview"},
  {code:"WV",name:"West Virginia",aidName:"College for West Virginia",aidUrl:"https://www.cfwv.com/"},
  {code:"WI",name:"Wisconsin",aidName:"Wisconsin Higher Educational Aids Board",aidUrl:"https://heab.state.wi.us/"},
  {code:"WY",name:"Wyoming",aidName:"Wyoming college aid resources",aidUrl:"https://edu.wyoming.gov/for-students/"}
];
