"use client";
import {useMemo,useState} from "react";
import {Calculator,MapPinned} from "lucide-react";
import {stateResources} from "./states";

const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value||0);
const numberValue=(value:string)=>Math.max(0,Number(value)||0);

export function StateResourceDirectory(){
  const [state,setState]=useState("FL");
  const selected=stateResources.find(item=>item.code===state)!;
  return <section className="state-tool" aria-labelledby="state-help-title"><div className="tool-heading"><MapPinned/><div><div className="eyebrow">All 50 states</div><h3 id="state-help-title">Find help where you live and study</h3></div></div><label>Choose your state<select value={state} onChange={event=>setState(event.target.value)}>{stateResources.map(item=><option value={item.code} key={item.code}>{item.name}</option>)}</select></label><div className="state-results"><article><span>College and state aid</span><strong>{selected.aidName}</strong><a href={selected.aidUrl} target="_blank" rel="noopener noreferrer">Open {selected.name} aid resources</a></article><article><span>Food benefits</span><strong>Official USDA SNAP directory</strong><a href="https://www.fns.usda.gov/snap/state-directory" target="_blank" rel="noopener noreferrer">Choose {selected.name} in the SNAP directory</a></article><article><span>Local emergency help</span><strong>Housing, food, utilities, health, and transportation</strong><a href="https://www.211.org/about-us/your-local-211" target="_blank" rel="noopener noreferrer">Find the local 211 serving {selected.name}</a></article><article><span>Government benefits</span><strong>Official benefit programs and eligibility guidance</strong><a href="https://www.usa.gov/benefits" target="_blank" rel="noopener noreferrer">Explore government benefits</a></article></div><p className="tool-note">State programs change. Confirm deadlines and eligibility on the official agency page before relying on an award.</p></section>
}

export function AidGapCalculator(){
  const [values,setValues]=useState({tuition:"",housing:"",grants:"",scholarships:"",loans:"",payments:"",workStudy:""});
  const set=(key:keyof typeof values)=>(value:string)=>setValues(current=>({...current,[key]:value}));
  const result=useMemo(()=>{const tuition=numberValue(values.tuition),housing=numberValue(values.housing),grants=numberValue(values.grants),scholarships=numberValue(values.scholarships),loans=numberValue(values.loans),payments=numberValue(values.payments),workStudy=numberValue(values.workStudy);const billed=tuition+housing;const gift=grants+scholarships;return {billed,gift,netPrice:Math.max(0,billed-gift),gap:Math.max(0,billed-gift-loans-payments),loans,workStudy};},[values]);
  return <section className="aid-calculator" aria-labelledby="gap-title"><div className="tool-heading"><Calculator/><div><div className="eyebrow">Know the real number</div><h3 id="gap-title">Financial-aid gap calculator</h3></div></div><p>Use annual or semester numbers, but do not mix them. Enter aid only if it appears as accepted or pending on your school account.</p><div className="calculator-grid"><MoneyField label="Tuition and required fees" value={values.tuition} setValue={set("tuition")}/><MoneyField label="School-billed housing and meals" value={values.housing} setValue={set("housing")}/><MoneyField label="Grants" value={values.grants} setValue={set("grants")}/><MoneyField label="Scholarships" value={values.scholarships} setValue={set("scholarships")}/><MoneyField label="Accepted student/parent loans" value={values.loans} setValue={set("loans")}/><MoneyField label="Payments already made" value={values.payments} setValue={set("payments")}/><MoneyField label="Work-study offered" value={values.workStudy} setValue={set("workStudy")}/></div><div className="calculator-results"><div><span>School-billed cost</span><strong>{money(result.billed)}</strong></div><div><span>Free aid</span><strong>{money(result.gift)}</strong></div><div><span>Net price before loans</span><strong>{money(result.netPrice)}</strong></div><div className="gap-result"><span>Estimated remaining gap</span><strong>{money(result.gap)}</strong></div></div><div className="calculator-warning"><strong>Important:</strong> Work-study is normally earned through paychecks after you work; it usually does not reduce today&apos;s bill. This estimate cannot see loan fees, pending verification, refunds, or charges outside the fields above. Confirm the exact balance with student accounts.</div></section>
}

function MoneyField({label,value,setValue}:{label:string;value:string;setValue:(value:string)=>void}){return <label>{label}<span className="money-input"><b>$</b><input inputMode="decimal" type="number" min="0" step="1" value={value} onChange={event=>setValue(event.target.value)} placeholder="0"/></span></label>}
