import Link from "next/link";
import {requireAdmin} from "@/lib/auth/staff";
import {createAdminClient} from "@/lib/supabase/admin";

type Query={scope?:string;q?:string;review?:string};
const priorityKeys=["student_accounts","registrar","basic_needs","housing","title_ix","international","student_advocacy","technology"];
export default async function CollegeDirectoryAdmin({searchParams}:{searchParams:Promise<Query>}){
  const query=await searchParams;await requireAdmin();const admin=createAdminClient();const now=new Date().toISOString();
  let request=admin.from("college_directory").select("unitid,name,city,state,hbcu,website,financial_aid_url,source_year,reviewed_at,college_contact_directory(department_key,department_name,contact_url,email,verification_status,verified_at,last_checked_at,next_review_at)").eq("active",true).order("hbcu",{ascending:false}).order("name").limit(1000);
  if(query.scope==="hbcu"||!query.scope)request=request.eq("hbcu",true);if(query.q)request=request.ilike("name",`%${query.q.replaceAll("%","")}%`);
  const {data:schools}=await request;const rows=(schools??[]).map(s=>{const contacts=s.college_contact_directory??[];const verified=contacts.filter(c=>c.verification_status==="verified");const due=contacts.filter(c=>c.next_review_at&&c.next_review_at<=now);const covered=new Set(verified.map(c=>c.department_key));return {...s,contacts,verified,due,missing:priorityKeys.filter(k=>!covered.has(k))};}).filter(s=>query.review==="due"?s.due.length>0:query.review==="missing"?s.missing.length>0:true);
  const verifiedCount=rows.reduce((n,s)=>n+s.verified.length,0),dueCount=rows.reduce((n,s)=>n+s.due.length,0),fullCoverage=rows.filter(s=>s.missing.length===0).length;
  return <main className="section white"><div className="shell"><Link href="/admin" className="card-link">← Command center</Link><div className="section-head"><div><div className="eyebrow">Official national resource map</div><h2>College directory verification</h2><p className="muted">Federal institution records, official school department pages, verification dates, and scheduled rechecks.</p></div><Link className="button outline" href="/resources/student-help">Test student search</Link></div>
    <div className="stats admin-stats"><div className="stat"><strong>{rows.length}</strong><span>schools shown</span></div><div className="stat"><strong>{verifiedCount}</strong><span>verified contacts</span></div><div className="stat"><strong>{fullCoverage}</strong><span>all priority routes</span></div><div className="stat"><strong>{dueCount}</strong><span>reviews due</span></div></div>
    <form className="admin-filter"><input name="q" placeholder="Search institution" defaultValue={query.q}/><select name="scope" defaultValue={query.scope??"hbcu"}><option value="hbcu">HBCUs first</option><option value="all">All institutions</option></select><select name="review" defaultValue={query.review??""}><option value="">All coverage</option><option value="missing">Missing priority routes</option><option value="due">Review due</option></select><button className="button">Filter</button></form>
    <div className="howard-admin-list">{rows.map(s=><article className="card howard-admin-case" key={s.unitid}><div className="howard-admin-head"><div><span className="status">{s.hbcu?"HBCU":"U.S. college"}</span><h3>{s.name}</h3><p>{s.city}, {s.state} · NCES {s.unitid} · IPEDS {s.source_year}</p></div><strong>{s.verified.length}/{priorityKeys.length} priority routes verified</strong></div><div className="resource-actions">{s.website&&<a href={s.website} target="_blank" rel="noreferrer">Official website</a>}{s.financial_aid_url&&<a href={s.financial_aid_url} target="_blank" rel="noreferrer">IPEDS financial aid</a>}</div>{s.missing.length>0&&<p className="muted"><strong>Still needed:</strong> {s.missing.map(x=>x.replaceAll("_"," ")).join(", ")}</p>}<details><summary>View {s.contacts.length} department record(s)</summary><div className="table-wrap"><table><thead><tr><th>Department</th><th>Status</th><th>Contact</th><th>Checked</th><th>Next review</th></tr></thead><tbody>{s.contacts.map(c=><tr key={c.department_key}><td><a href={c.contact_url??"#"} target="_blank" rel="noreferrer">{c.department_name}</a></td><td>{c.verification_status.replaceAll("_"," ")}</td><td>{c.email??"Official page"}</td><td>{new Date(c.last_checked_at).toLocaleDateString()}</td><td className={c.next_review_at<=now?"error-text":""}>{new Date(c.next_review_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></details></article>)}</div>
  </div></main>;
}
