import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {beginOfficialApplication,removeSchool,updateGuidedApplication} from "../actions";

type Institution={id:string;name:string;state_code:string;application_url:string|null;eff_member_status:string;eff_receiver_enabled:boolean};
type Selection={id:string;institution_id:string;admission_term:string;applyall_institutions:Institution|null};
type Guided={institution_id:string;status:string;confirmation_number:string|null;school_specific_notes:string|null;submitted_at:string|null};

export default async function ApplyAllDashboard({searchParams}:{searchParams:Promise<{message?:string}>}){
  const {message}=await searchParams;const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/sign-in?next=%2Fapply-everywhere%2Fdashboard");
  const {data:profile}=await db.from("applyall_profiles").select("id").eq("user_id",user.id).maybeSingle();if(!profile)redirect("/apply-everywhere/start");
  const [{data:rawSelections},{data:rawGuided},{data:commonApp}]=await Promise.all([
    db.from("applyall_school_selections").select("id,institution_id,admission_term,applyall_institutions(id,name,state_code,application_url,eff_member_status,eff_receiver_enabled)").eq("profile_id",profile.id).order("selected_at"),
    db.from("applyall_guided_applications").select("institution_id,status,confirmation_number,school_specific_notes,submitted_at").eq("profile_id",profile.id),
    db.from("applyall_common_applications").select("id,status").eq("profile_id",profile.id).eq("cycle","2027").maybeSingle()
  ]);
  const selections=(rawSelections??[]) as unknown as Selection[];const guided=new Map(((rawGuided??[]) as Guided[]).map(g=>[g.institution_id,g]));
  return <main className="applyall"><section className="applyall-workspace"><div className="shell"><span className="applyall-kicker">Your Future Passport</span><h1>Apply once. Finish each school with confidence.</h1><p className="applyall-lead">EFF organizes your reusable answers. You complete school-specific questions, verification, fees or waivers, certification, and final submission on each university&apos;s official website.</p>
  {message&&<p className="applyall-complete"><strong>{message}</strong></p>}
  <section className="applyall-next"><div><span>Your partnership-free pathway</span><h2>EFF prepares. You review and submit.</h2><ol><li>Complete your reusable EFF application profile</li><li>Open each university&apos;s official application</li><li>Finish its unique questions and student-only checkpoints</li><li>Record the official confirmation number here</li></ol></div></section>
  <div className="hero-actions"><Link className="button" href="/apply-everywhere/application">{commonApp?"Update my reusable profile":"Complete my reusable profile"}</Link><Link className="button outline" href="/apply-everywhere/schools">Select colleges</Link></div>
  <h2 style={{marginTop:"2rem"}}>My application workspace</h2>
  {selections.length?<div className="applyall-review-list">{selections.map(selection=>{const school=selection.applyall_institutions;const track=guided.get(selection.institution_id);const direct=school?.eff_member_status==="ACTIVE"&&school.eff_receiver_enabled;return <article className="card" key={selection.id}><span className="applyall-kicker">{direct?"Direct EFF submission":"Guided official application"}</span><h2>{school?.name}</h2><p>{school?.state_code} · {selection.admission_term}</p><p>{direct?"This college accepts direct application delivery through EFF.":"EFF helps you prepare and track this application. The university website controls the final submission."}</p>
    <div className="hero-actions">{direct?<Link className="button" href="/apply-everywhere/application/review">Review direct submission</Link>:school?.application_url?<form action={beginOfficialApplication}><input type="hidden" name="institutionId" value={selection.institution_id}/><input type="hidden" name="applicationUrl" value={school.application_url}/><button className="button">Open official application</button></form>:<span className="applyall-alert">Official application link is being verified.</span>}</div>
    {!direct&&<form action={updateGuidedApplication}><input type="hidden" name="institutionId" value={selection.institution_id}/><label>Application status<select name="status" defaultValue={track?.status??"NOT_STARTED"}><option value="NOT_STARTED">Not started</option><option value="IN_PROGRESS">In progress</option><option value="ACTION_REQUIRED">Action required</option><option value="SUBMITTED">Submitted to university</option><option value="COMPLETE">University marked complete</option></select></label><label>University confirmation number<input name="confirmationNumber" defaultValue={track?.confirmation_number??""} placeholder="Required when marking submitted"/></label><label>School-specific questions or missing materials<textarea name="notes" rows={4} defaultValue={track?.school_specific_notes??""} placeholder="Essay supplement, transcript, fee waiver, recommendation, portal task…"/></label><button className="button outline">Save application update</button>{track?.submitted_at&&<p><strong>Recorded submitted:</strong> {new Date(track.submitted_at).toLocaleString()}</p>}</form>}
    <details><summary>Before you mark this submitted</summary><ul><li>Review every imported or copied answer</li><li>Complete school-specific essays and questions</li><li>Complete email verification or multifactor authentication yourself</li><li>Choose a fee-waiver option or pay the university directly</li><li>Personally certify and submit on the official website</li><li>Copy the confirmation number into EFF Apply Everywhere</li></ul></details>
    <form action={removeSchool}><input type="hidden" name="selectionId" value={selection.id}/><button className="button outline">Remove school</button></form></article>})}</div>:<div className="card"><p>No colleges selected yet.</p><Link className="button" href="/apply-everywhere/schools">Explore Southern colleges</Link></div>}
  <p className="applyall-fine">EFF does not store university passwords, verification codes, or payment-card information. EFF never claims an application was submitted without a university confirmation recorded by the student.</p></div></section></main>;
}
