import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft,CheckCircle2,ExternalLink,GraduationCap,HeartHandshake,MapPin,ShieldCheck} from "lucide-react";
import {formatSupportAmount,studentInitials} from "@/lib/student-support";
import {getPublicStudentSupportProfile} from "@/lib/student-support-public";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const profile=await getPublicStudentSupportProfile(slug);return profile?{title:`Support ${profile.displayName}`,description:profile.headline}:{title:"Student profile"};}
export default async function StudentSupportDetail({params}:{params:Promise<{slug:string}>}){const{slug}=await params,profile=await getPublicStudentSupportProfile(slug);if(!profile)notFound();const firstName=profile.displayName.split(/\s+/)[0];return <main className="student-profile-page"><section className="section cream"><div className="shell"><Link className="card-link support-back" href="/meet-a-student"><ArrowLeft/> Back to all students</Link><div className="student-profile-layout"><aside><div className="student-detail-photo">{profile.photoUrl?<img src={profile.photoUrl} alt=""/>:<span>{studentInitials(profile.displayName)}</span>}</div><div className="support-verified-box"><ShieldCheck/><div><strong>EFF reviewed profile</strong><span>Consent, redacted documentation, public story, and external destination reviewed.</span></div></div></aside><article className="student-story-card"><div className="eyebrow">Meet a student</div><h1>{profile.displayName}</h1><p className="student-detail-headline">{profile.headline}</p><div className="student-detail-facts"><span><GraduationCap/>{profile.institution}</span>{profile.major&&<span>{profile.major}</span>}{profile.classYear&&<span>{profile.classYear}</span>}{profile.locationText&&<span><MapPin/>{profile.locationText}</span>}</div><div className="student-need-highlight"><small>Verified amount sought</small><strong>{formatSupportAmount(profile.amountNeeded)}</strong><p>{profile.needSummary}</p></div><div className="student-story"><h2>{firstName}’s story</h2>{profile.story.split(/\n+/).filter(Boolean).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div><div className="student-support-actions"><a className="button" href={profile.fundraiserUrl} target="_blank" rel="noopener noreferrer">Support {firstName} directly on {profile.fundraiserPlatform} <ExternalLink/></a><small>You are leaving EFF’s website. Payment terms, fees, receipts, and tax treatment are controlled by the external provider—not EFF.</small></div></article></div></div></section>
 <section className="section white"><div className="shell support-trust-grid"><div><CheckCircle2/><h3>What EFF reviewed</h3><p>Account connection, consent, redacted supporting documentation, public story, and destination.</p></div><div><ShieldCheck/><h3>What approval does not mean</h3><p>EFF does not guarantee future use, donations, enrollment outcomes, or the external platform’s policies.</p></div><div><HeartHandshake/><h3>Support the wider mission</h3><p>Help EFF keep building student-retention resources through a separate gift.</p><a className="card-link" href="https://www.estherfundsfoundation.org" target="_blank" rel="noopener noreferrer">Support Esther Funds Foundation <ExternalLink/></a></div></div></section></main>}
