import type {Metadata} from "next";
import Link from "next/link";
import {ArrowRight,CheckCircle2,ExternalLink,HeartHandshake,Search,ShieldCheck,UserRoundPlus} from "lucide-react";
import {formatSupportAmount,studentInitials} from "@/lib/student-support";
import {listPublicStudentSupportProfiles} from "@/lib/student-support-public";
export const metadata:Metadata={title:"Meet a Student",description:"Meet verified students and continue to their approved external support pages through Esther Funds Foundation."};
export default async function MeetAStudent({searchParams}:{searchParams:Promise<{q?:string}>}){const{q}=await searchParams;const profiles=await listPublicStudentSupportProfiles(q);return <main className="student-directory">
 <section className="support-hero"><div className="shell support-hero-grid"><div><div className="eyebrow light">Every student has a future worth finishing</div><h1>Meet a student.<br/><em>Help remove a barrier.</em></h1><p>EFF gives approved students a trusted place to share their story. Choose a student, read their reviewed profile, and continue to the external support page they provided.</p><div className="support-hero-actions"><Link className="button light" href="#students">Meet the students</Link><Link className="button ghost-light" href="/meet-a-student/apply">Create my student profile</Link></div></div><div className="support-hero-note"><ShieldCheck/><h2>Reviewed before public</h2><p>The national office checks consent, redacted documentation, the public story, and the external destination before a profile appears.</p><span>EFF does not receive student-directed contributions through this directory.</span></div></div></section>
 <section className="section cream support-how"><div className="shell"><div className="section-head"><div><div className="eyebrow">A clearer way to connect</div><h2>One platform. Two distinct ways to help.</h2></div><p>Direct support for a student and charitable support for EFF are presented separately so donors understand exactly where each contribution goes.</p></div><div className="support-how-grid"><article><span>01</span><UserRoundPlus/><h3>A student creates a profile</h3><p>They share a public story, external support link, and private redacted verification.</p></article><article><span>02</span><ShieldCheck/><h3>EFF reviews it</h3><p>Staff checks the submission and may request corrections before publication.</p></article><article><span>03</span><HeartHandshake/><h3>Donors choose how to help</h3><p>Support a student externally, or donate separately to EFF’s retention work.</p></article></div></div></section>
 <section className="section white" id="students"><div className="shell"><div className="support-directory-heading"><div><div className="eyebrow">Approved profiles</div><h2>Meet the students</h2><p>Search by name, school, major, city, or state.</p></div><form className="support-search"><Search/><input name="q" defaultValue={q??""} aria-label="Search student profiles" placeholder="Try a school or major"/><button className="button">Search</button></form></div>
 {profiles.length?<div className="student-profile-grid">{profiles.map(profile=><article className="student-profile-card" key={profile.id}><div className="student-profile-photo">{profile.photoUrl?<img src={profile.photoUrl} alt=""/>:<span>{studentInitials(profile.displayName)}</span>}<small><CheckCircle2/> EFF reviewed</small></div><div className="student-profile-body"><div className="eyebrow">{profile.institution}</div><h3>{profile.displayName}</h3><p className="support-headline">{profile.headline}</p><dl><div><dt>Seeking</dt><dd>{formatSupportAmount(profile.amountNeeded)}</dd></div>{profile.major&&<div><dt>Studying</dt><dd>{profile.major}</dd></div>}</dl><Link className="button" href={`/meet-a-student/${profile.slug}`}>Read {profile.displayName.split(" ")[0]}’s story <ArrowRight/></Link></div></article>)}</div>:<div className="support-empty"><Search/><h3>{q?"No approved profiles matched that search.":"Approved student profiles will appear here."}</h3><p>{q?"Try a school name, major, city, or shorter term.":"Students can submit now; EFF reviews each profile before publication."}</p>{q&&<Link className="button outline" href="/meet-a-student">Clear search</Link>}</div>}</div></section>
 <section className="section support-donor-choice"><div className="shell support-choice-grid"><div><div className="eyebrow light">Invest in the movement</div><h2>Want to help EFF reach more students?</h2><p>A separate donation to Esther Funds Foundation supports the systems, advocacy, and student-retention work that make this platform possible.</p><a className="button light" href="https://www.estherfundsfoundation.org" target="_blank" rel="noopener noreferrer">Support EFF <ExternalLink/></a></div><div className="support-choice-clarity"><strong>Clear by design</strong><p>A student’s button opens their approved external page. EFF’s button opens the foundation website. We do not add an EFF charge to a student’s checkout or represent personal support as a charitable gift to EFF.</p></div></div></section>
 </main>}
