import Link from "next/link";
import {ExternalLink,MapPin,Search,ShieldCheck} from "lucide-react";
import {createClient} from "@/lib/supabase/server";

type Params={q?:string;state?:string;category?:string};
const categories=["financial_aid","basic_needs","housing","food","transportation","mental_health","public_benefits","legal_aid","childcare","technology","emergency_relief"];
export default async function StudentStabilityAtlas({searchParams}:{searchParams:Promise<Params>}){
 const p=await searchParams;const db=await createClient();const clean=(p.q??"").trim().replaceAll("%","");
 let resources=db.from("student_resource_sources").select("id,source_type,title,provider,category,state_code,county,city,summary,official_url,contact,availability_status,last_verified_at").is("archived_at",null).in("availability_status",["verified_open","seasonal"]).order("source_type").order("title").limit(100);
 if(clean)resources=resources.or(`title.ilike.%${clean}%,provider.ilike.%${clean}%,summary.ilike.%${clean}%,city.ilike.%${clean}%,county.ilike.%${clean}%`);
 if(p.state)resources=resources.or(`state_code.eq.${p.state.toUpperCase()},source_type.eq.national`);if(p.category)resources=resources.eq("category",p.category);
 let schools=db.from("college_directory").select("unitid,name,city,state,website,financial_aid_url,college_contact_directory(department_key,department_name,contact_url,phone,email,verification_status)").eq("active",true).limit(25);
 if(clean)schools=schools.ilike("name",`%${clean}%`);else if(p.state)schools=schools.eq("state",p.state);else schools=schools.limit(0);
 const[{data:resourceRows,error},{data:schoolRows}]=await Promise.all([resources,schools]);
 return <main className="section white"><div className="shell"><div className="section-head"><div><div className="eyebrow">Verified support routes</div><h2>Student Stability Atlas</h2><p className="muted">Search official campus and community resources without having to know which office to ask first.</p></div><Link className="button" href="/help-desk/open-case">Get help now</Link></div>
  <form className="card scholarship-filters"><label>School, city, county, or need<input name="q" defaultValue={p.q} placeholder="Howard University, rent, groceries…"/></label><label>State<input name="state" defaultValue={p.state} maxLength={2} placeholder="GA"/></label><label>Type<select name="category" defaultValue={p.category??""}><option value="">All support types</option>{categories.map(x=><option value={x} key={x}>{x.replaceAll("_"," ")}</option>)}</select></label><button className="button"><Search size={17}/> Search</button></form>
  <div className="notice"><ShieldCheck size={18}/><span>EFF links to the official provider and records when it was checked. A listing does not guarantee eligibility, availability, funding, or an outcome. For immediate danger call 911; for a mental-health crisis call or text 988.</span></div>
  {schoolRows?.length?<section><div className="eyebrow">Official campus routes</div><div className="cards">{schoolRows.map(s=><article className="card" key={s.unitid}><MapPin/><h3>{s.name}</h3><p className="muted">{s.city}, {s.state}</p><div className="resource-actions">{s.website&&<a href={s.website} target="_blank" rel="noreferrer">School website</a>}{s.financial_aid_url&&<a href={s.financial_aid_url} target="_blank" rel="noreferrer">Financial aid</a>}{s.college_contact_directory?.filter(c=>c.contact_url).slice(0,6).map(c=><a key={c.department_key} href={c.contact_url!} target="_blank" rel="noreferrer">{c.department_name}</a>)}</div></article>)}</div></section>:null}
  <section><div className="eyebrow">Community, state, and national routes</div>{error?<div className="directory-empty"><h3>Resources are temporarily unavailable</h3></div>:resourceRows?.length?<div className="scholarship-grid">{resourceRows.map(r=><article className="card" key={r.id}><div className="eyebrow">{r.source_type} · {r.category.replaceAll("_"," ")}</div><h3>{r.title}</h3><p className="muted">{r.provider}{r.city?` · ${r.city}`:""}{r.state_code?`, ${r.state_code}`:""}</p><p>{r.summary}</p><a className="card-link" href={r.official_url} target="_blank" rel="noreferrer">Open official resource <ExternalLink size={15}/></a><small>Checked {r.last_verified_at?new Date(r.last_verified_at).toLocaleDateString():"pending"}</small></article>)}</div>:<div className="directory-empty"><h3>No verified match yet</h3><p>Try a broader phrase or <Link href="/help-desk/open-case">open a Help Desk request</Link> so EFF can help route the need.</p></div>}</section>
 </div></main>;
}
