import type {Metadata} from "next";
import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {CheckCircle2,FileText,LockKeyhole,ShieldCheck} from "lucide-react";
import {careerRoleMap,volunteerRoleSlugs} from "@/lib/careers";
import {createClient} from "@/lib/supabase/server";
import {submitCareerApplication} from "../actions";

export const metadata:Metadata={title:"Apply to EFF"};

export default async function CareerApplicationPage({params,searchParams}:{params:Promise<{role:string}>;searchParams:Promise<{error?:string}>}){
  const {role:slug}=await params;const {error}=await searchParams;const role=careerRoleMap.get(slug);if(!role)notFound();const volunteer=volunteerRoleSlugs.has(slug);const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect(`/sign-in?next=/careers/apply/${encodeURIComponent(slug)}`);const [{data:profile},{data:careerProfile}]=await Promise.all([supabase.from("profiles").select("legal_name,preferred_name,primary_email,phone").eq("id",user.id).single(),supabase.from("career_profiles").select("*").eq("user_id",user.id).maybeSingle()]);
  return <main className="section white"><div className="shell career-application-shell"><Link className="card-link" href="/careers">← Careers & service</Link><div className="career-application-title"><div><div className="eyebrow">{role.category}</div><h2>{role.title}</h2><p>{role.summary}</p></div><aside><strong>{role.compensation}</strong><span>{role.commitment}</span></aside></div>
    <div className="career-detail-grid"><section className="career-detail-card"><h3>What you would do</h3><ul>{role.responsibilities.map(item=><li key={item}><CheckCircle2/>{item}</li>)}</ul></section><section className="career-detail-card"><h3>What we are looking for</h3><ul>{role.qualifications.map(item=><li key={item}><CheckCircle2/>{item}</li>)}</ul></section></div>
    <div className="notice"><strong>Signed in as {profile?.primary_email??user.email}.</strong><br/>Your application will appear in your <Link className="card-link" href="/careers/dashboard">careers dashboard</Link>. You can update reusable information in your <Link className="card-link" href="/careers/profile">professional profile</Link>.</div>{error&&<div className="notice error-text" role="alert"><strong>We could not submit your application.</strong><br/>{error}</div>}
    <form action={submitCareerApplication} className="application-form career-form" encType="multipart/form-data"><input type="hidden" name="roleSlug" value={role.slug}/><input className="career-honeypot" name="companyWebsite" tabIndex={-1} autoComplete="off" aria-hidden="true"/>
      <section className="form-section"><span className="section-number">01</span><h3>Your information</h3><p className="muted">Review the information copied from your careers profile. Changes made here will also update that reusable profile. Do not submit Social Security numbers, tax records, passwords, banking information, or verification codes.</p><div className="form-grid"><label>Full legal name<input name="fullName" required maxLength={120} autoComplete="name" defaultValue={profile?.legal_name??""}/></label><label>Preferred name <span className="optional">optional</span><input name="preferredName" maxLength={80} defaultValue={profile?.preferred_name??""}/></label><label>Portal account email<input name="email" type="email" readOnly aria-readonly="true" value={profile?.primary_email??user.email??""}/></label><label>Phone<input name="phone" type="tel" required maxLength={40} autoComplete="tel" defaultValue={profile?.phone??""}/></label><label>City, state/province, country<input name="location" required maxLength={160} autoComplete="address-level2" defaultValue={careerProfile?.location??""}/></label><label>Current status<select name="applicantType" required defaultValue={careerProfile?.applicant_type??""}><option value="" disabled>Select one</option><option>Current college student</option><option>Graduate or alumnus</option><option>Working professional</option><option>Other</option></select></label><label>College, university, or employer<input name="institution" required maxLength={180} defaultValue={careerProfile?.institution_or_employer??""}/></label><label>Degree, major, or professional field<input name="degree" required maxLength={180} defaultValue={careerProfile?.degree_or_field??""}/></label><label>Graduation year <span className="optional">if applicable</span><input name="graduationYear" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} defaultValue={careerProfile?.graduation_year??""}/></label><label>LinkedIn or professional profile <span className="optional">optional</span><input name="linkedinUrl" type="url" placeholder="https://" maxLength={500} defaultValue={careerProfile?.linkedin_url??""}/></label></div></section>
      <section className="form-section"><span className="section-number">02</span><h3>Experience and motivation</h3><div className="form-grid"><label className="full-field">Why do you want to serve with Esther Funds Foundation?<textarea name="whyEff" required minLength={100} maxLength={3000}/></label><label className="full-field">Describe the experience most relevant to this role.<textarea name="relevantExperience" required minLength={150} maxLength={5000}/></label><label className="full-field">What would strong, relationship-centered teamwork look like to you?<textarea name="teamCulture" required minLength={100} maxLength={3000}/></label><label>Weekly availability<select name="weeklyAvailability" required defaultValue=""><option value="" disabled>Select one</option><option>1-2 hours</option><option>Up to 3 hours</option><option>Availability varies by week</option></select></label><label>Earliest available start date<input name="startDate" type="date" required/></label></div></section>
      <section className="form-section"><span className="section-number">03</span><h3>Role-specific questions</h3><div className="form-grid">{role.questions.map(question=><label className={question.type==="textarea"?"full-field":undefined} key={question.name}>{question.label}{question.help&&<small>{question.help}</small>}{question.type==="textarea"?<textarea name={question.name} required={question.required} minLength={question.required?80:undefined} maxLength={5000}/>:question.type==="select"?<select name={question.name} required={question.required} defaultValue=""><option value="" disabled>Select one</option>{question.options?.map(option=><option key={option}>{option}</option>)}</select>:<input name={question.name} required={question.required} maxLength={800}/>}</label>)}</div></section>
      <section className="form-section"><span className="section-number">04</span><h3>Résumé and links</h3><div className="career-upload-grid"><label className="career-upload"><FileText/><strong>{role.resumeRequired?"Upload your résumé":"Upload a résumé, if helpful"}</strong><span>PDF or DOCX, up to 8 MB. Do not include sensitive identification or financial information.</span><input name="resume" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required={role.resumeRequired}/></label><label>Portfolio, writing sample, or work link <span className="optional">optional</span><input name="workUrl" type="url" placeholder="https://" maxLength={500} defaultValue={careerProfile?.work_url??""}/></label></div></section>
      <section className="form-section agreement"><span className="section-number">05</span><h3>Confirm before submitting</h3><div className="career-privacy"><LockKeyhole/><p>Your application is used for EFF recruiting and service placement. Access is limited to authorized reviewers and retained according to organizational policy and applicable law.</p></div><label className="check"><input name="truthful" type="checkbox" required/><span>I certify that the information I provided is truthful and that submitted work samples are mine or clearly attributed.</span></label>{volunteer&&<label className="check"><input name="volunteerAcknowledgment" type="checkbox" required/><span>I understand this is freely chosen, unpaid charitable service with no promise of compensation, employment, scholarship selection, or future paid work. I may stop volunteering at any time.</span></label>}<label className="check"><input name="privacyConsent" type="checkbox" required/><span>I consent to EFF using this information to evaluate and communicate about this application.</span></label><label className="check"><input name="writtenTerms" type="checkbox" required/><span>I understand that submitting this form creates no employment, contractor, volunteer, fiduciary, or attorney-client relationship. Any relationship begins only after written terms are signed. A title, stipend, remote schedule, or tax form does not determine worker classification.</span></label><label>Type your full name as your electronic signature<input name="signature" required maxLength={120}/></label></section>
      <div className="form-actions"><Link className="button outline" href="/careers/dashboard">Cancel</Link><button className="button" type="submit"><ShieldCheck size={17}/> Submit application</button></div>
    </form></div></main>;
}
