"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {requireAdmin} from "@/lib/auth/staff";
import {createAdminClient} from "@/lib/supabase/admin";
import {normalizeSupportUrl} from "@/lib/student-support";
import {queueStudentSupportEmail} from "@/lib/student-support-email";
const clean=(value:FormDataEntryValue|null,max:number)=>String(value??"").trim().slice(0,max);
export async function reviewStudentSupportProfile(formData:FormData){
 const{user}=await requireAdmin(),admin=createAdminClient(),id=clean(formData.get("id"),80),decision=clean(formData.get("decision"),30),note=clean(formData.get("reviewNote"),1500);
 if(!["approved","changes_requested","declined","paused"].includes(decision))redirect(`/admin/student-support/${id}?error=${encodeURIComponent("Choose a valid review action.")}`);if(decision!=="approved"&&note.length<10)redirect(`/admin/student-support/${id}?error=${encodeURIComponent("Add a clear student-facing explanation.")}`);
 const checklist={identity:formData.get("checkIdentity")==="on",documentation:formData.get("checkDocumentation")==="on",story:formData.get("checkStory")==="on",link:formData.get("checkLink")==="on",privacy:formData.get("checkPrivacy")==="on"};
 const{data:item}=await admin.from("student_support_profiles").select("*").eq("id",id).maybeSingle();if(!item)redirect("/admin/student-support?error=Profile+not+found.");const{data:student}=await admin.from("profiles").select("primary_email,preferred_name,legal_name").eq("id",item.student_id).maybeSingle();const normalized=normalizeSupportUrl(String(item.fundraiser_url??""));
 if(decision==="approved"&&(!Object.values(checklist).every(Boolean)||!item.verification_document_path||!normalized))redirect(`/admin/student-support/${id}?error=${encodeURIComponent("Complete every verification check and confirm the document and HTTPS link.")}`);
 let publicPhotoPath:string|null=item.public_photo_path??null;if(decision==="approved"&&item.private_photo_path){const downloaded=await admin.storage.from("student-support-private").download(item.private_photo_path);if(downloaded.error||!downloaded.data)redirect(`/admin/student-support/${id}?error=${encodeURIComponent("The photo could not be prepared for publication.")}`);publicPhotoPath=`profiles/${id}.${item.private_photo_path.split(".").pop()?.toLowerCase()||"jpg"}`;const uploaded=await admin.storage.from("student-support-public").upload(publicPhotoPath,downloaded.data,{upsert:true,contentType:downloaded.data.type||undefined});if(uploaded.error)redirect(`/admin/student-support/${id}?error=${encodeURIComponent("The approved photo could not be published.")}`);}
 if(decision!=="approved"&&publicPhotoPath){await admin.storage.from("student-support-public").remove([publicPhotoPath]);publicPhotoPath=null;}
 const now=new Date().toISOString();const{error}=await admin.from("student_support_profiles").update({status:decision,review_note:note||null,verification_checklist:checklist,reviewed_at:now,reviewed_by:user.id,link_verified_at:decision==="approved"?now:null,published_at:decision==="approved"?now:null,public_photo_path:publicPhotoPath,fundraiser_url:normalized?.url??item.fundraiser_url,fundraiser_platform:normalized?.platform??item.fundraiser_platform,updated_at:now}).eq("id",id);if(error){console.error("Meet a Student review failed",error);redirect(`/admin/student-support/${id}?error=${encodeURIComponent("The review could not be saved.")}`);}
 const name=student?.preferred_name||student?.legal_name||item.display_name||"Student",email=String(student?.primary_email??""),event=decision==="approved"?"student_support_approved":decision==="declined"?"student_support_declined":"student_support_changes",path=decision==="approved"?`/meet-a-student/${item.slug}`:"/meet-a-student/apply",message=decision==="approved"?"The EFF national office completed its review and published your profile.":note;
 await queueStudentSupportEmail({recipient:email,templateKey:event,idempotencyKey:`student-support-review:${id}:${decision}:${now}`,name,message,path});await admin.from("notifications").insert({user_id:item.student_id,title:decision==="approved"?"Your Meet a Student profile is live":decision==="declined"?"Meet a Student review complete":"Your Meet a Student profile needs attention",body:message,href:path});await admin.from("audit_events").insert({actor_id:user.id,action:`student_support_profile_${decision}`,target_type:"student_support_profile",target_id:id,metadata_safe:{checklist,platform:normalized?.platform??null,has_public_photo:Boolean(publicPhotoPath)}});
 revalidatePath("/meet-a-student");revalidatePath(`/meet-a-student/${item.slug}`);revalidatePath("/meet-a-student/apply");revalidatePath("/admin/student-support");revalidatePath(`/admin/student-support/${id}`);redirect(`/admin/student-support/${id}?updated=1`);
}
