import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {saveCommonApplication} from "./actions";

export default async function Page({searchParams}:{searchParams:Promise<{saved?:string,error?:string}>}){
  const params=await searchParams;const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/sign-in?next=%2Fapply-everywhere%2Fapplication");
  const {data:profile}=await db.from("applyall_profiles").select("id").eq("user_id",user.id).maybeSingle();if(!profile)redirect("/apply-everywhere/start");
  const {data:app}=await db.from("applyall_common_applications").select("*").eq("profile_id",profile.id).eq("cycle","2027").maybeSingle();const hs=(app?.high_school??{}) as Record<string,string>;const academics=(app?.academics??{}) as Record<string,string>;
  return <main className="applyall"><section className="applyall-workspace"><div className="shell" style={{maxWidth:900}}><span className="applyall-kicker">EFF Reusable College Profile</span><h1>Tell your story once.</h1><p className="applyall-lead">Use these answers while completing multiple official college applications. Review every answer before submitting to a university. Direct EFF delivery is available only for verified participating colleges.</p>{params.saved&&<p className="applyall-complete">Draft saved.</p>}{params.error&&<p className="applyall-alert">{params.error}</p>}<form action={saveCommonApplication} className="card"><h2>Applicant information</h2><label>Legal name<input name="legalName" required defaultValue={app?.legal_name??""}/></label><label>Preferred name<input name="preferredName" defaultValue={app?.preferred_name??""}/></label><label>Date of birth<input type="date" name="dateOfBirth" required defaultValue={app?.date_of_birth??""}/></label><label>Phone<input name="phone" defaultValue={app?.phone??""}/></label><h2>Education</h2><label>High school<input name="highSchool" required defaultValue={hs.name??""}/></label><label>Graduation year<input name="graduationYear" required defaultValue={hs.graduationYear??""}/></label><label>GPA<input name="gpa" required defaultValue={academics.gpa??""}/></label><label>Intended major<input name="intendedMajor" required defaultValue={academics.intendedMajor??""}/></label><h2>Your story</h2><label>Personal essay<textarea name="essay" required rows={12} maxLength={6500} defaultValue={app?.essay??""}/></label><label>Additional information<textarea name="additionalInformation" rows={6} defaultValue={app?.additional_information??""}/></label><div className="hero-actions"><button className="button">Save my reusable profile</button>{app&&<Link className="button outline" href="/apply-everywhere/dashboard">Continue to my schools</Link>}</div></form></div></section></main>;
}
