import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {confirmFutureLinkSession,issueFutureLinkServiceVerification,logFutureLinkSession,reportFutureLinkSafety,requestFutureLinkRematch,respondToMatch,signFutureLinkAgreement} from "../actions";

export const metadata:Metadata={title:"My FutureLink Dashboard"};
const statusLabel:Record<string,string>={verification_pending:"Verification in review",additional_documents_required:"Additional information needed",searching_for_match:"Searching for your best match",match_proposed:"A match is ready",awaiting_mentor_acceptance:"Waiting for mentor response",awaiting_mentee_acceptance:"Waiting for mentee response",agreement_required:"Mentorship agreement required",active_match:"Active mentorship",safety_review:"Safety review",paused:"Paused",suspended:"Participation paused",completed:"Completed"};
type MatchProfile={user_id:string;display_name:string;participant_type:string;school:string|null;degree_level:string|null;academic_field:string|null;profession:string|null;career_fields:string[]|null;support_offered:string[]|null;support_needed:string[]|null;experience_tags:string[]|null;timezone:string|null;meeting_format:string|null;communication_styles:string[]|null;bio:string|null;profile_photo_path:string|null;approved_contact_methods:string[]|null;phone_private:string|null;primary_email?:string|null};

export default async function FutureLinkDashboard({searchParams}:{searchParams:Promise<{submitted?:string;reported?:string;error?:string}>}){const params=await searchParams;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/sign-in?next=/future-link/dashboard");const {data:profile}=await supabase.from("futurelink_profiles").select("*").eq("user_id",user.id).maybeSingle();if(!profile)redirect("/future-link/apply");const admin=createAdminClient();const {data:matches}=await admin.from("futurelink_matches").select("*").or(`mentee_id.eq.${user.id},mentor_id.eq.${user.id}`).order("created_at",{ascending:false}).limit(10);const current=(matches??[]).find(m=>!["declined","ended","completed"].includes(m.status));let other:MatchProfile|null=null;let photoUrl:string|null=null;if(current){const otherId=current.mentee_id===user.id?current.mentor_id:current.mentee_id;const {data}=await admin.from("futurelink_profiles").select("user_id,display_name,participant_type,school,degree_level,academic_field,profession,career_fields,support_offered,support_needed,experience_tags,timezone,meeting_format,communication_styles,bio,profile_photo_path,approved_contact_methods,phone_private").eq("user_id",otherId).maybeSingle();other=data as MatchProfile|null;if(data?.profile_photo_path){const signed=await admin.storage.from("futurelink-profile-media").createSignedUrl(data.profile_photo_path,3600);photoUrl=signed.data?.signedUrl??null;}if(current.status==="active"&&current.contact_released_at&&other){const {data:base}=await admin.from("profiles").select("primary_email").eq("id",otherId).maybeSingle();other={...other,primary_email:base?.primary_email};}}
  const {data:agreements}=current?await admin.from("futurelink_agreements").select("user_id,signed_at").eq("match_id",current.id):{data:[]};
  const {data:sessions}=current?await admin.from("futurelink_sessions").select("*").eq("match_id",current.id).order("session_date",{ascending:false}):{data:[]};
  const confirmed=(sessions??[]).filter(s=>s.status==="confirmed");const confirmedMinutes=confirmed.reduce((sum,row)=>sum+row.duration_minutes,0);const isMentor=current?.mentor_id===user.id;const signed=agreements?.some(a=>a.user_id===user.id);
  return <main className="fl-page fl-dashboard"><section className="fl-dashboard-head"><div className="fl-shell"><div><div className="fl-kicker">My FutureLink</div><h1>{statusLabel[profile.status]??profile.status.replaceAll("_"," ")}</h1><p>Welcome, {profile.display_name}. Your private mentorship workspace keeps every next step in one place.</p></div><Link className="fl-button light" href="/future-link">FutureLink home</Link></div></section><div className="fl-shell fl-dashboard-grid"><div className="fl-main-stack">{params.submitted&&<div className="fl-alert success">Your profile was submitted. EFF will review your verification before the system can match you.</div>}{params.reported&&<div className="fl-alert success">Your safety report was received. The match was immediately frozen and the other participant cannot be matched again while EFF reviews it.</div>}{params.error&&<div className="fl-alert">{params.error}</div>}
    {profile.status==="additional_documents_required"&&<section className="fl-panel warning"><div className="fl-kicker">Action needed</div><h2>EFF needs updated verification.</h2><p>{profile.review_note||"Please update your FutureLink application with the requested information."}</p><Link className="fl-button" href="/future-link/apply">Update my application</Link></section>}
    {["verification_pending","searching_for_match","match_eligible"].includes(profile.status)&&<section className="fl-panel"><div className="fl-kicker">What happens next</div><h2>{profile.status==="verification_pending"?"Verification comes before matching.":"FutureLink is comparing eligible profiles."}</h2><p>{profile.status==="verification_pending"?"Your information is private while the National Office reviews identity or enrollment evidence. Nobody can search for you or contact you.":"The system—not a manual list—scores compatible verified mentors and mentees. You will receive an email when a strong match is proposed."}</p><div className="fl-timeline"><span className="done">Profile submitted</span><span className={profile.verification_status==="approved"?"done":"active"}>Verification</span><span className={profile.verification_status==="approved"?"active":""}>Automatic matching</span><span>Mutual acceptance</span><span>Agreement &amp; connection</span></div></section>}
    {current&&other&&<section className="fl-panel fl-match"><div className="fl-kicker">{current.status==="active"?"Your active connection":"Proposed connection"}</div><div className="fl-match-person">{photoUrl?<Image src={photoUrl} alt="" width={72} height={72} unoptimized/>:<div className="fl-avatar">{other.display_name?.slice(0,1)}</div>}<div><h2>{other.display_name}</h2><p>{other.profession||other.degree_level} · {other.school||other.academic_field}</p></div>{current.status!=="active"&&<strong className="fl-score">{current.score}% fit</strong>}</div><p className="fl-bio">{other.bio}</p><div className="fl-tags">{(other.career_fields??[]).slice(0,4).map((v:string)=><span key={v}>{v}</span>)}{(current.reasons??[]).slice(0,3).map((v:string)=><span key={v}>{v}</span>)}</div>
      {["proposed","awaiting_mentor_acceptance","awaiting_mentee_acceptance"].includes(current.status)&&<div className="fl-decision"><p><strong>Your choice is private.</strong> Declining has no penalty and returns eligible participants to the pool.</p><div><form action={respondToMatch}><input type="hidden" name="matchId" value={current.id}/><input type="hidden" name="decision" value="accept"/><button className="fl-button">Accept this match</button></form><form action={respondToMatch}><input type="hidden" name="matchId" value={current.id}/><input type="hidden" name="decision" value="decline"/><button className="fl-button ghost dark">Decline &amp; keep searching</button></form></div></div>}
      {current.status==="agreement_required"&&!signed&&<form action={signFutureLinkAgreement} className="fl-agreement"><h3>Mentorship agreement</h3><p>I will maintain professional boundaries, protect private information, use approved communication methods, and follow the FutureLink Code of Conduct. I understand a mentor is not acting as a therapist, attorney, financial adviser, or university adviser. Either participant or EFF may pause or end this relationship.</p><input type="hidden" name="matchId" value={current.id}/><label>Type your legal name<input name="legalName" required/></label><label className="inline"><input type="checkbox" name="agreementAccepted" value="yes" required/>I understand and agree.</label><button className="fl-button">Sign agreement</button></form>}
      {current.status==="agreement_required"&&signed&&<div className="fl-alert success">You signed the agreement. Contact details will stay private until the other participant signs.</div>}
      {current.status==="active"&&<div className="fl-contact"><h3>Approved contact details</h3><p>These details are for this mentorship only. Never share them publicly.</p>{other.approved_contact_methods?.includes("Email")&&<p><strong>Email:</strong> {other.primary_email}</p>}{(other.approved_contact_methods?.includes("Phone")||other.approved_contact_methods?.includes("Text"))&&<p><strong>Phone:</strong> {other.phone_private}</p>}</div>}
    </section>}
    {current?.status==="active"&&isMentor&&<section className="fl-panel"><div className="fl-kicker">Mentor session log</div><h2>Record a completed meeting.</h2><form action={logFutureLinkSession} className="fl-compact-form"><input type="hidden" name="matchId" value={current.id}/><label>Date<input name="sessionDate" type="date" required/></label><label>Start time<input name="startedAt" type="time"/></label><label>Minutes<input name="durationMinutes" type="number" min="5" max="480" required/></label><label>Format<select name="format" required><option>Virtual</option><option>In person</option><option>Phone</option><option>Other</option></select></label><label>Category<select name="category" required><option>Academic support</option><option>Career planning</option><option>Leadership development</option><option>Resource navigation</option><option>General mentorship</option></select></label><label className="wide">Optional reflection<textarea name="reflection" rows={3}/></label><button className="fl-button">Send for mentee confirmation</button></form></section>}
    {current?.status==="active"&&<section className="fl-panel"><div className="fl-kicker">Service &amp; session ledger</div><h2>{confirmed.length} confirmed session{confirmed.length===1?"":"s"} · {(confirmedMinutes/60).toFixed(1)} hours</h2>{(sessions??[]).length?<div className="fl-session-list">{sessions!.map(s=><div key={s.id}><span><strong>{new Date(`${s.session_date}T12:00:00`).toLocaleDateString()}</strong>{s.category} · {s.duration_minutes} minutes</span><b>{s.status.replaceAll("_"," ")}</b>{s.mentee_id===user.id&&s.status==="pending_mentee_confirmation"&&<div className="fl-inline-actions"><form action={confirmFutureLinkSession}><input type="hidden" name="sessionId" value={s.id}/><input type="hidden" name="decision" value="confirm"/><button>Confirm</button></form><form action={confirmFutureLinkSession}><input type="hidden" name="sessionId" value={s.id}/><input type="hidden" name="decision" value="dispute"/><button>Dispute</button></form></div>}</div>)}</div>:<p>No sessions have been logged yet.</p>}{isMentor&&confirmed.length>0&&<form action={issueFutureLinkServiceVerification}><button className="fl-button">Download verified service record</button></form>}</section>}
  </div><aside className="fl-side-stack"><section className="fl-panel"><div className="fl-kicker">Profile status</div><h3>{profile.verification_status.replaceAll("_"," ")}</h3><p>Participant path: {profile.participant_type.replaceAll("_"," ")}</p><p>Submitted: {profile.submitted_at?new Date(profile.submitted_at).toLocaleDateString():"Not submitted"}</p></section>{current&&!["safety_hold","ended"].includes(current.status)&&<section className="fl-panel"><div className="fl-kicker">Relationship controls</div><h3>You stay in control.</h3><form action={requestFutureLinkRematch}><input type="hidden" name="matchId" value={current.id}/><button className="fl-text-button">End this match &amp; rematch</button></form><details className="fl-report"><summary>Report a safety concern &amp; block</summary><form action={reportFutureLinkSafety}><input type="hidden" name="matchId" value={current.id}/><label>Concern<select name="category" required><option value="">Select</option><option>Harassment or discrimination</option><option>Romantic or sexual solicitation</option><option>Money, loan, investment, or MLM request</option><option>Credential or private-information request</option><option>Threat, stalking, or pressure</option><option>Fraud or impersonation</option><option>Other safety concern</option></select></label><label>What happened?<textarea name="details" rows={5} required/></label><button className="fl-danger">Submit report &amp; freeze match</button></form></details></section>}</aside></div></main>}
