import Link from "next/link";
import {requireAdmin} from "@/lib/auth/staff";
import {createAdminClient} from "@/lib/supabase/admin";

const TARGET=3000;
export default async function ScholarshipCoverage(){await requireAdmin();const db=createAdminClient();const today=new Date().toISOString().slice(0,10);const [{count:verified},{count:current},{count:review},{count:broken},{data:sources}]=await Promise.all([
 db.from("external_scholarships").select("id",{count:"exact",head:true}).eq("verification_status","verified_current").not("published_at","is",null).is("archived_at",null),
 db.from("external_scholarships").select("id",{count:"exact",head:true}).eq("verification_status","verified_current").not("published_at","is",null).is("archived_at",null).or(`deadline.gte.${today},deadline.is.null`),
 db.from("external_scholarships").select("id",{count:"exact",head:true}).in("verification_status",["needs_verification","needs_recheck"]).is("archived_at",null),
 db.from("external_scholarships").select("id",{count:"exact",head:true}).eq("verification_status","source_closed"),
 db.from("external_sources").select("id,name,permission_status,health,last_success_at,source_observations(count)").order("name")
]);const achieved=current??0,progress=Math.min(100,Math.round(achieved/TARGET*100));return <main className="section white"><div className="shell"><Link className="card-link" href="/admin">← Command center</Link><div className="eyebrow">Evidence, not marketing</div><h2>Scholarship catalog coverage</h2><p className="muted">The public target counts only individually stored, currently published, deduplicated records with an approved source basis and current verification state.</p><div className="stats admin-stats"><div className="stat"><strong>{achieved.toLocaleString()}</strong><span>current verified</span></div><div className="stat"><strong>{(verified??0).toLocaleString()}</strong><span>all verified</span></div><div className="stat"><strong>{(review??0).toLocaleString()}</strong><span>awaiting verification</span></div><div className="stat"><strong>{(broken??0).toLocaleString()}</strong><span>closed or removed</span></div></div><section className="card"><h3>{progress}% of the 3,000-record target</h3><progress max={TARGET} value={achieved} style={{width:"100%"}}>{progress}%</progress><p><strong>{Math.max(0,TARGET-achieved).toLocaleString()}</strong> additional verified current records are required before EFF may claim a 3,000-opportunity catalog.</p></section><div className="table-wrap"><table><thead><tr><th>Source</th><th>Permission basis</th><th>Health</th><th>Observed records</th><th>Last success</th></tr></thead><tbody>{sources?.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.permission_status.replaceAll("_"," ")}</td><td>{s.health}</td><td>{s.source_observations?.[0]?.count??0}</td><td>{s.last_success_at?new Date(s.last_success_at).toLocaleString():"Never"}</td></tr>)}</tbody></table></div><div className="notice"><strong>Publication gate:</strong> Discovery catalogs may be used to locate opportunities, but their licensed descriptions are not copied. EFF publishes independently verified facts and the provider’s official application link only when the source basis permits it.</div></div></main>}
