import {NextRequest,NextResponse} from "next/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {runFutureLinkMatching} from "@/lib/futurelink-matching";
import {queueFutureLinkEmail} from "@/lib/futurelink-email";
export async function GET(request:NextRequest){if(!process.env.CRON_SECRET||request.headers.get("authorization")!==`Bearer ${process.env.CRON_SECRET}`)return NextResponse.json({error:"Unauthorized"},{status:401});const admin=createAdminClient();const matching=await runFutureLinkMatching(50);const cutoff=new Date(Date.now()-24*60*60*1000).toISOString();const {data:matches}=await admin.from("futurelink_matches").select("id,mentee_id,mentor_id,status,proposed_at,mentor_accepted_at,mentee_accepted_at").in("status",["proposed","awaiting_mentor_acceptance","awaiting_mentee_acceptance","agreement_required"]).lt("updated_at",cutoff).limit(100);let reminders=0;for(const match of matches??[]){for(const userId of [match.mentee_id,match.mentor_id]){const waiting=match.status==="agreement_required"?"Your FutureLink match is waiting for the mentorship agreement.":"A proposed FutureLink match is waiting for your private response.";const day=new Date().toISOString().slice(0,10);if(await queueFutureLinkEmail({userId,templateKey:"futurelink_reminder",idempotencyKey:`futurelink-reminder:${match.id}:${userId}:${day}`,payload:{message:waiting,application_path:"/future-link/dashboard"}}))reminders++;}}
  const now=new Date(),windowEnd=new Date(now.getTime()+24*60*60*1000);const {data:plans}=await admin.from("futurelink_meeting_plans").select("id,match_id,next_meeting_at,last_reminder_for,futurelink_matches!inner(mentee_id,mentor_id,status)").eq("futurelink_matches.status","active").gte("next_meeting_at",now.toISOString()).lte("next_meeting_at",windowEnd.toISOString()).limit(100);let meetingReminders=0;
  for(const plan of plans??[]){if(plan.last_reminder_for===plan.next_meeting_at)continue;const match=Array.isArray(plan.futurelink_matches)?plan.futurelink_matches[0]:plan.futurelink_matches;if(!match)continue;for(const userId of [match.mentee_id,match.mentor_id])if(await queueFutureLinkEmail({userId,templateKey:"futurelink_meeting_reminder",idempotencyKey:`futurelink-meeting:${plan.id}:${plan.next_meeting_at}:${userId}`,payload:{message:`Your next FutureLink meeting is scheduled for ${new Date(plan.next_meeting_at!).toLocaleString("en-US")}.`,application_path:"/future-link/dashboard"}}))meetingReminders++;await admin.from("futurelink_meeting_plans").update({last_reminder_for:plan.next_meeting_at}).eq("id",plan.id);}
  return NextResponse.json({...matching,reminders,meetingReminders});}
export const maxDuration=60;
