import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {ArrowRight,BriefcaseBusiness,GraduationCap,HeartHandshake,LockKeyhole,ShieldCheck,Sparkles,UsersRound} from "lucide-react";

export const metadata:Metadata={title:"EFF FutureLink",description:"Verified mentorship for college students, peer mentors, graduates, and professionals."};

export default function FutureLinkHome(){return <main className="fl-page">
  <section className="fl-hero"><div className="fl-shell fl-hero-grid"><div><div className="fl-kicker">Esther Funds Foundation presents</div><h1>EFF <em>FutureLink</em></h1><p className="fl-display">You shouldn&apos;t have to figure college out alone.</p><p className="fl-lead">Find someone who&apos;s been there—or become the person who helps someone else make it through.</p><div className="fl-actions"><Link className="fl-button light" href="/future-link/apply?path=mentee">Find My Guide<ArrowRight/></Link><Link className="fl-button outline" href="/future-link/apply?path=mentor">Become a Guide</Link></div></div><div className="fl-hero-card"><Image src="/brand/eff-logo.png" alt="Esther Funds Foundation" width={112} height={112}/><span>Verified connection. Clear boundaries. Real support.</span><strong>Mentorship built for the whole college journey.</strong><div className="fl-proof"><ShieldCheck/>Every participant is verified before becoming eligible for matching.</div></div></div></section>
  <section className="fl-paths"><div className="fl-shell"><div className="fl-section-head"><span>Choose your pathway</span><h2>One network. Three ways to belong.</h2><p>The system builds your match from structured academic, career, support, availability, and communication preferences.</p></div><div className="fl-card-grid">
    <article><GraduationCap/><h3>College students</h3><p>Receive guidance from someone whose education or career experience aligns with where you are going.</p><Link href="/future-link/apply?path=mentee">Find my guide<ArrowRight/></Link></article>
    <article><UsersRound/><h3>Peer mentors</h3><p>Support another student while building leadership experience and verified service hours.</p><Link href="/future-link/apply?path=peer">Serve as a peer mentor<ArrowRight/></Link></article>
    <article><BriefcaseBusiness/><h3>Graduate &amp; professional mentors</h3><p>Turn what you learned into a practical bridge for the next generation of students.</p><Link href="/future-link/apply?path=professional">Become a professional guide<ArrowRight/></Link></article>
  </div></div></section>
  <section className="fl-how"><div className="fl-shell"><div className="fl-section-head"><span>Designed for safety and fit</span><h2>The system does the matching.</h2></div><div className="fl-steps"><div><b>01</b><ShieldCheck/><h3>Apply &amp; verify</h3><p>Create a structured profile and submit private verification. Nobody enters the match pool unverified.</p></div><div><b>02</b><Sparkles/><h3>Compatibility scored</h3><p>FutureLink weighs support goals, expertise, academic and career alignment, availability, timezone, and meeting preferences.</p></div><div><b>03</b><HeartHandshake/><h3>Both people choose</h3><p>The mentor and mentee independently accept, sign the agreement, and only then receive approved contact details.</p></div></div></div></section>
  <section className="fl-safety"><div className="fl-shell fl-safety-grid"><div><LockKeyhole/><div className="fl-kicker">Private by design</div><h2>Not a public directory. Not a dating app.</h2></div><div><p>Dates of birth, home addresses, verification documents, IDs, private phone numbers, and personal email addresses are never displayed publicly.</p><ul><li>Adults age 18+ only</li><li>Mutual acceptance before connection</li><li>Report, block, end, and rematch controls</li><li>Safety reports immediately freeze the relationship</li><li>Verified session and service-hour ledger</li></ul></div></div></section>
  <section className="fl-cta"><div className="fl-shell"><span>For such a time as this.</span><h2>Become the guide you once needed.</h2><p>Applications are reviewed by Esther Funds Foundation before automated matching begins.</p><div className="fl-actions center"><Link className="fl-button" href="/future-link/apply">Start my FutureLink profile</Link><Link className="fl-button ghost" href="/future-link/dashboard">Open my dashboard</Link></div></div></section>
</main>}
