import Link from "next/link";
import {requireAdmin} from "@/lib/auth/staff";
import {createAdminClient} from "@/lib/supabase/admin";
import {updateHowardCase} from "./actions";

type Query={status?:string;q?:string};
const statuses=["advocacy_sent","howard_review","reinstated","student_withdrew","closed_no_resolution","delivery_failed"];

export default async function HowardHelpAdmin({searchParams}:{searchParams:Promise<Query>}){
  const query=await searchParams;await requireAdmin();const admin=createAdminClient();
  let request=admin.from("howard_help_cases").select("*").order("created_at",{ascending:false}).limit(300);if(query.status)request=request.eq("status",query.status);
  const [{data:cases,error},{count:signatures}]=await Promise.all([request,admin.from("howard_petition_signatures").select("id",{count:"exact",head:true}).not("verified_at","is",null)]);
  const rows=(cases??[]).filter(row=>!query.q||`${row.case_code} ${row.student_name} ${row.email} ${row.issue_type}`.toLowerCase().includes(query.q.toLowerCase()));
  const count=(status:string)=>(cases??[]).filter(row=>row.status===status).length;
  return <main className="section white"><div className="shell"><Link href="/admin" className="card-link">← Command center</Link><div className="section-head"><div><div className="eyebrow">Student Rescue Operations</div><h2>Howard Help Desk</h2><p className="muted">Consent-verified cases, advocacy delivery, reinstatement outcomes, and petition support.</p></div><Link className="button outline" href="/resources/howard-help">View public desk</Link></div>
    <div className="stats admin-stats"><div className="stat"><strong>{rows.length}</strong><span>cases shown</span></div><div className="stat"><strong>{count("advocacy_sent")+count("howard_review")}</strong><span>active advocacy</span></div><div className="stat"><strong>{count("reinstated")}</strong><span>reinstated</span></div><div className="stat"><strong>{signatures??0}</strong><span>verified signatures</span></div></div>
    <form className="admin-filter"><input name="q" placeholder="Case, student, email, or issue" defaultValue={query.q}/><select name="status" defaultValue={query.status??""}><option value="">All statuses</option>{["pending_verification",...statuses].map(status=><option key={status} value={status}>{status.replaceAll("_"," ")}</option>)}</select><button className="button">Filter</button></form>
    {error?<div className="notice error-text">The Howard Help Desk could not load.</div>:<div className="howard-admin-list">{rows.map(row=><article className="card howard-admin-case" key={row.id}><div className="howard-admin-head"><div><span className="status">{row.status.replaceAll("_"," ")}</span><h3>{row.student_name}</h3><p>{row.case_code} · {row.email}</p></div><small>{new Date(row.created_at).toLocaleString()}</small></div><div className="howard-admin-facts"><span><strong>Issue</strong>{row.issue_type}</span><span><strong>Reported status</strong>{row.enrollment_status}</span><span><strong>Prior balance</strong>{row.balance_before===null?"—":`$${Number(row.balance_before).toLocaleString()}`}</span><span><strong>Current balance</strong>{row.balance_now===null?"—":`$${Number(row.balance_now).toLocaleString()}`}</span><span><strong>Deadline</strong>{row.school_deadline||"Not provided"}</span><span><strong>Anonymous advocacy</strong>{row.anonymous_advocacy_consent?"Authorized":"Not authorized"}</span></div><details><summary>View submitted facts</summary><h4>Pending aid or account information</h4><p>{row.aid_summary}</p><h4>Timeline</h4><p>{row.timeline}</p><h4>Steps taken</h4><p>{row.steps_taken}</p></details><form action={updateHowardCase} className="howard-admin-update"><input type="hidden" name="caseId" value={row.id}/><select name="status" defaultValue={row.status==="pending_verification"?"delivery_failed":row.status}>{statuses.map(status=><option key={status} value={status}>{status.replaceAll("_"," ")}</option>)}</select><textarea name="staffNote" defaultValue={row.staff_note??""} placeholder="Private operational note. Do not paste sensitive documents." maxLength={3000}/><button className="button" type="submit">Save case update</button></form></article>)}</div>}
    <p className="muted">Showing {rows.length} case(s), newest first. The public petition displays only verified totals and never displays email addresses.</p>
  </div></main>;
}
