import Link from "next/link";
import {notFound} from "next/navigation";
import {AlertTriangle,LockKeyhole,MessagesSquare,ShieldCheck} from "lucide-react";
import {requireAdmin} from "@/lib/auth/staff";
import {createAdminClient} from "@/lib/supabase/admin";
import {adminCloseHelpDeskConversation,adminReleaseVolunteer,adminReopenHelpDeskConversation,resolveHelpDeskEscalation,sendAdminHelpDeskMessage} from "../help-desk-actions";

export default async function HelpDeskTranscriptAdmin({params}:{params:Promise<{caseCode:string}>}){
  const {caseCode}=await params;await requireAdmin();const admin=createAdminClient();
  const {data:record}=await admin.from("student_help_cases").select("*").eq("case_code",caseCode.toUpperCase()).maybeSingle();
  if(!record)notFound();
  const {data:conversation}=await admin.from("help_desk_conversations").select("*,help_desk_volunteer_profiles(display_name,notification_email)").eq("case_id",record.id).maybeSingle();
  const [{data:messages},{data:escalations},{data:logs}]=conversation?await Promise.all([
    admin.from("help_desk_messages").select("*").eq("conversation_id",conversation.id).order("created_at",{ascending:true}),
    admin.from("help_desk_escalations").select("*").eq("conversation_id",conversation.id).order("created_at",{ascending:false}),
    admin.from("help_desk_service_logs").select("*,help_desk_volunteer_profiles(display_name,notification_email)").eq("conversation_id",conversation.id).order("started_at",{ascending:false}),
  ]):[{data:[]},{data:[]},{data:[]}];
  const assigned=Array.isArray(conversation?.help_desk_volunteer_profiles)?conversation.help_desk_volunteer_profiles[0]:conversation?.help_desk_volunteer_profiles;
  return <main className="section white"><div className="shell"><Link href="/admin/student-help" className="card-link">← Student Help cases</Link><div className="section-head"><div><div className="eyebrow">Protected executive transcript · {record.case_code}</div><h1>{record.student_name} · {record.school_name}</h1><p>{record.issue_type} · {record.urgency} · deadline {record.school_deadline||"not provided"}</p></div><LockKeyhole/></div>
    <div className="help-desk-admin-case-grid"><section><div className="card"><h2>Student intake</h2><p><strong>What happened:</strong><br/>{record.situation_summary}</p><p><strong>Steps taken:</strong><br/>{record.steps_taken}</p><p><strong>Documents listed:</strong><br/>{record.documents_available?.join(", ")||"None listed"}</p></div>
      <div className="card"><div className="section-head"><div><h2>Full secure transcript</h2><p>{messages?.length??0} recorded messages</p></div><MessagesSquare/></div><div className="help-desk-transcript">{(messages??[]).map(message=><article className={`help-desk-message ${message.sender_type}`} key={message.id}><div><strong>{message.sender_type}</strong><time>{new Date(message.created_at).toLocaleString()}</time></div><p>{message.body}</p>{(message.safety_flag||message.conduct_flag)&&<span className="help-desk-flag"><AlertTriangle/>Flagged</span>}</article>)}</div>{conversation&&conversation.status!=="closed"&&conversation.status!=="safety_locked"&&<form action={sendAdminHelpDeskMessage} className="stack"><input type="hidden" name="conversationId" value={conversation.id}/><label>Reply as EFF National Office<textarea name="body" required minLength={2} maxLength={6000}/></label><button className="button">Send secure message</button></form>}</div>
    </section><aside>{conversation?<><div className="card"><h2>Conversation controls</h2><p><span className={`status ${conversation.status}`}>{conversation.status.replaceAll("_"," ")}</span></p><p><strong>Assigned:</strong> {assigned?.display_name||"No volunteer"}</p>{assigned&&<form action={adminReleaseVolunteer}><input type="hidden" name="conversationId" value={conversation.id}/><button className="button outline">Release and requeue</button></form>}{conversation.status==="closed"?<form action={adminReopenHelpDeskConversation}><input type="hidden" name="conversationId" value={conversation.id}/><button className="button">Reopen case</button></form>:<form action={adminCloseHelpDeskConversation} className="stack"><input type="hidden" name="conversationId" value={conversation.id}/><label>Close reason and next step<textarea name="reason" required minLength={10} maxLength={1000}/></label><button className="button danger-button">Close conversation</button></form>}</div><div className="card"><h2>Escalations</h2>{(escalations??[]).map(item=><article className="help-desk-escalation" key={item.id}><span className={`status ${item.severity}`}>{item.severity}</span><strong>{item.escalation_type.replaceAll("_"," ")}</strong><p>{item.summary}</p><small>{new Date(item.created_at).toLocaleString()}</small>{item.status!=="resolved"&&<form action={resolveHelpDeskEscalation}><input type="hidden" name="escalationId" value={item.id}/><button className="button outline">Mark resolved</button></form>}</article>)}{!escalations?.length&&<p className="muted">No escalations.</p>}</div><div className="card"><h2>Service records</h2>{(logs??[]).map(log=>{const v=Array.isArray(log.help_desk_volunteer_profiles)?log.help_desk_volunteer_profiles[0]:log.help_desk_volunteer_profiles;return <p key={log.id}><strong>{v?.display_name||"Volunteer"}:</strong> {log.minutes_credited} minutes · {log.volunteer_message_count} messages<br/><small>{log.closeout_summary||"Active record"}</small></p>})}</div></>:<div className="card"><ShieldCheck/><h2>Secure conversation not issued</h2><p>Use the case list to issue a secure Help Desk link to this verified student.</p></div>}</aside></div>
  </div></main>;
}
