import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

const statusLabel:Record<string,string>={submitted:"Submitted",in_review:"In review",interview:"Interview stage",selected:"Selected",not_selected:"Not selected",withdrawn:"Withdrawn"};

export default async function CareerApplicationDetail({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect(`/sign-in?next=/careers/applications/${encodeURIComponent(id)}`);
  const {data:item}=await supabase.from("career_applications").select("id,role_title,category,posting_term,status,full_name,email,phone,location,applicant_type,institution,degree,graduation_year,linkedin_url,work_url,weekly_availability,available_start_date,why_eff,relevant_experience,team_culture,role_answers,resume_filename,created_at,updated_at").eq("id",id).maybeSingle();if(!item)notFound();
  const answers=Object.entries((item.role_answers??{}) as Record<string,string>);
  return <main className="section white"><div className="shell" style={{maxWidth:900}}><Link className="card-link" href="/careers/dashboard">← Careers dashboard</Link><div className="eyebrow">{item.posting_term} · {item.category}</div><h2>{item.role_title}</h2><div className="notice"><strong>Status: {statusLabel[item.status]??item.status.replaceAll("_"," ")}</strong><br/>Last updated {new Date(item.updated_at).toLocaleString()}. Selection is not final until written terms are signed.</div><section className="card"><h3>Applicant profile at submission</h3><p><strong>{item.full_name}</strong><br/>{item.email}<br/>{item.phone}<br/>{item.location}</p><p>{item.applicant_type} · {item.institution}<br/>{item.degree}{item.graduation_year?` · ${item.graduation_year}`:""}</p>{item.linkedin_url&&<p><a className="card-link" href={item.linkedin_url} target="_blank" rel="noopener noreferrer">Professional profile</a></p>}{item.work_url&&<p><a className="card-link" href={item.work_url} target="_blank" rel="noopener noreferrer">Work sample or portfolio</a></p>}{item.resume_filename&&<p>Résumé received: <strong>{item.resume_filename}</strong></p>}</section><section className="card"><h3>Experience and availability</h3><p><strong>Availability:</strong> {item.weekly_availability}; available from {new Date(`${item.available_start_date}T12:00:00`).toLocaleDateString()}</p><h4>Why EFF</h4><p>{item.why_eff}</p><h4>Relevant experience</h4><p>{item.relevant_experience}</p><h4>Team culture</h4><p>{item.team_culture}</p></section>{answers.length?<section className="card"><h3>Role-specific responses</h3>{answers.map(([key,value])=><div key={key} style={{borderTop:"1px solid #e4d8ef",padding:"14px 0"}}><strong>{key.replaceAll(/([A-Z])/g," $1").replaceAll("_"," ")}</strong><p>{value}</p></div>)}</section>:null}</div></main>;
}
