import Link from "next/link";
import {notFound} from "next/navigation";
import {ExternalLink,FileCheck2,ShieldAlert} from "lucide-react";
import {requireAdmin} from "@/lib/auth/staff";
import {createAdminClient} from "@/lib/supabase/admin";
import {formatSupportAmount,statusLabels,type StudentSupportStatus} from "@/lib/student-support";
import {reviewStudentSupportProfile} from "../actions";
export default async function StudentSupportReview({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;updated?:string}>}){const{id}=await params,query=await searchParams;await requireAdmin();const admin=createAdminClient();const{data:item}=await admin.from("student_support_profiles").select("*,profiles!student_support_profiles_student_id_fkey(primary_email,legal_name,preferred_name,institution)").eq("id",id).maybeSingle();if(!item)notFound();const[photo,document]=await Promise.all([item.private_photo_path?admin.storage.from("student-support-private").createSignedUrl(item.private_photo_path,600):Promise.resolve({data:null}),item.verification_document_path?admin.storage.from("student-support-private").createSignedUrl(item.verification_document_path,600):Promise.resolve({data:null})]);const checklist=(item.verification_checklist??{}) as Record<string,boolean>,student=item.profiles as unknown as {primary_email?:string;legal_name?:string;preferred_name?:string;institution?:string}|null;return <main className="section white"><div className="shell"><Link className="card-link support-back" href="/admin/student-support">← Review queue</Link>{query.error&&<div className="notice support-error"><ShieldAlert/>{query.error}</div>}{query.updated&&<div className="notice"><FileCheck2/>Review saved and the student notification was queued.</div>}<div className="support-page-heading"><div><div className="eyebrow">Protected profile review</div><h1>{item.display_name||student?.preferred_name||student?.legal_name||"Student profile"}</h1><p>{student?.primary_email} · submitted {item.submitted_at?new Date(item.submitted_at).toLocaleString():"as a draft"}</p></div><span className={`support-status status-${item.status}`}>{statusLabels[item.status as StudentSupportStatus]??item.status}</span></div>
 <div className="support-review-layout"><div className="support-review-content"><section className="card"><div className="eyebrow">Public preview</div><h2>{item.headline||"No headline"}</h2><dl className="answer-list"><div><dt>Public name</dt><dd>{item.display_name||"Not provided"}</dd></div><div><dt>Institution</dt><dd>{item.institution||"Not provided"}</dd></div><div><dt>Location</dt><dd>{item.location_text||"Not provided"}</dd></div><div><dt>Major / class year</dt><dd>{[item.major,item.class_year].filter(Boolean).join(" · ")||"Not provided"}</dd></div><div><dt>Amount sought</dt><dd>{formatSupportAmount(item.amount_needed)}</dd></div></dl>{photo.data?.signedUrl&&<a className="button outline" href={photo.data.signedUrl} target="_blank" rel="noopener noreferrer">Open private photo (10-minute link)</a>}</section>
 <section className="card"><div className="eyebrow">Student story</div><h2>Public story and need</h2><h3>Short summary</h3><p>{item.need_summary||"Not provided"}</p><h3>Full story</h3><div className="student-story">{String(item.story??"").split(/\n+/).filter(Boolean).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div></section>
 <section className="card"><div className="eyebrow">External support destination</div><h2>{item.fundraiser_platform||"Unverified external link"}</h2>{item.fundraiser_url?<a className="button" href={item.fundraiser_url} target="_blank" rel="noopener noreferrer">Open and verify link <ExternalLink/></a>:<p>No link provided.</p>}<p className="muted">Confirm the page belongs to this student/guardian, the story and amount are reasonably consistent, and the destination is public HTTPS.</p></section>
 <section className="card"><div className="eyebrow">Private documentation</div><h2>Never publish this file</h2><p>{item.verification_document_name||"No verification file name available"}</p>{document.data?.signedUrl?<a className="button" href={document.data.signedUrl} target="_blank" rel="noopener noreferrer">Open private document (10-minute link)</a>:<div className="notice support-error">No verification document is available.</div>}<div className="privacy-banner" style={{marginTop:18}}><ShieldAlert/><div><strong>Stop if the file contains prohibited sensitive information.</strong><span>Request a redacted replacement; do not reproduce unnecessary Social Security numbers, passwords, bank details, tax returns, or full IDs.</span></div></div></section></div>
 <aside><form action={reviewStudentSupportProfile} className="card support-review-form"><input type="hidden" name="id" value={item.id}/><div className="eyebrow">Publication checklist</div><h2>Verify before approval</h2><label><input type="checkbox" name="checkIdentity" defaultChecked={checklist.identity}/> Account and displayed identity reasonably match.</label><label><input type="checkbox" name="checkDocumentation" defaultChecked={checklist.documentation}/> Redacted document supports the public need.</label><label><input type="checkbox" name="checkStory" defaultChecked={checklist.story}/> Story is accurate, respectful, and safe.</label><label><input type="checkbox" name="checkLink" defaultChecked={checklist.link}/> HTTPS destination was opened and verified.</label><label><input type="checkbox" name="checkPrivacy" defaultChecked={checklist.privacy}/> No prohibited information will be published.</label><label>Student-facing message<textarea name="reviewNote" defaultValue={item.review_note??""} rows={6} maxLength={1500} placeholder="Required for changes, decline, or pause. Be specific and kind."/></label><div className="support-review-buttons"><button className="button" name="decision" value="approved">Approve and publish</button><button className="button outline" name="decision" value="changes_requested">Request changes</button><button className="button outline" name="decision" value="paused">Pause profile</button><button className="text-button danger" name="decision" value="declined">Do not publish</button></div><p className="muted">Every action is audited and queues one student email. Approval does not promise donations or any outcome.</p></form></aside></div></div></main>}
