import {NextRequest,NextResponse} from "next/server";import {createClient} from "@/lib/supabase/server";
const cell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
export async function GET(_request:NextRequest,{params}:{params:Promise<{kind:string}>}){const {kind}=await params;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const {data:roles}=await supabase.from("user_roles").select("role").eq("user_id",user.id);if(!roles?.some(item=>["program_admin","super_admin"].includes(item.role)))return NextResponse.json({error:"Forbidden"},{status:403});let rows:unknown[][]=[];
  if(kind==="applications"){const {data}=await supabase.from("applications").select("id,status,submitted_at,source_system,profiles!applications_applicant_id_fkey(legal_name,primary_email,institution),program_cycles(name,programs(name)),application_answers(question_key,value)");rows=[["Application ID","Applicant","Email","Institution","Program","Cycle","Status","Submitted","Source","Amount Requested"],...(data??[]).map(item=>{const p=item.profiles as unknown as {legal_name:string;primary_email:string;institution:string};const c=item.program_cycles as unknown as {name:string;programs:{name:string}};const answers=item.application_answers as unknown as Array<{question_key:string;value:string}>;return [item.id,p?.legal_name,p?.primary_email,p?.institution,c?.programs?.name,c?.name,item.status,item.submitted_at??"",item.source_system??"portal",answers?.find(x=>x.question_key==="amount_requested")?.value??""]})]}
  else if(kind==="reviews"){const {data}=await supabase.from("review_assignments").select("id,application_id,reviewer_id,conflict_disclosed,has_conflict,assigned_at,reviews(scores,locked_at),profiles!review_assignments_reviewer_id_fkey(legal_name,primary_email)");rows=[["Assignment ID","Application ID","Reviewer","Reviewer Email","Conflict Disclosed","Has Conflict","Scores","Locked","Assigned"],...(data??[]).map(item=>{const p=item.profiles as unknown as {legal_name:string;primary_email:string};const r=(item.reviews as unknown as Array<{scores:unknown;locked_at:string|null}>)?.[0];return [item.id,item.application_id,p?.legal_name,p?.primary_email,item.conflict_disclosed,item.has_conflict,JSON.stringify(r?.scores??{}),r?.locked_at??"",item.assigned_at]})]}
  else if(kind==="awards"){const {data}=await supabase.from("awards").select("id,amount,acceptance_deadline,accepted_at,disbursement_status,scheduled_date,actual_date,payment_reference,applications(id,profiles!applications_applicant_id_fkey(legal_name,primary_email))");rows=[["Award ID","Application ID","Applicant","Email","Amount","Accept By","Accepted","Disbursement Status","Scheduled","Actual","Payment Reference"],...(data??[]).map(item=>{const a=item.applications as unknown as {id:string;profiles:{legal_name:string;primary_email:string}};return [item.id,a?.id,a?.profiles?.legal_name,a?.profiles?.primary_email,item.amount,item.acceptance_deadline,item.accepted_at,item.disbursement_status,item.scheduled_date,item.actual_date,item.payment_reference]})]}
  else if(kind==="legacy"){const {data}=await supabase.from("legacy_application_records").select("id,email,source_record_id,status,original_submitted_at,exclusion_reason,claimed_application_id,created_at");rows=[["Legacy ID","Email","Source Record","Status","Original Submitted","Exclusion","Claimed Application","Imported"],...(data??[]).map(x=>[x.id,x.email,x.source_record_id,x.status,x.original_submitted_at,x.exclusion_reason,x.claimed_application_id,x.created_at])]}
  else if(kind==="scholarships"){const {data}=await supabase.from("external_scholarships").select("id,title,sponsor,amount_text,deadline_kind,deadline,original_url,published_at,archived_at,updated_at");rows=[["ID","Title","Sponsor","Amount","Deadline Type","Deadline","Provider URL","Published","Archived","Updated"],...(data??[]).map(x=>[x.id,x.title,x.sponsor,x.amount_text,x.deadline_kind,x.deadline,x.original_url,x.published_at,x.archived_at,x.updated_at])]}
  else if(kind==="communications"){const {data}=await supabase.from("messages").select("id,application_id,recipient,template_key,status,attempts,provider_id,sent_at,last_error_safe,created_at");rows=[["Message ID","Application ID","Recipient","Type","Status","Attempts","Provider ID","Sent","Safe Error","Created"],...(data??[]).map(x=>[x.id,x.application_id,x.recipient,x.template_key,x.status,x.attempts,x.provider_id,x.sent_at,x.last_error_safe,x.created_at])]}
  else if(kind==="importer-runs"){const {data}=await supabase.from("importer_runs").select("id,status,parser_version,counts,error_safe,started_at,completed_at,external_sources(name)").order("started_at",{ascending:false});rows=[["Run ID","Source","Status","Parser","Counts","Safe Error","Started","Completed"],...(data??[]).map(item=>[item.id,(item.external_sources as unknown as {name:string})?.name,item.status,item.parser_version,JSON.stringify(item.counts),item.error_safe??"",item.started_at,item.completed_at??""])]}
  else if(kind==="exceptions"){const {data}=await supabase.from("scholarship_exceptions").select("id,kind,detail_safe,priority,resolved_at,created_at,importer_runs(id,external_sources(name))");rows=[["Exception ID","Run ID","Source","Kind","Priority","Safe Detail","Created","Resolved"],...(data??[]).map(item=>{const r=item.importer_runs as unknown as {id:string;external_sources:{name:string}};return [item.id,r?.id,r?.external_sources?.name,item.kind,item.priority,item.detail_safe,item.created_at,item.resolved_at]})]}
  else return NextResponse.json({error:"Unknown report"},{status:404});
  await supabase.from("audit_events").insert({actor_id:user.id,action:"report_exported",target_type:"report",target_id:kind,metadata_safe:{row_count:rows.length-1}});return new NextResponse(rows.map(row=>row.map(cell).join(",")).join("\r\n"),{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":`attachment; filename="eff-${kind}-${new Date().toISOString().slice(0,10)}.csv"`}})}
