-- Opens the rolling For Such a Time as This Scholarship with the same verified-need requirements.
do $$ declare p uuid; c uuid; begin
  update public.programs set description='A rolling need-based scholarship for students facing a defining season when timely help can protect continued enrollment.',active=true where slug='for-such-a-time-as-this' returning id into p;
  insert into public.program_cycles(program_id,name,opens_at,closes_at,award_config,status)
  values(p,'Rolling 2026','2026-07-15 00:00:00-04',null,'{"amount":"Based on verified need and available funds","deadline_display":"Rolling — early application strongly encouraged","multiple_recipients":true}'::jsonb,'open')
  on conflict(program_id,name) do update set opens_at=excluded.opens_at,closes_at=null,award_config=excluded.award_config,status='open'
  returning id into c;
  insert into public.form_versions(cycle_id,version,schema,published_at) values(c,1,$json${"title":"For Such a Time as This Scholarship","sections":[{"key":"eligibility","title":"Eligibility","required":["residency_status","fafsa_completed","unmet_need_verified","undergraduate_no_bachelors","accredited_us_institution"]},{"key":"applicant","title":"About you","required":["legal_name","date_of_birth","personal_email","phone","address"]},{"key":"education","title":"Education","required":["institution","student_id","class_standing","major","expected_graduation","enrollment_status"]},{"key":"need","title":"Name your need","required":["amount_requested","need_category","financial_need_description"]},{"key":"essays","title":"Your story and faith reflection","required":["story","faith_reflection"]},{"key":"documents","title":"Documents","required":["headshot","enrollment_proof","financial_need_proof"]},{"key":"certification","title":"Certification","required":["certification","signature"]}]}$json$::jsonb,now()) on conflict(cycle_id,version) do update set schema=excluded.schema,published_at=excluded.published_at;
  insert into public.policy_versions(cycle_id,version,body,published_at) values(c,1,$policy$By submitting, I certify that the information is true and complete; I meet every published eligibility requirement; I authorize Esther Funds Foundation to verify enrollment and financial need; I understand an application does not guarantee an award; and I consent to electronic records and communications about this application. Multiple recipients may be selected, and award amounts depend on verified need and available funds.$policy$,now()) on conflict(cycle_id,version) do update set body=excluded.body,published_at=excluded.published_at;
end $$;
