import Link from "next/link";
import {requireAdmin} from "@/lib/auth/staff";
import {createAdminClient} from "@/lib/supabase/admin";
import {buildSchoolOutreach} from "@/lib/student-help-routing";
import {markSchoolResponse,sendSchoolOutreach} from "./actions";

export default async function StudentHelpAdmin(){
  await requireAdmin();const admin=createAdminClient();const {data:cases}=await admin.from("student_help_cases").select("*,college_directory(unitid,name,website,admissions_url,financial_aid_url,veterans_url,accessibility_url,source_year,reviewed_at)").not("verified_at","is",null).order("created_at",{ascending:false}).limit(250);
  return <main className="section white"><div className="shell"><Link href="/admin" className="card-link">← Command center</Link><div className="section-head"><div><div className="eyebrow">National student support operations</div><h2>Student Help Desk</h2><p className="muted">Verify official destinations, approve first outreach, keep students copied, and stop automation when a school responds.</p></div><Link className="button outline" href="/resources/student-help">View public desk</Link></div>
    <div className="stats admin-stats"><div className="stat"><strong>{cases?.length??0}</strong><span>verified cases</span></div><div className="stat"><strong>{cases?.filter(x=>x.outreach_sent_at&&!x.school_response_at).length??0}</strong><span>awaiting school</span></div><div className="stat"><strong>{cases?.filter(x=>x.school_response_at).length??0}</strong><span>school responses</span></div><div className="stat"><strong>{cases?.filter(x=>x.essentials_requested).length??0}</strong><span>essentials requests</span></div></div>
    <div className="howard-admin-list">{(cases??[]).map(row=>{const draft=buildSchoolOutreach(row);const school=Array.isArray(row.college_directory)?row.college_directory[0]:row.college_directory;return <article className="card howard-admin-case" key={row.id}><div className="howard-admin-head"><div><span className="status">{row.status.replaceAll("_"," ")}</span><h3>{row.student_name} · {row.school_name}</h3><p>{row.case_code} · {row.email}</p></div><small>{new Date(row.created_at).toLocaleString()}</small></div><div className="howard-admin-facts"><span><strong>Issue</strong>{row.issue_type}</span><span><strong>Route</strong>{draft.department}</span><span><strong>Urgency</strong>{row.urgency}</span><span><strong>Deadline</strong>{row.school_deadline||"Not provided"}</span><span><strong>Essentials</strong>{row.essentials_requested?`${row.essentials_term} · $${row.essentials_amount}`:"No"}</span><span><strong>School contact</strong>{row.outreach_sent_at?`Sent ${new Date(row.outreach_sent_at).toLocaleDateString()}`:"Not sent"}</span></div>{school&&<div className="resource-actions"><strong>Official IPEDS routes:</strong>{school.website&&<a href={school.website} target="_blank" rel="noreferrer">School website</a>}{school.admissions_url&&<a href={school.admissions_url} target="_blank" rel="noreferrer">Admissions</a>}{school.financial_aid_url&&<a href={school.financial_aid_url} target="_blank" rel="noreferrer">Financial aid</a>}{school.veterans_url&&<a href={school.veterans_url} target="_blank" rel="noreferrer">Veterans</a>}{school.accessibility_url&&<a href={school.accessibility_url} target="_blank" rel="noreferrer">Accessibility</a>}<small>NCES/IPEDS {school.source_year}</small></div>}<details><summary>Review student facts and outreach draft</summary><h4>Student report</h4><p>{row.situation_summary}</p><h4>Steps taken</h4><p>{row.steps_taken}</p>{!row.outreach_sent_at?<form action={sendSchoolOutreach} className="stack"><input type="hidden" name="caseId" value={row.id}/><label>Verified department email<input type="email" name="departmentEmail" required placeholder="Official school address"/></label><label>Official source page<input type="url" name="sourceUrl" required placeholder="https://school.edu/department/contact"/></label><label>Subject<input name="subject" required defaultValue={draft.subject}/></label><label>Message<textarea name="body" required defaultValue={draft.body} rows={18}/></label><button className="button">Approve and send with student copied</button></form>:<div className="notice"><strong>Sent to {row.department_email}</strong><span> Verified from {row.department_email_source}</span>{!row.school_response_at?<form action={markSchoolResponse}><input type="hidden" name="caseId" value={row.id}/><button className="button outline">Mark school response received</button></form>:<p>School response recorded; automatic department follow-ups are off.</p>}</div>}</details></article>})}</div>
  </div></main>;
}
