import Link from "next/link";
import {KeyRound,MailCheck,ShieldQuestion,UserPlus} from "lucide-react";

export default async function AccountHelp({searchParams}:{searchParams:Promise<{existing?:string}>}){
 const query=await searchParams;
 return <main><section className="resource-hero"><div className="shell"><div className="eyebrow">No more guessing</div><h1>Let’s get you into <span>your portal.</span></h1><p>Choose the situation that matches what you see. Never send anyone your password, Social Security number, or private claim link.</p></div></section><section className="section white"><div className="shell">
 {query.existing==="1"&&<div className="notice"><strong>We found an existing Name Your Need Scholarship application connected to your email address.</strong><br/>Please claim your existing application instead of submitting a new one. Open the newest private EFF invitation sent to your email.</div>}
 <div className="account-help-grid"><article className="card"><UserPlus/><h3>I never created a password</h3><p>Use the newest EFF invitation and select “Create an account.” Register with the exact email address that received the invitation.</p><Link className="button" href="/sign-up">Create my account</Link></article><article className="card"><MailCheck/><h3>I submitted through the old application</h3><p>Open your newest private invitation, sign in or create an account, then use that same invitation to connect your transferred application.</p><Link className="button" href="/sign-in">Sign in, then claim</Link></article><article className="card"><KeyRound/><h3>I created a password before</h3><p>Use password reset once, then open only the newest reset email. Check Spam and Promotions before requesting another link.</p><Link className="button" href="/forgot-password">Reset my password</Link></article><article className="card"><ShieldQuestion/><h3>I see Vercel, expired, or another error</h3><p>Do not request Vercel access. Use the official portal below and email EFF a screenshot with private numbers covered.</p><a className="button" href="mailto:nationals@estherfundsinc.org?subject=EFF%20Portal%20Access%20Help">Email portal support</a></article></div><div className="notice account-help-note"><strong>Official portal:</strong> portal.estherfundsfoundation.org. EFF will never ask you to pay a fee to access your application.</div></div></section></main>;
}
