import Link from "next/link";
import {ArrowRight,BookOpen,BriefcaseBusiness,Church,HeartHandshake,MapPin} from "lucide-react";
import {beyondCircles,beyondResources} from "@/lib/beyond";

export default function BeyondExplore(){return <main className="beyond-inner">
  <section className="beyond-page-hero"><p className="beyond-kicker">Your next chapter, organized</p><h1>Start where life feels <em>unclear.</em></h1><p>Choose a pathway. You do not have to know the perfect question before asking for support.</p></section>
  <section id="circles" className="beyond-content-section"><div className="beyond-section-row"><div><p className="beyond-kicker dark">Beyond Circles</p><h2>Smaller rooms. Deeper connection.</h2></div><p>Circles are built around city, career, faith, season, and shared experience—not an endless public feed.</p></div><div className="beyond-circle-grid">{beyondCircles.map(circle=><article key={circle.slug}><b>{circle.accent}</b><small>{circle.kind}</small><h3>{circle.name}</h3><p>{circle.description}</p><Link href="/beyond/join">Join this Circle <ArrowRight/></Link></article>)}</div></section>
  <section id="career" className="beyond-dark-section"><div><BriefcaseBusiness/><p className="beyond-kicker">Career &amp; workplace</p><h2>Tell us what happened at work.</h2></div><div className="beyond-prompt-list">{["I need work","Fix my résumé","I got an offer","I hate my job","I got laid off","Should I go back to school?","I’m ready for more"].map(item=><span key={item}>{item}</span>)}</div><p className="beyond-boundary">Beyond provides education, peer support, and resource navigation. It does not replace legal, mental-health, financial, or university professionals.</p></section>
  <section id="life" className="beyond-content-section"><div className="beyond-section-row"><div><p className="beyond-kicker dark">Life 101</p><h2>The graduation packet they forgot.</h2></div><p>Practical learning for the decisions adulthood expects you to already understand.</p></div><div className="beyond-resource-grid">{beyondResources.map((resource,index)=><article key={resource.title}><span>0{index+1}</span><small>{resource.category}</small><h3>{resource.title}</h3><p>{resource.description}</p><Link href="/beyond/join">{resource.action} <ArrowRight/></Link></article>)}</div></section>
  <section className="beyond-three"><article><Church/><h3>Beyond Faith</h3><p>Bible studies, prayer, faith-and-work conversations, and Beyond Sunday.</p></article><article><HeartHandshake/><h3>Give Back</h3><p>Mentor, review résumés, host a Circle, volunteer, speak, hire, or support the next student.</p></article><article><MapPin/><h3>Beyond Together</h3><p>City meetups, Beyond Dinner, service days, professional gatherings, and The Crossing.</p></article></section>
  <section className="beyond-final compact"><BookOpen/><p>One profile. Many ways to belong.</p><h2>Let Beyond meet you in this season.</h2><Link href="/beyond/join">Create my profile <ArrowRight/></Link></section>
</main>}
