"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

async function signedIn(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/sign-in?next=/scholarships");return {supabase,user};}
export async function toggleBookmark(formData:FormData){const {supabase,user}=await signedIn();const id=String(formData.get("scholarship_id"));const saved=String(formData.get("saved"))==="true";if(saved)await supabase.from("bookmarks").delete().eq("user_id",user.id).eq("scholarship_id",id);else await supabase.from("bookmarks").insert({user_id:user.id,scholarship_id:id});revalidatePath("/scholarships");revalidatePath("/scholarships/saved");}
export async function reportScholarship(formData:FormData){const {supabase,user}=await signedIn();const id=String(formData.get("scholarship_id"));const reason=String(formData.get("reason"));const detail=String(formData.get("detail")??"").trim();const {error}=await supabase.from("scholarship_reports").insert({scholarship_id:id,reporter_id:user.id,reason,detail:detail||null});if(error)throw new Error("We could not save that report.");revalidatePath(`/scholarships/${String(formData.get("slug"))}`);}
export async function scheduleReminder(formData:FormData){const {supabase,user}=await signedIn();const id=String(formData.get("scholarship_id"));const slug=String(formData.get("slug"));const deadline=String(formData.get("deadline")??"");if(!/^\d{4}-\d{2}-\d{2}$/.test(deadline))throw new Error("This opportunity does not have a fixed reminder date.");const remindAt=new Date(`${deadline}T14:00:00Z`);remindAt.setUTCDate(remindAt.getUTCDate()-7);if(remindAt.getTime()<=Date.now())remindAt.setTime(Date.now()+3600000);const {error}=await supabase.from("scholarship_reminders").upsert({user_id:user.id,scholarship_id:id,remind_at:remindAt.toISOString(),sent_at:null},{onConflict:"user_id,scholarship_id"});if(error)throw new Error("The reminder could not be scheduled.");await supabase.from("notification_preferences").upsert({user_id:user.id,scholarship_reminders:true,updated_at:new Date().toISOString()},{onConflict:"user_id"});revalidatePath(`/scholarships/${slug}`);}
