import type {Metadata} from "next";
import Link from "next/link";
import {AlertTriangle, LockKeyhole, ShieldCheck} from "lucide-react";
import {requestNationalStaffSignInLink} from "@/app/auth/actions";
import {signInHelpDeskStaff} from "@/app/help-desk/actions";
import {safeHelpDeskDestination} from "@/lib/help-desk-context";

export const metadata: Metadata = {title: "Help Desk Staff and Supervisor Access"};

type Query = {error?: string; message?: string; denied?: string; next?: string};

export default async function HelpDeskStaffSignIn({searchParams}: {searchParams: Promise<Query>}) {
  const query = await searchParams;
  const next = safeHelpDeskDestination(query.next, "staff");
  return <main className="section help-desk-auth-page"><div className="shell help-desk-auth-grid"><section className="card"><div className="eyebrow">Restricted Help Desk workspace</div><h1>National Help Desk Staff and Supervisor Access</h1><p>Authorized EFF personnel may review cases, support volunteers, manage escalations, verify service, and monitor National Help Desk operations.</p>{query.error&&<div className="notice error-text" role="alert"><AlertTriangle/>{query.error}</div>}{query.message&&<div className="notice" role="status">{query.message}</div>}{query.denied&&<div className="notice error-text" role="alert"><LockKeyhole/><span><strong>Your EFF account is active, but it does not currently include National Help Desk staff access.</strong><br/>An authorized Help Desk administrator must assign a separate Help Desk role.</span></div>}<form action={signInHelpDeskStaff} className="stack"><input type="hidden" name="next" value={next}/><label>Authorized EFF email<input name="email" type="email" required autoComplete="email"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><button className="button"><ShieldCheck/> Sign In to Help Desk Administration</button></form><hr/><h2>Passwordless national access</h2><form action={requestNationalStaffSignInLink} className="stack"><input type="hidden" name="next" value={next}/><label>Authorized national email<input name="email" type="email" required autoComplete="email"/></label><button className="button outline">Email My Secure Sign-In Link</button></form><div className="help-desk-secondary-links"><Link href="/help-desk/password-reset?context=staff">Reset Staff Password</Link><Link href="/help-desk">Return to National Help Desk</Link><Link href="/help-desk/volunteer/sign-in">Access Volunteer Area</Link><a href="mailto:nationals@estherfundsinc.org?subject=Authorized%20Help%20Desk%20Staff%20Access">Contact Authorized Administrator</a></div></section><aside className="help-desk-auth-aside"><ShieldCheck/><h2>Security requirements</h2><ul><li>Individual account and separate Help Desk role</li><li>Multi-factor authentication where supported</li><li>Failed-login and security-event monitoring</li><li>Immediate role revocation when access is no longer required</li><li>Access only for an approved Help Desk purpose</li></ul><hr/><h3>Scholarship reviewer or administrator?</h3><p>Scholarship applications, scoring, awards, and disbursements remain in Scholarship Administration.</p><Link className="button outline" href="/admin">Go to Scholarship Administration</Link></aside></div></main>;
}
